### ISSUE TITLE
Are there any plans to replace the deprecated MKPinAnnotationView for a new AnnotationView on iOS?

### ISSUE THREAD

**Issue by scriptprojectsdev** [react-native-maps/react-native-maps#4993] opened 2024-03-06 02:56 UTC
### Summary

Currently the pins displayed on the map don't match the typical native pins normally displayed on an iOS app. Since `MKPinAnnotationView` was deprecated, the typical pin used is `MKMarkerAnnotationView`. I know that it's working fine now, but it will have to be updated at some point.

### Reproducible sample code

```TSX
import { StyleSheet, Text, View } from 'react-native';
import MapView, { Marker } from 'react-native-maps'
import * as Location from 'expo-location'
import React from 'react'
import { useState, useEffect, useCallback, useRef } from 'react';

export default function App() {
  const mapView = useRef<MapView | null>(null);
  const markers = [{lat: 29, lng: -95, name: 'test'}]

  return (
    <View style={styles.container}>
      <MapView style={styles.map} ref={mapView}>
        {markers.map((marker, index) => (
          <Marker 
          key={index}
          coordinate={{latitude: marker.lat, longitude: marker.lng}}
          title={marker.name}
          description='This is a test'
          />
        ))}
      </MapView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  map: {
    width: '100%',
    height: '100%'
  }
});
```

### Steps to reproduce

1. Run the code above
2. Zoom out until you can see the pin
3. The pin will be the old style MKPinAnnotationView

### Expected result

The library should be updated to not include the old deprecated class

### Actual result

The library uses the deprecated class MKPinAnnotationView

### React Native Maps Version

1.10.3

### What platforms are you seeing the problem on?

iOS (Apple Maps)

### React Native Version

0.73.4

### What version of Expo are you using?

SDK 48

### Device(s)

iPhone Simulator

### Additional information

Using expo SDK v50.0.8

**Comment by jan-kozinski** [comment] 2024-03-10 13:51
Hi, thanks for letting us know. If you can please add a comment on the https://github.com/react-native-maps/react-native-maps/discussions/4975 discussion then we'll plan accordingly. I'm closing the issue as it's not a bug report

**Closed by jan-kozinski** 2024-03-10 13:51 UTC
Labels: bug
