### ISSUE TITLE
Polygon fill color not working properly 

### ISSUE THREAD

**Issue by NemanjaManot** [react-native-maps/react-native-maps#3057] opened 2019-09-09 13:30 UTC
# Bug

I am using Google Maps on iOS and I have Polygons. Before update (_to version 0.18.3. - at the moment I am not able to update to latest version_) everything works properly, but from now fill color gets weird results.
**Sometimes color is ok, sometimes it is not proper**, no rules.
On android everything works well.

## Environment info

React native info output:

```bash
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
      Android SDK:
        API Levels: 26, 28, 29
        Build Tools: 28.0.3, 29.0.1
        System Images: android-28 | Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.9.0 => 16.9.0 
      react-native: 0.59.10 => 0.59.10 
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

Library version: 0.18.3

## Steps To Reproduce

`1. react-native run-ios`
...

Describe what you expected to happen:

1. Polygon with proper color

## Reproducible sample code

```
export const Polygon = (props) => {
    return (
        <MapView.Polygon
            coordinates={ props.selectedAreas }
            fillColor={ props.fillColor }
            strokeColor={ props.strokeColor }
        />
    )
};

```

**Comment by wamry** [comment] 2019-09-11 13:48
i just tried circle, it has the same issue

**Comment by tomasswood** [comment] 2019-09-24 00:40
I had the same issue using **rgba**. Converting to HEX with Alpha worked. Eg `#3F51B570`

**Comment by kyoyadmoon** [comment] 2019-10-02 07:49
I have the same issue when using Circle component after upgrade react-native-maps to 0.25
I downgrade react-native-maps version to 0.24.2 and it works fine.

**Comment by Tautotes** [comment] 2019-10-02 15:37
Same issue here

**Comment by elicleveland12** [comment] 2019-10-03 18:14
I'm having the same issue. All of my polygons are rendering as a translucent blue color on iOS, but the fill and stroke colors are being received correctly on Android. I'm unable to revert to older versions of react-native-maps (lower than v0.25.0) while using Expo SDK v35.0.0. This issue persists in v0.26.1.

**Comment by NemanjaManot** [comment] 2019-10-14 06:40
Any news?

**Comment by rmnotes** [comment] 2019-10-15 10:28
Here the polygons were rendered on the *second* render with blue/purple fill. Initial render was always using the provided fillcolor. It only happened on iOS, but probably not the older iOS version.

We "resolved" it, by using the 2.5.0 pods with version 0.26.1. So far, there are no problems. (Android works fine without any adjustments.)

To make the patch persisintent we added a postinstall script to npm to copy the following file to `./node_modules/react-native-maps/react-native-google-maps.podspec`:

```ruby
require 'json'

package = JSON.parse(File.read(File.join(__dir__, 'package.json')))

Pod::Spec.new do |s|
  s.name         = "react-native-google-maps"
  s.version      = package['version']
  s.summary      = "React Native Mapview component for iOS + Android"

  s.authors      = { "intelligibabble" => "leland.m.richardson@gmail.com" }
  s.homepage     = "https://github.com/react-native-community/react-native-maps#readme"
  s.license      = "MIT"
  s.platform     = :ios, "8.0"

  s.source       = { :git => "https://github.com/react-native-community/react-native-maps.git" }
  s.source_files  = "lib/ios/AirGoogleMaps/**/*.{h,m}"
  s.compiler_flags = '-DHAVE_GOOGLE_MAPS=1', '-DHAVE_GOOGLE_MAPS_UTILS=1', '-fno-modules'

  s.dependency 'React'
  s.dependency 'GoogleMaps', '2.5.0'
  s.dependency 'Google-Maps-iOS-Utils', '2.1.0'
end
```

**Comment by rborn** [comment] 2019-10-15 11:10
@rmnotes looks like the latest version of GoogleMaps is 3.5.0. Could you test your patch with that one and of it works maybe open a PR ?

Thnx

**Comment by rmnotes** [comment] 2019-10-15 13:08
@rborn I have just tested it with GoogleMaps 3.5.0, but this reintroduced the bug.
Before we went backwards and tested with the versions we found in the commits. 3.2.0, 3.1.0 and 3.0.3 did not work, but 2.5.0 did.

According to the [changelog](https://developers.google.com/maps/documentation/ios-sdk/releases#version_300_-_january_2019), the bug was introduced/documented with 3.0.0. I did not find any indication that it is resolved yet. Nor did I find it in the [issue tracker](https://issuetracker.google.com/issues?q=componentid:188833) to verify its status. Maybe it is related to that [issue](https://issuetracker.google.com/issues/130331383).

Now after reading through the changelog we tested 2.7.0 and this works fine so far. So we will keep  that for the time beeing. 

I am not sure if that should be patched by just reverting the version number back to 2.7.0. There are probably some valid use cases that do not need correctly rendered polygons but depend on some features of version 3.

**Comment by rborn** [comment] 2019-10-15 13:20
@rmnotes Thanks a lot for this, let's keep the issue open till we find a permanent fix 😍

**Comment by Tautotes** [comment] 2019-10-15 13:23
Yes it’s a super annoying problem for us since we need GoogleMaps 3+ to have geolocation services working right in our app and we can’t go backward. Hope a fix will come out sooner than later

**Comment by rmnotes** [comment] 2019-10-15 14:32
> Yes it’s a super annoying problem for us since we need GoogleMaps 3+ to have geolocation services working right in our app and we can’t go backward. Hope a fix will come out sooner than later

@Tautotes We need geolocation as well, but are doing directly via the Places API at https://maps.googleapis.com/maps/api/place/details/json? with a dedicated Maps API key.

**Comment by mbrehme** [comment] 2019-10-21 10:22
Having the same issues with circles and fillColor

**Comment by rmnotes** [comment] 2019-10-25 09:58
The workaround https://github.com/react-native-community/react-native-maps/issues/3025#issuecomment-538345230 appears to work in all versions of GoogleMaps 3.+ as long the wrapper component sets a property with a non null value on any visible element. I  have updated the demo code to toggle the wrapper with a single button. 

It seams like that we should not wait for an update of the GoogelMaps pod, but that there is a tiny bug in the iOS code here. Any ideas where to start investigating?

**Comment by ezranbayantemur** [comment] 2019-12-16 14:53
Same problem..

**Comment by itsam** [comment] 2020-01-13 12:31
Same problem for iOS also with GeoJSON (that uses Polygon actually...)

**Comment by kerembalcan** [comment] 2020-01-16 12:17
> Same problem for iOS also with GeoJSON (that uses Polygon actually...)

Here you can find my workaround explained. https://github.com/react-native-community/react-native-maps/issues/2867#issuecomment-573739457

**Comment by itsam** [comment] 2020-01-20 15:32
@kerembalcan Thanks, that seems to work! Not sure why the timeout is necessary though...

**Comment by computerjazz** [comment] 2020-02-11 01:39
I wasn't satisfied with the workaround as it still introduces a flash of default blue before the polygon updates, so I did some experimenting and found some leads. Maybe someone with more iOS experience than I have can chime in, but it's looking like something in the realm of an async/threading race condition to me.

First, the temporary fix: insert a short delay before the polygon gets added to the map here:  https://github.com/react-native-community/react-native-maps/blob/master/lib/ios/AirGoogleMaps/AIRGoogleMap.m#L135-L136

I changed to:
```objc
    AIRGoogleMapPolygon *polygon = (AIRGoogleMapPolygon*)subview;
      
    // Including a short delay before adding the polygon to the map fixes an issue where
    // the polygon would be default blue colored on initial render.
    // https://github.com/react-native-community/react-native-maps/issues/3057
    double delayInSeconds = 1.0;
    dispatch_time_t popTime = dispatch_time(DISPATCH_TIME_NOW, (int64_t)(delayInSeconds * NSEC_PER_SEC));
    dispatch_after(popTime, dispatch_get_main_queue(), ^(void){
        polygon.polygon.map = self;
        [self.polygons addObject:polygon];
    });
```

I initially tried _only_ a `dispatch_async`, but found that the below code still showed default blue polygons _sometimes_ (most of the time it worked though):
```objc
      dispatch_async(dispatch_get_main_queue(), ^{
        polygon.polygon.map = self;
        [self.polygons addObject:polygon];
      });
```

I'm going to patch-package for now as I don't think this is the _actual_ fix, but I'm hoping some iOS dev out there can identify the underlying issue take it over the finish line.

**Comment by verochan** [comment] 2020-02-21 11:23
I'm experiencing the same problem on the project I'm working on with react-native-maps version 0.26.1 , as a temporal fix I applied this solution: https://github.com/react-native-community/react-native-maps/issues/3025#issuecomment-522968087

Although, on the project, we have one specific case where it's not working 100% perfect (sometimes it shows the correct styles, sometimes it doesn't), but as temporal fix, we can cope with it... 

Does anybody know if this bug related with Google Maps is already being addressed and an official solution will arrive soon? If I'm not mistaken, this is happening since July (v0.25.0) :confused:

**Comment by mtumiati** [comment] 2020-04-17 18:48
I found another workaround:

I saved the CGColorRef taken from fillColor.CGColor in a property of the AIRGoogleMapCircle
```objc
@property (nonatomic, assign) CGColorRef strokeColorRef;
@property (nonatomic, assign) CGColorRef fillColorRef;
```
then I created a new color from the rgba values of that color ref
```objc
- (UIColor *)getColorFromCGColorRef:(CGColorRef) color{
    const CGFloat * components = CGColorGetComponents(color);
    const CGFloat alpha = CGColorGetAlpha(color);
    
    UIColor *newFill = [UIColor colorWithRed: components[0] green: components[1] blue: components[2] alpha: alpha];
    
    return newFill;
}
```
And I called again setFillColor and setStrokeColor before adding the circle to the map
```objc
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wobjc-missing-super-calls"
- (void)insertReactSubview:(id<RCTComponent>)subview atIndex:(NSInteger)atIndex {
  //[...]
  } else if ([subview isKindOfClass:[AIRGoogleMapCircle class]]) {
    AIRGoogleMapCircle *circle = (AIRGoogleMapCircle*)subview;
    circle.circle.map = self;
      
    [circle setFillColor:[self getColorFromCGColorRef:circle.fillColorRef]];
    [circle setStrokeColor:[self getColorFromCGColorRef:circle.strokeColorRef]];
    [self.circles addObject:circle];
  } 
```

It should work also for polygon, I guess.

Seems that the object is added before the color has been passed to the view. That's why the delay added by @computerjazz works most of the time.

**Comment by therealgilles** [comment] 2020-06-21 19:55
I thought I would add screenshots to illustrate the issue:

Polygons filled with blue color:
![Simulator Screen Shot - iPhone 11 - 2020-06-21 at 12 52 38](https://user-images.githubusercontent.com/18076992/85233850-4f129f00-b3be-11ea-8513-ba333520d662.png)

Expected polygons:
![Simulator Screen Shot - iPhone 11 - 2020-06-21 at 12 52 22](https://user-images.githubusercontent.com/18076992/85233851-50dc6280-b3be-11ea-8cba-9e73b50cf3fc.png)

**Comment by therealgilles** [comment] 2020-06-21 20:46
Apparently it is a known Google Maps present since version 3.0.0. From the changelog (https://developers.google.com/maps/documentation/ios-sdk/releases):

Version 3.0.0 - January, 2019
Support for iOS 8.0 has been dropped. The new minimum is iOS 9.0.
Known Issues:

**There is an occasional rendering bug when using the polygon overlay feature.**

**Comment by murilo-campaner** [comment] 2020-07-27 06:16
Any news from this? Im with the same problem.

**Comment by ArturoTorresMartinez** [comment] 2020-08-28 18:01
Same problem here

**Comment by vineethvijayan** [comment] 2020-09-08 18:39
Same here.

**Comment by Eramirez06** [comment] 2020-09-20 19:02
same here

**Comment by GuillaumeMunsch** [comment] 2020-09-25 11:00
Same here

**Comment by oscarcornejo** [comment] 2020-10-07 17:44
Same here!🙄

**Comment by GuillaumeMunsch** [comment] 2020-10-08 08:49
This actually worked for me on iOS

**Comment by therealgilles** [comment] 2020-12-07 21:58
Adding comment to keep this issue alive, unless someone can tell it's fixed.

**Comment by PedroViniciusMelo** [comment] 2020-12-17 15:28
Any news?

**Comment by ddarren** [comment] 2020-12-17 22:10
I opened a #3658 to correct the issue in GeoJson specifically where the stroke color, stroke width, fill color, and marker color properties were not getting preserved. Alternatively, here's a [patch](https://gist.github.com/ddarren/2f2989bf9035308d88cd15d81f8a6d9d) for 0.27.1

**Comment by therealgilles** [comment] 2020-12-18 20:19
Hi @ddarren, do you what's changed that broke this functionality?

**Comment by ddarren** [comment] 2020-12-18 21:23
@therealgilles I'm not sure if this was ever implemented, or if it was, it was removed at some point. I had to add the code to read the specific properties (stroke width, fill color, etc.) from the GeoJson. The code changes in my pull request look more like an enhancement than a bug fix.

**Comment by fattomhk** [comment] 2020-12-21 08:05
@therealgilles But i am okay with filling colors with this code:
 https://github.com/react-native-maps/react-native-maps/pull/3499

```
    "react-native-maps": "^0.27.1",
```
Google map 3.5

**Comment by heysoftwaredave** [comment] 2021-02-13 18:22
Same issue still happening. 
![Screen Shot 2021-02-13 at 10 22 02 AM](https://user-images.githubusercontent.com/13468931/107857757-52431b00-6de5-11eb-824f-3bd2bf1a6629.png)

**Comment by wdhilliard** [comment] 2021-02-23 23:12
I continue to have this same issue with Polygons and Circles. Props work half the time. Using v0.28.0, which includes changes from @ddarren  , the problem still persists. The "workarounds" using setNativeProps, while ultimately displaying the correct color are not a fix as the correct props are not applied on first render. This results in a flash of the blue styles and then a correction to the styles defined in props

**Comment by fattomhk** [comment] 2021-02-24 06:58
@wdhilliard If any one of you are dealing with the blue fill color on iOS. here is my workaround.

In node_modules/react-native-maps/lib/ios/AirGoogleMaps/AIRGoogleMapPolygon.m, add this after `_polygon = [[AIRGMSPolygon alloc] init];`

```
_polygon.fillColor = [UIColor clearColor];
```

**Comment by wdhilliard** [comment] 2021-03-09 04:36
Setting a default transparent fillColor will prevent unwanted styles from appearing on the screen, but in those instances it will cause the item to not render at all. It looks like these values are not set on initialization properly. Possibly a race condition that hasn't been handled properly

**Comment by fattomhk** [comment] 2021-03-09 06:47
I thought that is not caused by the default fill color.

We will see a polygon in blue if we haven't set the transparent color there. 
If you set the transparent color and  add something on the polygon (for example an onPress function), you can find the polygon exists but the fill color is gone. No idea how this happen.

**Comment by jeremyeaton89** [comment] 2021-06-16 00:01
Only able to get this to work after wrapping `Polygon` and using `setNativeProps` with a 1 second timeout (suggestion from [older issue](https://github.com/react-native-maps/react-native-maps/issues/2867#issuecomment-493856610)). `onLayout` never fired for me...

**Comment by TusharKoul** [comment] 2021-06-18 00:03
we're facing this issue too while using the `<Geojson/>` component! `setNativeProps` wont work for us in that case since we'll have to get the ref for each of the `<Polygon>` components being rendered by the Geojson component.

**Comment by raulgordejev** [comment] 2021-10-11 12:44
I tried upgrading to 0.29.3 and it seems to be fixed without using setNativeProps. Can somebody confirm, since it happened quite randomly for me before?

**Comment by therealgilles** [comment] 2022-02-10 05:50
Anyone has an update on this?

**Comment by aaalsubaie** [comment] 2022-02-10 06:14
we are still having this issue!

**Comment by verochan** [comment] 2022-02-10 08:18
Even with this [patch](https://github.com/react-native-maps/react-native-maps/issues/3025#issuecomment-865725136), sometimes, I'm still experiencing this problem... Waiting for the definitive solution 😐

**Comment by shahin963** [comment] 2022-02-17 13:59
Having the same issue with GoogleMaps 3.5.0

**Comment by raulgordejev** [comment] 2022-02-17 14:06
I'm still having the same issue as well. However I've managed to get it working good enough for now with this [workaround](https://github.com/react-native-maps/react-native-maps/issues/3025#issuecomment-522968087) + using react-native-maps version 0.26.1.

I've noticed that on newer versions than 0.26.1 the workaround doesn't have the same effect.

**Comment by edi** [comment] 2022-03-12 00:22
Any fix for this ... ?

**Comment by therealgilles** [comment] 2022-03-12 04:08
I filled an issue with Google IssueTracker here: https://issuetracker.google.com/issues/218789650

**Comment by therealgilles** [comment] 2022-04-05 05:22
The Google team is asking the following:
```
For us to further check this issue, may we know if you were able to reproduce this problem using the latest version (v6.1.1) of Maps SDK for iOS? If so, could you please provide us a sample project that reproduces the problem?
```

Anyone has tested v6.1.1? Anyone has a sample project they can use to debug?
I haven't and don't have one myself right now.

**Comment by peterkeith2010** [comment] 2022-04-27 20:21
tested with new react-native-maps 0.31.0 and GoogleMaps 6.1.1.
Same issue

**Comment by therealgilles** [comment] 2022-05-02 19:58
I'm following up on Google issue tracker. I suggested they use the react-native-maps bundled example as test case. They put it as priority P4.

Does anyone know if this issue happens with release builds? When I experimented recently, I only observed it on debug builds.

**Comment by andrewjmathers** [comment] 2022-06-18 17:11
Found that since polygon already has an opacity and since onLayout callback prop does not exist in recent versions the most reliable workaround for now is to simply use HEX equivalent of RGBA color. I'm sure there are cases where this workaround doesn't work, but for most it should be ok.

**Comment by therealgilles** [comment] 2022-06-18 22:46
@andrewjmathers Do you mean that this workaround works because it's the same color/opacity but it's a different value (expressed in hex) so it gets updated as it appears different?

**Comment by andrewjmathers** [comment] 2022-06-19 21:21
[therealgilles](https://github.com/therealgilles) actually with some testing it turns out it does not resolve the issue, still occurs to me, although it appears as if it happens a little less often (totally subjective from my observations). Clearly an issue with polygon opacity itself

**Comment by edi** [comment] 2022-06-20 06:23
I wonder how many more years will this take to fix since reproducing it is so easy 😢

**Comment by Simon-TechForm** [comment] 2022-07-20 21:52
I just revisited this issue, as I was hoping that `v1.1.0-beta.6` would've fixed it, but unfortunately nothing changed. I also had another look at our code and I still cannot see any obvious reasons as to why this would be caused by `react-native-maps`, meaning the only possible solution I have is adding one of the workarounds mentioned, to the lib, which isn't a viable solution.

I believe the thing we need to move forward is a native reproduction of the issue. I wouldn't count on Google to put much effort into an issue concerning a third party library which is build on top of a cross platform framework that they don't support, and I can't blame them.

If anyone is up for the task, my assumption is that this is caused by adding a circle/polygon to the map too early in its lifecycle, at least before the map received its frame. To mimic how react-native-maps works, it's important to init the mapView with a zero frame.

**Comment by therealgilles** [comment] 2022-07-21 04:35
@Simon-TechForm Does it happen on production build for you or just on development builds?

**Comment by Simon-TechForm** [comment] 2022-07-22 10:58
@therealgilles I've only tested it in debug builds. Are you only experiencing it in debug builds?

**Comment by Simon-TechForm** [comment] 2022-08-12 21:20
As you might have guessed from the comment above, I decided to work around the quirks of the Google SDK and implement a fix directly in `react-native-maps`. Could you please try out the beta version and report back to me if it fixes the issue?

**Closed** 2022-08-22 15:04 UTC
Labels: Google Maps, released on @beta
