### ISSUE TITLE
Application crashes on Android device when image property of marker is used

### ISSUE THREAD

**Issue by Kolyunya** [react-native-maps/react-native-maps#3664] opened 2020-12-23 16:56 UTC
# Bug report (related to #3158, #3637)

## Summary
Application crashes on Android device when using image property of markers with the following error
> Error while updating property 'image' of a view managed by:  AIRMapMarker

## Environment info
```bash
react-native: 0.63.2
react: 17.0.1
react-native-maps: 0.27.1
```

```bash
System:
    OS: Linux 5.9 Arch Linux
    CPU: (4) x64 Intel(R) Core(TM) i7-3517U CPU @ 1.90GHz
    Memory: 1.32 GB / 5.69 GB
    Shell: 5.1.0 - /bin/bash
  Binaries:
    Node: 15.4.0 - /usr/bin/node
    Yarn: 1.22.10 - /usr/bin/yarn
    npm: 6.14.8 - /usr/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 1.8.0_265 - /usr/bin/javac
    Python: 3.9.0 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^17.0.0 => 17.0.1 
    react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps to reproduce
1. Add an `image` prop to the marker: 
```
<Marker image = { require('./assets/marker.png') } />
```
2. Application crashes
3. Remove the `image` prop from the marker
4. Application works perfectly

Describe what you expected to happen: application does not crash.

Describe what you actually happens: application crashes.

## Reproducible sample code
Minimal reproducible example application is [here](https://github.com/Kolyunya/react-native-maps-crash-demo).

## Footnotes
I see a couple of possible reasons for this crash. First, I'm not exactly sure whether RN `0.59+` is supported or not? Second, I wasn't able to follow the installation instructions because I'm using Expo which does all the configuration work for me.

Would highly appreciate if someone can confirm or refute the bug or give any advice.

Thanks!

**Comment by SleeplessByte** [comment] 2021-01-09 17:09
I can confirm this happens when upgrading React Native (in this case Expo 37 to 39, which also upgrades react-native).

**Comment by ortigozamatias** [comment] 2021-01-09 19:06
We have performed the same upgrade in Expo and even went until v40. It was crashing until we set the Google Maps API key. After that, it all went smoothly. We weren't using any custom marker.

**Comment by SleeplessByte** [comment] 2021-01-10 11:48
That's an unrelated error. You can use it just fine without custom markers, and it _will_ crash if you do not set the Google Maps key.

**Comment by Kolyunya** [comment] 2021-01-10 12:10
@SleeplessByte but is it possible to set this key when building via the expo CLI on their cloud platform?

**Comment by SleeplessByte** [comment] 2021-01-10 12:13
Yes. It's all in the expo documentation. You set it in app.json, once for iOS and once for Android.

This is unrelated to this bug.

**Comment by Kolyunya** [comment] 2021-01-10 14:57
@SleeplessByte thanks! Gonna give it a try! Haven't examined that part of the documentation yet.

**Comment by Kolyunya** [comment] 2021-01-13 14:51
Seems like the issue is not caused by the API keys.
I've set the keys but the problem still persists in my case.

**Comment by SleeplessByte** [comment] 2021-01-13 15:01
Thanks for confirming :)

**Comment by MrPumpking** [comment] 2021-01-14 13:34
I've also stumbled upon this one. Both icon and image props cause published / built app to crash. Falling back to using Image inside the Marker for now.

**Comment by sflahave** [comment] 2021-01-15 02:35
I'm seeing the same issue. I'm trying to use a custom marker with the `image` prop, like this: 
```
   <MapView
        ref={mapRef}
        initialRegion={initialRegion}
        style={styles.mapStyle}
        showsUserLocation>
       <Marker
            coordinate={coord}
            image={require('../../assets/images/mapMarker_hq.png')}
            style={styles.hqMarker}
            title={user?.organization?.name}
          />
  </MapView>
```

The app is an Expo app with the managed workflow setup. The problem only occurs when I publish the app and then run it on a real device. It works fine on the same device when running locally in DEV mode. 

I captured my log output - hopefully this is helpful: 

```
82  5427  5427 E st.exp.exponen: Invalid ID 0x00000000.
01-14 20:27:05.682  5427  5427 E unknown:ViewManager: Error while updating prop image
01-14 20:27:05.682  5427  5427 E unknown:ViewManager: java.lang.reflect.InvocationTargetException
01-14 20:27:05.682  5427  5427 E unknown:ViewManager: 	at java.lang.reflect.Method.invoke(Native Method)
01-14 20:27:05.682  5427  5427 E unknown:ViewManager: 	at abi40_0_0.com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:4)
01-14 20:27:05.682  5427  5427 E unknown:ViewManager: 	at abi40_0_0.com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:2)
01-14 20:27:05.682  5427  5427 E unknown:ViewManager: 	at abi40_0_0.com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:9)
01-14 20:27:05.682  5427  5427 E unknown:ViewManager: 	at abi40_0_0.com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:3)
01-14 20:27:05.682  5427  5427 E unknown:ViewManager: 	at abi40_0_0.com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:8)
01-14 20:27:05.682  5427  5427 E unknown:ViewManager: 	at abi40_0_0.com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:2)
01-14 20:27:05.682  5427  5427 E unknown:ViewManager: 	at abi40_0_0.com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:9)
01-14 20:27:05.682  5427  5427 E unknown:ViewManager: 	at abi40_0_0.com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:4)
01-14 20:27:05.682  5427  5427 E unknown:ViewManager: 	at abi40_0_0.com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:1)
01-14 20:27:05.682  5427  5427 E unknown:ViewManager: 	at abi40_0_0.com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:7)
01-14 20:27:05.682  5427  5427 E unknown:ViewManager: 	at abi40_0_0.com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:1)
01-14 20:27:05.682  5427  5427 E unknown:ViewManager: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:970)
01-14 20:27:05.682  5427  5427 E unknown:ViewManager: 	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
01-14 20:27:05.682  5427  5427 E unknown:ViewManager: 	at android.view.Choreographer.doFrame(Choreographer.java:727)
01-14 20:27:05.682  5427  5427 E unknown:ViewManager: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
01-14 20:27:05.682  5427  5427 E unknown:ViewManager: 	at android.os.Handler.handleCallback(Handler.java:938)
01-14 20:27:05.682  5427  5427 E unknown:ViewManager: 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-14 20:27:05.682  5427  5427 E unknown:ViewManager: 	at android.os.Looper.loop(Looper.java:223)
01-14 20:27:05.682  5427  5427 E unknown:ViewManager: 	at android.app.ActivityThread.main(ActivityThread.java:7656)
01-14 20:27:05.682  5427  5427 E unknown:ViewManager: 	at java.lang.reflect.Method.invoke(Native Method)
01-14 20:27:05.682  5427  5427 E unknown:ViewManager: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
01-14 20:27:05.682  5427  5427 E unknown:ViewManager: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
01-14 20:27:05.682  5427  5427 E unknown:ViewManager: Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x0
01-14 20:27:05.682  5427  5427 E unknown:ViewManager: 	at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:246)
01-14 20:27:05.682  5427  5427 E unknown:ViewManager: 	at android.content.res.Resources.getDrawableForDensity(Resources.java:982)
01-14 20:27:05.682  5427  5427 E unknown:ViewManager: 	at android.content.res.Resources.getDrawable(Resources.java:922)
01-14 20:27:05.682  5427  5427 E unknown:ViewManager: 	at android.content.res.Resources.getDrawable(Resources.java:897)
01-14 20:27:05.682  5427  5427 E unknown:ViewManager: 	at abi40_0_0.host.exp.exponent.modules.api.components.maps.AirMapMarker.setImage(AirMapMarker.java:17)
01-14 20:27:05.682  5427  5427 E unknown:ViewManager: 	at abi40_0_0.host.exp.exponent.modules.api.components.maps.AirMapMarkerManager.setImage(AirMapMarkerManager.java:1)
01-14 20:27:05.682  5427  5427 E unknown:ViewManager: 	... 23 more
01-14 20:27:05.682  5427  5427 E unknown:DisabledDevSupportManager: Caught exception
01-14 20:27:05.682  5427  5427 E unknown:DisabledDevSupportManager: abi40_0_0.com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'image' of a view managed by: AIRMapMarker
01-14 20:27:05.682  5427  5427 E unknown:DisabledDevSupportManager: 	at abi40_0_0.com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:13)
01-14 20:27:05.682  5427  5427 E unknown:DisabledDevSupportManager: 	at abi40_0_0.com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:2)
01-14 20:27:05.682  5427  5427 E unknown:DisabledDevSupportManager: 	at abi40_0_0.com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:9)
01-14 20:27:05.682  5427  5427 E unknown:DisabledDevSupportManager: 	at abi40_0_0.com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:3)
01-14 20:27:05.682  5427  5427 E unknown:DisabledDevSupportManager: 	at abi40_0_0.com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:8)
01-14 20:27:05.682  5427  5427 E unknown:DisabledDevSupportManager: 	at abi40_0_0.com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:2)
01-14 20:27:05.682  5427  5427 E unknown:DisabledDevSupportManager: 	at abi40_0_0.com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:9)
01-14 20:27:05.682  5427  5427 E unknown:DisabledDevSupportManager: 	at abi40_0_0.com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:4)
01-14 20:27:05.682  5427  5427 E unknown:DisabledDevSupportManager: 	at abi40_0_0.com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:1)
01-14 20:27:05.682  5427  5427 E unknown:DisabledDevSupportManager: 	at abi40_0_0.com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:7)
01-14 20:27:05.682  5427  5427 E unknown:DisabledDevSupportManager: 	at abi40_0_0.com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:1)
01-14 20:27:05.682  5427  5427 E unknown:DisabledDevSupportManager: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:970)
01-14 20:27:05.682  5427  5427 E unknown:DisabledDevSupportManager: 	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
01-14 20:27:05.682  5427  5427 E unknown:DisabledDevSupportManager: 	at android.view.Choreographer.doFrame(Choreographer.java:727)
01-14 20:27:05.682  5427  5427 E unknown:DisabledDevSupportManager: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
01-14 20:27:05.682  5427  5427 E unknown:DisabledDevSupportManager: 	at android.os.Handler.handleCallback(Handler.java:938)
01-14 20:27:05.682  5427  5427 E unknown:DisabledDevSupportManager: 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-14 20:27:05.682  5427  5427 E unknown:DisabledDevSupportManager: 	at android.os.Looper.loop(Looper.java:223)
01-14 20:27:05.682  5427  5427 E unknown:DisabledDevSupportManager: 	at android.app.ActivityThread.main(ActivityThread.java:7656)
01-14 20:27:05.682  5427  5427 E unknown:DisabledDevSupportManager: 	at java.lang.reflect.Method.invoke(Native Method)
01-14 20:27:05.682  5427  5427 E unknown:DisabledDevSupportManager: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
01-14 20:27:05.682  5427  5427 E unknown:DisabledDevSupportManager: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
01-14 20:27:05.682  5427  5427 E unknown:DisabledDevSupportManager: Caused by: java.lang.reflect.InvocationTargetException
01-14 20:27:05.682  5427  5427 E unknown:DisabledDevSupportManager: 	at java.lang.reflect.Method.invoke(Native Method)
01-14 20:27:05.682  5427  5427 E unknown:DisabledDevSupportManager: 	at abi40_0_0.com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:4)
01-14 20:27:05.682  5427  5427 E unknown:DisabledDevSupportManager: 	... 21 more
01-14 20:27:05.682  5427  5427 E unknown:DisabledDevSupportManager: Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x0
01-14 20:27:05.682  5427  5427 E unknown:DisabledDevSupportManager: 	at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:246)
01-14 20:27:05.682  5427  5427 E unknown:DisabledDevSupportManager: 	at android.content.res.Resources.getDrawableForDensity(Resources.java:982)
01-14 20:27:05.682  5427  5427 E unknown:DisabledDevSupportManager: 	at android.content.res.Resources.getDrawable(Resources.java:922)
01-14 20:27:05.682  5427  5427 E unknown:DisabledDevSupportManager: 	at android.content.res.Resources.getDrawable(Resources.java:897)
01-14 20:27:05.682  5427  5427 E unknown:DisabledDevSupportManager: 	at abi40_0_0.host.exp.exponent.modules.api.components.maps.AirMapMarker.setImage(AirMapMarker.java:17)
01-14 20:27:05.682  5427  5427 E unknown:DisabledDevSupportManager: 	at abi40_0_0.host.exp.exponent.modules.api.components.maps.AirMapMarkerManager.setImage(AirMapMarkerManager.java:1)
01-14 20:27:05.682  5427  5427 E unknown:DisabledDevSupportManager: 	... 23 more
01-14 20:27:05.695  5427  5427 D SoLoader: init exiting
```

**Comment by nathanvogel** [comment] 2021-01-18 15:22
I'm seeing the same issue inside published apps on Android, so I'm also using a native nested <Image/> component.

**Comment by cameronmurphy** [comment] 2021-01-21 02:56
I see this but only when launching builds via Expo Client from https://exp.host
![image](https://user-images.githubusercontent.com/1300032/105263932-9a0ac400-5be4-11eb-982c-c621a982f5ca.png)

Local dev and published builds seem to be fine.

**Comment by hussainahmad** [comment] 2021-02-12 05:15
@sflahave Could you provide a reproducible demo example code.

**Comment by tameroski** [comment] 2021-02-24 15:38
Same issue here. As @MrPumpking said, using a native nested component is the only workaround for the moment : 
```
<MapView
     style={styles.map}
     customMapStyle={mapTheme}
     region={region}
     initialRegion={initialRegion}
>
    <Marker coordinate={coords} }}>
       <Image source={require('../../assets/images/marker.png')}/>
    </Marker>
</MapView>
```

**Comment by Kolyunya** [comment] 2021-02-27 16:00
@hussainahmad the minimal reproducible demo code is [here](https://github.com/Kolyunya/react-native-maps-crash-demo).

**Comment by philipp-spark** [comment] 2021-03-07 10:29
The same happen with icon props 

[`log image props`](https://gist.github.com/philipp-spark/c4e8650eb71c55ea343be0acd77741ff)
[`log icon props`](https://gist.github.com/philipp-spark/4552848a2a519d3bc2d0fb9d348551e7)

**Comment by clarios6** [comment] 2021-03-18 05:21
I ran into this issue and commented about it on #2997 
I had tried the same solution as @tameroski and it worked but ultimately I ended up changing it.
My workaround involved using a base64 encoded image kind of like this:
```
<Marker
    image={'data:image/png;base64, ...'}
>
</Marker>
```
It runs just as fast as it does if you use the image prop in development, but I haven't been able to test it on iOS.

**Comment by CostinBiserica** [comment] 2021-03-23 13:08
As of 23.03.2021, the behaviour it's still present. The workaround it's using the <Image></Image> and not the image/icon prop of the marker.

**Comment by CaNafo** [comment] 2021-04-02 12:05
> As of 23.03.2021, the behaviour it's still present. The workaround it's using the `<Image></Image>` and not the image/icon prop of the marker.

This solution is working just fine.
Inside the `<Marker></Marker> `tag insert `<Image source={YourImage}/>` tag with image of the marker.

**Comment by nmpribeiro** [comment] 2021-06-30 12:58
I can confirm I also see this problem. However, in my case, if I use the `<Image />` tag I have huge performance issues in android. I will try to workaround by using the base64 option as mentioned by @clarios6 .

**Comment by cameronmurphy** [comment] 2021-07-05 07:31
The issue seems to be resolved in 0.28.0 🥳

**Comment by RyanTG** [comment] 2021-08-13 05:34
Perhaps for you?

I tried the base64 method (both as Image and ImageBackground, since I need my markers to have a Text component within). Still very slow on Android. ImageBackground was exceptionally slow.

**Comment by SleeplessByte** [comment] 2022-05-31 22:10
It's not stale.

**Comment by Simon-TechForm** [comment] 2022-07-22 20:54
I wanted to revisit this issue, but I'm struggling to reproduce the error. Can someone experiencing this provide the minimal steps to reproduce anno expo 45? I normally don't use expo, so please be explicit :)

**Comment by Kolyunya** [comment] 2022-07-23 09:43
@Simon-TechForm I made a [minimal reproducible example](https://github.com/Kolyunya/react-native-maps-crash-demo) some time ago. Probably worth updating dependencies versions.

**Comment by Simon-TechForm** [comment] 2022-07-23 21:40
@Kolyunya I tried your example as well, without any issues. But it seems like this is only happening in production builds, am I correct? If so, how are you doing the production builds that causes the error? As I said, I'm not an expo user, so I'm not accustomed to the workflows etc. I tried `expo start --no-dev --minify` which seemed to work as well :)

**Comment by Simon-TechForm** [comment] 2022-08-11 20:27
I'm closing for now. If anyone is still experiencing this, please comment with an up to date reproducible example and I'll be happy to re-open :)

**Closed by Simon-TechForm** 2022-08-11 20:27 UTC
Labels: bug, help wanted

**Comment by SleeplessByte** [comment] 2022-08-11 23:38
@Simon-TechForm you can make a build by running `expo build` and picking android apk.

**Comment by cynde** [comment] 2024-07-28 06:28
hi i'm still getting this issue. using <Image> inside <Marker></Marker> will have performance issue since i load so many markers. anybody can help?
