### ISSUE TITLE
Android random crash - marker/polyline related?

### ISSUE THREAD

**Issue by D10S60948** [react-native-maps/react-native-maps#4065] opened 2022-01-12 19:17 UTC
# Bug report

## Environment info
```bash
    "react": "17.0.2",
    "react-native": "0.66.4",
    "react-native-maps": "^0.30.1",
```

## Summary + Steps to reproduce
It happens randomly, caught with Sentry. It can happen even after few minutes of use of the app.
Didn't manage to recognize any pattern which causes it ☹️ but.. I think it happens more often when returning from background or navigating between screens (might be false assumption and hence deceiving so please don't take it as a fact). 
Reproduced by mistake so caught the logs 👇🏼

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
01-14 17:57:26.051 16109 16785 E AndroidRuntime: FATAL EXCEPTION: androidmapsapi-Snapshot
01-14 17:57:26.051 16109 16785 E AndroidRuntime: Process: com.xxx.xxx.xxx, PID: 16109
01-14 17:57:26.051 16109 16785 E AndroidRuntime: java.lang.IllegalArgumentException: width and height must be > 0
01-14 17:57:26.051 16109 16785 E AndroidRuntime: 	at android.graphics.Bitmap.createBitmap(Bitmap.java:1113)
01-14 17:57:26.051 16109 16785 E AndroidRuntime: 	at android.graphics.Bitmap.createBitmap(Bitmap.java:1080)
01-14 17:57:26.051 16109 16785 E AndroidRuntime: 	at android.graphics.Bitmap.createBitmap(Bitmap.java:1030)
01-14 17:57:26.051 16109 16785 E AndroidRuntime: 	at android.graphics.Bitmap.createBitmap(Bitmap.java:991)
01-14 17:57:26.051 16109 16785 E AndroidRuntime: 	at com.google.maps.api.android.lib6.impl.a.d(:com.google.android.gms.dynamite_mapsdynamite@214815088@21.48.15 (150800-0):2)
01-14 17:57:26.051 16109 16785 E AndroidRuntime: 	at com.google.maps.api.android.lib6.impl.bl.run(:com.google.android.gms.dynamite_mapsdynamite@214815088@21.48.15 (150800-0):1)
01-14 17:57:26.051 16109 16785 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:923)
```
</details>

**Comment by Simon-TechForm** [comment] 2022-03-14 23:18
Hello @D10S60948. Have you managed to reproduce this? It's extremely difficult to assist you without a sample code reproducing the issue.

**Comment by D10S60948** [comment] 2022-03-15 06:34
Hi, it happened all the time but hard to intentionally reproduce as nothing in particular triggered it.
I managed to get rid of it once I downgraded react-native from 0.66.4 to 0.65.3 and react-native-reanimated from 2.3.1 to 2.2.3 (Is suspect that `react-native-reanimated` was the trigger and that a threads race condition on the Java side caused it. but it's just an assumption).
I Added some logcat logs that will hopefully assist a bit.

**Comment by Simon-TechForm** [comment] 2022-03-15 08:12
I see. Since you found out that it's likely caused by react-native-reanimated and it doesn't seem like anyone else is experiencing it, I hope you don't mind me closing it? :)

If you experience it again and manages to reproduce it, please feel free to open a new issue :)

**Closed by Simon-TechForm** 2022-03-15 08:12 UTC
Labels: bug
