### ISSUE TITLE
Traffic rendering issue on Android

### ISSUE THREAD

**Issue by TucaMariusOctavian** [react-native-maps/react-native-maps#4231] opened 2022-05-09 13:52 UTC
# Bug report

## Summary

Traffic glitches appear on Google Map on Android when traffic is on. This happens when zoom is around 6.5 especially around Paris, Nederlands or Belgium (a lot of roads).

![image](https://user-images.githubusercontent.com/17797197/167418977-ac4694cf-6d81-4b75-ada6-6f99b2d7dff4.png)
![image](https://user-images.githubusercontent.com/17797197/167419233-7116b092-bd3f-4770-943e-6fcdb8f4fb58.png)

## Environment info

Android emulator API 30: Pixel 3,4, Nexus 5
Devices: Huawei P Android 9, Asus Zenfone 6, Pixel 4

React Native CLI:
"react": "17.0.2",
"react-native": "0.68.1",
"react-native-maps": "^0.31.1"

Expo CLI on both SDK 44 and 45:
"expo": "^45.0.0",
"react": "17.0.2",
"react-native": "0.68.1",
"react-native-maps": "0.30.1",

"expo": "^44.0.0",
"react": "17.0.1",
"react-native": "0.64.3",
"react-native-maps": "0.29.4",

```js
      <MapView
        showsTraffic={true}
        style={{width: '100%', height: '90%'}}
        initialRegion={{
          latitude: 51.743426,
          longitude: 5.553055,
          latitudeDelta: 0.0922,
          longitudeDelta: 0.0421,
        }}
      />
```

**Comment by Simon-TechForm** [comment] 2022-07-09 19:46
hi @TucaMariusOctavian 👋

I'm unable to reproduce the issue with the code you provided on the latest version of react-native-maps. Because of this and the lack of traction that this issue have gotten, I hope you are okay with me closing this. If you are still experiencing this on the latest version (`v1.0.0` as of today), please feel free to open a new issue :)

**Closed by Simon-TechForm** 2022-07-09 19:46 UTC
Labels: bug
