### ISSUE TITLE
Empty maps within the Example folder

### ISSUE THREAD

**Issue by alex83130** [react-native-maps/react-native-maps#3867] opened 2021-06-27 21:25 UTC
# Bug report

## Summary

I launched the example project, everything loads correctly, but I get empty maps.
I already tried to change the API key with mine, but it still the same result.

## Environment info
      react-native: 0.63.4
      react: 16.13.1

I'm using the Android Emulator, which so far worked fine for my react-native projects.

`react-native info` output:
```
info Fetching system and libraries information...
(node:39320) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
    Memory: 3.02 GB / 15.82 GB
  Binaries:
    Node: 14.15.4 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.10 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 29, 30
      Build Tools: 28.0.3, 29.0.2
      System Images: android-29 | Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
    Windows SDK:
      AllowAllTrustedApps: Disabled
      Versions: 10.0.17763.0
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6953283
    Visual Studio: Not Found
  Languages:
    Java: 1.8.0_275
    Python: 3.8.2
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: react-native info => 0.63.4
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps to reproduce

1, git clone this repo
2. cd example
3. npm install
4. npx react-native run-android

Describe what you expected to happen:

Start the app and See the maps 

Describe what you actually happens:

Start the app but the maps are empty

![image](https://user-images.githubusercontent.com/15250423/123559854-9c151800-d76c-11eb-918f-79de5d318a93.png)

## Reproducible sample code

The example folder in this repo.

**Comment by christopherdro** [comment] 2021-07-03 14:39
There is an issue with your api key. Duplicate of https://github.com/react-native-maps/react-native-maps/issues/3868 and probably another dozen tickets that have already been closed.

**Closed by christopherdro** 2021-07-03 14:39 UTC
Labels: bug
