### ISSUE TITLE
Map not rendering in IOS. Please resolve this issue ASAP!

### ISSUE THREAD

**Issue by nishantiic** [react-native-maps/react-native-maps#4445] opened 2022-09-17 08:45 UTC
### Summary

This package is working in android but when i was trying to install for ios that show me error like this.
**### _1 - error build: Undefined symbol: _OBJC_CLASS_$_RCTBridge
2 - error build: Undefined symbol: _OBJC_CLASS_$_RCTBundleURLProvider
3 - error build: Undefined symbol: _RCTAppSetupDefaultRootView
4 - error build: Undefined symbol: _RCTAppSetupPrepareApp
Note:- Previously i was getting an error regarding GMSService Not found ,but that was resolved._** 

I have updated the deployment target to "13.0" and made the change as per the instructions but still getting an error not able to build.
The new Version of react-native update the app update the "AppDelegate.m" to "AppDelegate.mm" and the installation says that update "AppDelegate.m". Please check this and let me know to to resolve this error and what's the process for the install if any missing changes are there. 

### Reproducible sample code

```JSX
<MapView
          provider={PROVIDER_GOOGLE}
          style={styles.map}
          mapType="hybrid"
          region={{
          latitude: 37.78825,
          longitude: -122.4324,
          latitudeDelta: 0.0922,
          longitudeDelta: 0.0421,
          }}
          showsCompass={true}
          showsUserLocation={true}
          onRegionChange={event => onChange(event)}
        />
```

### Steps to reproduce

Follow the instruction as per the guidelines with and try to make build. 

### Expected result

i want to show the map on the screen with the current location

### Actual result

Not even building the app for ios.

### React Native Maps Version

1.3.1

### What platforms are you seeing the problem on?

iOS (Google Maps)

### React Native Version

0.69.4

### What version of Expo are you using?

Not using Expo

### Device(s)

iPhone 13pro max

### Additional information

Please provide me the latest installation process for IOS.
Please Update and resolve the issue ASAP!.

**Comment by rob5408** [comment] 2022-09-17 22:52
I see entitled behavior on the internet all the time. I'm not sure why this one made me want to respond. Let's start by removing the exclamation marks and demands for things to be fixed ASAP. None of these maintainers work for you. Even if they did, it's a self-defeating way to approach getting someone to do something for you.

I'm running react-native-maps 1.3.1 with RN 0.69.4 in iOS in the sim and device and it works perfectly. It's not a bug, it's your setup. I even have constructive steps for you to try towards debugging, but I'm not sharing anything unless you change your question to be less demanding.

**Comment by Simon-TechForm** [comment] 2022-09-21 18:30
I guess "ASAP" doesn't include responding to your own issue in 4 days... 😁

I'm just gonna close this.

I honestly aprreciate your comment @rob5408 - it gets extremely tiresome maintaining OSS with issues like these. Thank you 👍

**Closed by Simon-TechForm** 2022-09-21 18:30 UTC
Labels: bug

**Comment by nishantiic** [comment] 2022-10-03 12:50
Hi All,
Apologies for coming across as rude behaviour. My intention was not to hurt anyone. The way i composed the issues was not correct, i've made the changes. 
Thank you all for maintaining this amazing package.

**Comment by Hassanjankhan** [comment] 2023-11-09 06:22
I have the same issue on IOS emulator, after some finding i commenting  **provider={PROVIDER_GOOGLE}** this line of code it is working fine now.
