### ISSUE TITLE
Custom markers slow performance with reproduceble demo

### ISSUE THREAD

**Issue by compojoom** [react-native-maps/react-native-maps#2575] opened 2018-11-08 16:45 UTC
I was experiencing high CPU usage and lags on the map with what I consider a lot of markers - 400. To my surprise however the map was fast with 300 markers. So, it wasn't really making sense. 
After debugging this for several hours I managed to come with a reproducible demo of the issue.

https://github.com/compojoom/react-native-maps/tree/high_cpu

launch the examples and switch to google maps as provider and open the "custom markers" example. 

in xCode one should see
<img width="271" alt="image" src="https://user-images.githubusercontent.com/693770/48213168-7baaac00-e37d-11e8-9199-d12b7c880ace.png">

If you go into
example/examples/CustomMarkers.js
and remove the `dsafasdf` on line 81 and refresh the example you will see that the CPU usage goes to 1-2%
<img width="269" alt="image" src="https://user-images.githubusercontent.com/693770/48213327-d2b08100-e37d-11e8-8c65-735b98720285.png">

if one changes the width of the custom marker to 100 px for example, then we get again CPU usage of 100%

I've tested this currently only on iOS and I'm not sure if the issue apply to Android. 

### Environment
 "react": "16.5.0",
"react-mixin": "^2.0.2",
"react-native": "0.57.1",
react-native-maps: > 0.21.0
Target Platform: eg: iOS - 12.1 Simulator/iPhone 6

### Steps to Reproduce
Use the reproducible demo. The issue is hard to reproduce as one needs a lot of markers and the "correct" styling...

### Expected Behavior
I would expect CPU to go down once the markers are rendered

### Actual Behavior
CPU stays at 100%

### Reproducible Demo
https://github.com/compojoom/react-native-maps/tree/high_cpu

**Comment by rborn** [comment] 2018-11-08 17:49
@compojoom nice research, could you please update the issue to follow the template? 
Thanks

**Comment by compojoom** [comment] 2018-11-08 22:29
updated

**Comment by cklinx** [comment] 2018-11-11 11:15
Try to set `tracksViewChanges={false}` in your markers

**Comment by compojoom** [comment] 2018-11-11 12:36
@cklinx - this bug report has nothing to do with tracksViewChanges. If you look at the example code you'll see that tracksViewChanges is already set to false: https://github.com/compojoom/react-native-maps/blob/d60402e2c62f26f3be91023381bdb0cafc9c8318/example/examples/CustomMarkers.js#L73

**Comment by idumachika** [comment] 2018-11-11 13:00
i have issue styling my map i want to implement border raduis on my map ,if
i add border radius  it does work

**Comment by tomtom94** [comment] 2018-11-13 21:06
I raise the same question ;). What's up with this big issue @react-community

**Comment by AngelVenchev** [comment] 2018-11-14 14:48
I am facing the same issue. What is going on after the markers have been rendered. If I replace the custom markers with the default ones it works really well. However when I replace the markers with ImageBackgroud and Text inside it, with little to no styling it just starts going slowly.

**Comment by tomtom94** [comment] 2018-11-15 22:34
What about putting the inside of the marker in a react class ??

```
      <Marker
        key={`marker-${data.id}`}
        coordinate={data.location}
        size={30}
        tracksViewChanges={false}
      >
        <MarkerIconIcomoon
          color={
            this.state.slideIndex === data.id && this.state.displayCarousel
              ? "#fecb2f"
              : "black"
          }
          backgroundColor="black"
          size={50}
        />
      </Marker>
```

I chose Component instead of PureComponent.
```
class MarkerIconIcomoon extends Component {
  render() {
    return (
      <IconIcomoon
        name="pin-full"
        color={this.props.color}
        backgroundColor={this.props.backgroundColor}
        size={this.props.size}
      />
    );
  }
}
```

It seems slightly faster, but my markers takes so much time than IOS to render, the gap is yet huge.

**Comment by compojoom** [comment] 2018-11-16 04:53
@tomtom94 - In my demo I'm reproducing this with a Text element. In the app, where I have the problem I have a custom component that renders the contents - View, Text, Icon etc. A custom component doesn't help here. I didn't make a custom component in the demo to simplify things.

**Comment by tomtom94** [comment] 2018-11-18 07:58
Hello guys, the slowness issue isn't anymore an issue for me hihi !!!! 

Well it is an easy job, just don't use the props **onRegionChange** 

```
// onRegionChange={currentRegion => {
//   this.onRegionChange(currentRegion);
// }}
```

This is what causes the android google map slowness issue

Instead you can just simply use the props **onRegionChangeComplete**

```
onRegionChangeComplete={currentRegion => {
  this.onRegionChangeComplete(currentRegion);
}}
```

Cheers. !!

**Comment by AngelVenchev** [comment] 2018-11-21 10:34
Hey, I solved my problem and this could help somebody else too. I ended up using the image prop on the marker component to display whatever custom component I need. In my use-case I was implementing clustering using supercluster, I wanted to display a number of clustered pins. I generated my images from here: https://dummyimage.com - about a hundred. Then a designer converted them to circles with a transparent background automatically with a Photoshop action and I loaded them in my application. 100 images were as small as 60kB so it's not a big hit that I have them all in the app.

**Comment by duytq94** [comment] 2019-03-22 10:07
I have the same problem, if you use custom markers, the map will very lag.
This is really a big problem, please help.
Thanks!

**Comment by Balasnest** [comment] 2019-09-09 12:12
@compojoom Did you manage to get it to work? I am also facing the same issue. After using for a while, android maps are slow, lagging. Zoom in/out are very rough too.

**Comment by darran-kelinske-fivestars** [comment] 2019-10-21 20:34
We are noticing significant android performance issues with around 20 custom markers. Has anyone found any solutions/workarounds?

**Comment by mlop113** [comment] 2019-11-25 07:47
> We are noticing significant android performance issues with around 20 custom markers. Has anyone found any solutions/workarounds?

I have same problem, CPU is overload 100%

**Comment by darran-kelinske-fivestars** [comment] 2019-11-25 15:43
Solution: Native development

**Comment by mlop113** [comment] 2019-12-06 04:15
As @compojoom said this bug report has nothing to do with tracksViewChanges, It is already set to false

**Comment by WoodburyShortridge** [comment] 2020-06-19 18:05
Any updates on this issue? I am experiencing the same: cpu spikes with just a handful of custom markers and callouts(text only). 

100% cpu in iOS using the google provider map. Switching to apple maps fixes the performance issue, but is not preferred. 

Tried both tracksViewChanges=false and using onRegionChangeComplete, both did not help with google maps on iOS.

**Comment by elisegriset92** [comment] 2020-08-24 15:08
Hello, has anyone found a solution regarding the custom marker making the app really slow (android only) 
Indeed when I test with the google map marker it's really fast !

**Comment by stanleyness** [comment] 2020-09-16 21:17
Bump! Please fix

**Comment by KeystoneScience** [comment] 2020-10-27 22:41
bump

**Comment by hmust92** [comment] 2020-12-02 19:06
bump

**Comment by valeriik** [comment] 2020-12-17 13:16
My steps:

1. Launch app with PROVIDER_GOOGLE on iOS without any markers etc, just the map.
CPU about **100%**
2. Add 1-5 custom marker(s).
CPU about **65%**
3. Remove all custom markers - everything is fine.
CPU about **2%**

Also:
1. I tried to use **image** prop instead of custom marker - the same result - at start CPU about **100%**, after all custom markers were removed - CPU about **65%**
2. I tried to use **icon** prop - everything is fine, if I do not moving the map - CPU about **2%**

But I **cannot** use **icon** prop because I really need to set different width/height. depends on business logic.

**Comment by valeriik** [comment] 2020-12-24 16:55
As CPU performance is very important bug, I have found only 1 way to avoid it - use **icon** prop instead of image prop or custom marker. 

But here I had to create a set of different png files (1x/2x/3x copies of them) to cover all my needs (of course using custom marker would simplify my work 10 times but it'll veery increase CPU performance...)

So, for me it was very important to know marker height, and I did not find any info how to know which [@2x/@3x](https://reactnative.dev/docs/images#static-image-resources) suffixes app uses, therefore I created next code:

```
  import { PixelRatio } from 'react-native'
  ...
  const getMarkerImgInfo = () => {
    const pr = PixelRatio.get()
    if (pr >= 3) 
      return { img: require('@/assets/markers/map-marker-3x.png'), height: 150 / pr} // @3...
    else if (pr >= 1.5 && pr < 3) 
      return { img: require('@/assets/markers/map-marker-2x.png'), height: 100 / pr} // 1.5...2.99 @2
    else 
      return { img: require('@/assets/markers/map-marker-1x.png'), height: 50 / pr} // < 1.49 @1
  }
  ...
  console.log("Marker height:", getMarkerImgInfo().height);
  ...
  <MapView
  ...
  >
    <Marker
      ...
      icon={getMarkerImgInfo().img}
    />
  </MapView>
```
where 50, 100 and 150 is the original size of png files in pixels.
So this way marker will be approximately the same size for all devices with different dpi/resolution and react-native-maps will work with normal CPU performance on iOS/Android.

I added only 3 png's but you can add more files. For example if height of x1 png is 50px, for PixelRatio.get() === 0.75 you can create map-marker-075x.png with height 50*0.75=~37px etc, to better match file size to screen dpi size.

**Comment by philipp-spark** [comment] 2021-03-07 11:08
problem is icon/image prop cant be used due to this issue .... #3664

**Comment by RamonAcedoM** [comment] 2021-07-09 05:41
Any news on this?

**Comment by smccamley** [comment] 2021-08-06 20:32
I'm also having this issue

**Comment by RyanTG** [comment] 2021-08-12 17:08
To add another use case to this: in addition to custom Image and Icon markers resulting in very slow performance on Android, styling the markers using a View also results in slow performance.

For example:
````
        <View style={{
            width: dotWidthHeight,
            height: dotWidthHeight,
            borderRadius: dotWidthHeight / 2,
            borderWidth: 2,
            borderColor: 'white',
            backgroundColor: 'red'
        }}>
        </View>
````

Works great on iOS. We opted for a styled View because it's easy and flexible (for dynamically resizing) and _feels_ lightweight.

**Comment by valeriik** [comment] 2021-12-11 15:32
guys, any news here?

**Comment by JurgenFiGO** [comment] 2022-03-15 10:42
Still experiencing extreme performance degradation on Android when using custom markers when not setting trackViewChanges to false. Any update on a potential fix or workaround?

**Comment by salah-ghanim** [comment] 2022-04-15 11:02
with the new architecture of react-native we can get much better performance and get closer to native performance by avoiding serializing map data (markers).

hopefully with RN supporting typescript for Turbo Modules we can start working on that

#4156

**Comment by BrodaNoel** [comment] 2022-07-08 01:51
Yes @stale... This is still a thing.

So, seems like the new Arch will fix (or get it better). Discussion in https://github.com/react-native-maps/react-native-maps/discussions/4301

I'll be waiting for this on Expo!
Thanks for the hard work people!

**Comment by Simon-TechForm** [comment] 2022-07-22 21:35
Lets try and get to the bottom of this. This issue is almost 4 years old at this point, and naturally picked up quite a few comments on the way. Because of this, I will focus on the case put forth by the author, and everything else will have to be tracked down in seperate issues - if not I won't be able to keep track of things.

So the issue to focus on here is abnormally high cpu usage with Google Maps on iOS, using custom markers with `tracksViewChanges` set to false. If anyone is able to reproduce this issue on `v1.1.0`, please report back with a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by Simon-TechForm** [comment] 2022-08-11 20:27
I'm closing for now. If anyone is still experiencing this, please comment with an up to date reproducible example and I'll be happy to re-open :)

**Closed by Simon-TechForm** 2022-08-11 20:27 UTC
Labels: enhancement, help wanted, performance, Google Maps, waiting on dependency
