### ISSUE TITLE
How to solve  {isGesture: boolean} for Apple Map

### ISSUE THREAD

**Issue by marksturm** [react-native-maps/react-native-maps#3979] opened 2021-10-13 15:08 UTC
Anyone an idea how to make a equal-function to {isGesture: boolean} for apple maps?
I need to differentiate, if the user do a gesture or the movement comes from an animation, like animateToRegion.

**Comment by Simon-TechForm** [comment] 2021-10-15 06:26
Duplicate of #3952

**Closed as completed** 2021-10-17 18:07 UTC
