### ISSUE TITLE
Android crash with new rendered enabled

### ISSUE THREAD

**Issue by danilofatcat** [react-native-maps/react-native-maps#4317] opened 2022-07-12 09:41 UTC
### Summary

On android, when using a new render engine app crashes after a few minutes of a map being loaded.

This is a native error I caught:

<img width="407" alt="Screenshot 2022-07-12 at 11 35 17" src="https://user-images.githubusercontent.com/82648829/178460008-c0ed93b8-6989-450f-9b8c-6d5f03d99da8.png">

### Reproducible sample code

```TSX
import React from 'react';
import {StyleSheet} from 'react-native';
import MapView, {enableLatestRenderer} from 'react-native-maps';
enableLatestRenderer()

export default function App() {
          return (
            <MapView
              style={styles.mapView}
              initialRegion={{
                latitude: 42,
                longitude: 30,
                latitudeDelta: 1,
                longitudeDelta: 1,
              }}
            />
        );
}

const styles = StyleSheet.create({
   mapView: {
            flex: 1,
   },
});
```

### Steps to reproduce

Enable latest renderer on android
Load google map with react-native-maps
After few minutes application crashes

### Expected result

App should continue working fine even after few minutes of using maps

### Actual result

Application crashes. See screenshot with error above.

### React Native Maps Version

1.0.0

### What platforms are you seeing the problem on?

Android

### React Native Version

0.67.3

### What version of Expo are you using?

Not using Expo

### Device(s)

Samsung Galaxy a52

### Additional information

This is happening on release version of the app. 
Also, I have markers loaded as SVG images on the map.

**Comment by Simon-TechForm** [comment] 2022-07-12 22:07
Even though the error message isn't the same, I believe that this is caused by the same underlying problem mentioned in #4161, so leaving a reference and closing this for now.

**Closed by Simon-TechForm** 2022-07-12 22:07 UTC
Labels: bug
