### ISSUE TITLE
onRegionChangeComplete on MapView doesn not have {isGesture} on v0.27.1

### ISSUE THREAD

**Issue by Infinitism** [react-native-maps/react-native-maps#3631] opened 2020-11-24 01:21 UTC
# Bug report

onRegionChangeComplete on MapView doesn not have {isGesture}

## Summary

On version 0.27.1 does not have the {isGesture} property in the downloaded package but lists it in the MapView documentation.

## Environment info

react-native-maps: 0.27.1

**Comment by Ahmdrza** [comment] 2020-12-05 06:22
Hi, any idea when this will be available in the latest version?

**Comment by KyleAsaff** [comment] 2021-01-16 18:44
doesn't work for me either even when `provider={PROVIDER_GOOGLE}`. I need to detect when a user pans by dragging. any work arounds or ETA on a fix?

**Comment by anaumov-work** [comment] 2021-01-19 10:09
@Ahmdrza @KyleAsaff @Infinitism   You can use my workaround - onPanDrag event with a flag variable to detect gestures

**Comment by KyleAsaff** [comment] 2021-01-31 21:40
> @Ahmdrza @KyleAsaff @Infinitism You can use my workaround - onPanDrag event with a flag variable to detect gestures

I tried to `useState` to set a flag for `onPanDrag` to determine if it's a pan action in `onRegionChangeComplete` then setting it false after `onRegionChangeComplete` completes. it's unreliable - sometimes a `onPanDrag` will trigger an extra time after `onRegionChangeComplete` triggers.

**Comment by krtejeda** [comment] 2021-03-07 01:41
Not a bug. isGesture is available in the latest branch and can be used if you use 0.28.0. Only thing missing is the type definitions which will be addressed by #3677 .

**Closed** 2021-03-16 00:55 UTC
Labels: bug

**Comment by iners-max** [comment] 2021-05-04 11:40
I have put 0.28.0 in my package.json (and verified in package-lock.json) but the second parameter is undefined

**Comment by dazulu** [comment] 2021-05-10 09:32
> I have put 0.28.0 in my package.json (and verified in package-lock.json) but the second parameter is undefined

I am also getting back`undefined` for `isGesture` on 0.28.0 (context is onRegionChangeComplete)

![Screenshot 2021-05-10 at 11 30 48](https://user-images.githubusercontent.com/4543447/117638498-2c7aa780-b183-11eb-9e1e-00b4ec49aa9d.png)

**Comment by rxng8** [comment] 2021-05-27 04:17
it is still unusable in 0.28.0.

**Comment by vietnt-uet** [comment] 2021-06-01 04:12
@christopherdro This is still reproduced on the latest version.

**Comment by tomgreener** [comment] 2021-06-01 09:43
Also experiencing this issue in 0.28.0

**Comment by Seypopi** [comment] 2021-06-14 13:51
I am on 0.28.0. and it is still impossible to use `{isGesture}`

**Comment by karuzo17** [comment] 2022-04-02 20:45
Issue is for me present as well on Android with v0.28.1

**Comment by mp3por** [comment] 2022-09-09 08:16
Same for me as well with version 1.2.0
