### ISSUE TITLE
react native maps polyline is showing but it's not normall

### ISSUE THREAD

**Issue by samyarkd** [react-native-maps/react-native-maps#3963] opened 2021-09-22 08:23 UTC
# Bug report

## Summary
I want to draw a Polyline on the map, Polyline is showing, but it's not the Polyline I expected, even I tried to pass the coordinates manually, but it's still drawing from the {lat: 0.0, long: 0.0} to right or left
it's not a normal Polyline 

## Environment info

`react-native info` output:

```bash
expo: ~42.0.1
expo-location: "~12.1.2",
react: "16.13.1",
react-dom: "16.13.1",
react-native-maps: "0.28.0",
react-native: 0.63.2
```

## Steps to reproduce

1. initialize myProject
2. installing react-native-maps
3. expo start

 **What I expected to happen:**
a Polyline route from Point 1 to Point 2

Point 1 is my location and Point 2 is where I tap on the map

**What actually happens when i tap on map to draw polyline :**
![image](https://i.stack.imgur.com/Tjn3a.jpg)
![image](https://user-images.githubusercontent.com/75088294/134306647-5b6899d4-99d7-4dcc-a9bd-a3b8f481e347.png)

## Code
```JavaScript

import React, { useEffect, useState } from 'react'
import { Dimensions, StyleSheet, Text, View } from 'react-native'
import MapView, { Marker, Polyline } from 'react-native-maps'
import * as Location from 'expo-location';
import axios from 'axios';
import { decode } from "@googlemaps/polyline-codec";

const App = () => {
  const [location, setLocation] = useState(null);
  const [dectnation, setDectnation] = useState(null)
  const [polyline, setPolyline] = useState(null)
  const [dcodedPolyline, setDcodedPolyline] = useState(null)


  useEffect(() => {
    (async () => {
      let { status } = await Location.requestForegroundPermissionsAsync();
      if (status !== 'granted') {
        console.log('Permission to access location was denied');
        return;
      }
    })();
  }, []);

  useEffect(() => {
    if (dectnation !== null && location !== null) {
      const urls = `https://router.hereapi.com/v8/routes?transportMode=car&origin=${location?.latitude},${location?.longitude}&destination=${dectnation?.latitude},${dectnation?.longitude}&return=polyline`
      console.log(urls)
      var config = {
        method: 'get',
        url: urls,
        headers: {
          'Authorization': 'Bearer [TOKEN]'
        }
      };

      axios(config)
        .then(function (response) {
          (response.data.routes.length > 0 ? response.data.routes.map(resp => resp.sections.map(ix => setPolyline(ix.polyline))) : null);
        })
        .catch(function (error) {
          console.log(error);
        });

    }


  }, [dectnation]);

  useEffect(() => {
    if (polyline === null) {
      null
    } else {
      setDcodedPolyline(decode(polyline, 5));
      // console.log(dcodedPolyline?.map(c => ({ latitude: c[0], longitude: c[1] })))
    }
  }, [polyline])




  function tapLoc(e) {
    const destination = e.nativeEvent.coordinate
    setDectnation(destination)
  }

  function userloc(e) {
    const origin = e.nativeEvent.coordinate
    setLocation({ latitude: origin.latitude, longitude: origin.longitude })

  }

  function renderPoly() {

    if (dcodedPolyline) {
      const polyob = dcodedPolyline?.map(c => ({ latitude: c[0], longitude: c[1] }))
      return (
        <Polyline
          lineDashPattern={[1]}
          coordinates={polyob}
          strokeWidth={3} />
      )
    }
  }


  return (
    <View style={styles.container}>
      <MapView
        provider='google'
        mapType='standard'
        showsUserLocation
        zoomEnabled
        showsMyLocationButton={true}
        style={styles.map}
        onPress={e => tapLoc(e)}
        onUserLocationChange={e => userloc(e)}
      >


        {renderPoly()}

      </MapView>
    </View>
  )
}

export default App

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  map: {
    width: Dimensions.get('window').width,
    height: Dimensions.get('window').height,
  },
});

```

**Comment by Simon-TechForm** [comment] 2022-03-14 23:49
I'm going to close this for now as this haven't got a lot of traction, and I can't reproduce the issue with the sample code provided. If this is still an issue, please feel free to open a new issue, providing a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

**Closed by Simon-TechForm** 2022-03-14 23:49 UTC
Labels: bug
