### ISSUE TITLE
 ViewPropTypes will be removed from React Native. Migrate to ViewPropTypes exported from 'deprecated-react-native-prop-types'. 

### ISSUE THREAD

**Issue by ravin-amplework** [react-native-maps/react-native-maps#4325] opened 2022-07-15 04:48 UTC
### Summary

 ViewPropTypes will be removed from React Native. Migrate to ViewPropTypes exported from 'deprecated-react-native-prop-types'. 

### Reproducible sample code

```TSX
ViewPropTypes will be removed from React Native. Migrate to ViewPropTypes exported from 'deprecated-react-native-prop-types'. 
    at App (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.schoolhealth&modulesOnly=false&runModule=true:116180:24)
    at Connect(App) (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.schoolhealth&modulesOnly=false&runModule=true:211571:43)
    at Provider (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.schoolhealth&modulesOnly=false&runModule=true:211102:21)
    at RCTView
    at View
    at EnsureSingleNavigator (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.schoolhealth&modulesOnly=false&runModule=true:236451:24)
    at BaseNavigationContainer (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.schoolhealth&modulesOnly=false&runModule=true:235960:28)
    at ThemeProvider (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.schoolhealth&modulesOnly=false&runModule=true:242156:21)
    at NavigationContainerInner (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.schoolhealth&modulesOnly=false&runModule=true:242016:26)
    at App (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.schoolhealth&modulesOnly=false&runModule=true:116007:26)
    at RCTView
    at View
    at RCTView
    at View
    at AppContainer (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.schoolhealth&modulesOnly=false&runModule=true:79884:36)
    at SchoolHealth(RootComponent) (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.schoolhealth&modulesOnly=false&runModule=true:86264:28)
```

### Steps to reproduce

run project on react native  0.68.2

### Expected result

remove warning  ViewPropTypes will be removed from React Native

### Actual result

 ViewPropTypes will be removed from React Native. Migrate to ViewPropTypes exported from 'deprecated-react-native-prop-types'. 

### React Native Maps Version

0.30.1

### What platforms are you seeing the problem on?

Android, iOS (Google Maps)

### React Native Version

0.68.2

### What version of Expo are you using?

Not using Expo

### Device(s)

android 11

### Additional information

warning for  ViewPropTypes will be removed from React Native. Migrate to ViewPropTypes exported from 'deprecated-react-native-prop-types'.

**Comment by Simon-TechForm** [comment] 2022-07-15 06:53
This is fixed in [v0.31.0](https://github.com/react-native-maps/react-native-maps/releases/tag/v0.31.0).

**Closed by Simon-TechForm** 2022-07-15 06:53 UTC
Labels: bug

**Comment by ThirupathaiahR** [comment] 2022-07-15 13:57
Even though the code is updated with a new package getting same issue, Any suggestions ?

**Comment by Simon-TechForm** [comment] 2022-07-15 17:17
@ThirupathaiahR make sure to clean your project and reinstall. If you still get the warning after upgrading to >= v0.31.0 it's caused by some other library :)

**Comment by harish-narra** [comment] 2022-07-28 14:31
using updated version (0.31.0) with a new package getting the same issue, Any suggestions?

**Comment by harish-narra** [comment] 2022-07-28 14:32
@ravin-amplework , resolved this issue from your end?
