### ISSUE TITLE
Blank map after upgrading to react native 0.76.1 for iOS

### ISSUE THREAD

**Issue by iamrohitagg** [react-native-maps/react-native-maps#5237] opened 2024-11-27 03:40 UTC
### Summary

I am having MapView added in my mobile app but it is not working after upgrading react native to 0.76.1. I have done all the changes as required for iOS.

### Reproducible sample code

```TSX
import MapView, { Callout, Marker, PROVIDER_GOOGLE } from "react-native-maps";
const AnimatedMapView = Animated.createAnimatedComponent(MapView);

const App = ({initialRegion, config, mapRef, filteredStores,}) => 
<AnimatedMapView
              provider={PROVIDER_GOOGLE}
              ref={mapRef}
              style={styles.map}
              showsUserLocation={false}
              followUserLocation
              initialRegion={initialRegion ?? config.storeInitialRegion}
              rotateEnabled={false}
            >
              <View>
                {!!filteredStores?.length &&
                  filteredStores
                    .filter(
                      ({ address }) =>
                        address && address.latitude && address.longitude
                    )
                    .map((store) => (
                      <Marker
                        key={store.id}
                        identifier={store.id}
                        coordinate={{
                          latitude: store.address.latitude,
                          longitude: store.address.longitude,
                        }}
                      >
                        <Callout style={{ flex: 1 }}>
                          <View style={s.calloutDetailContainer}>
                            <View>
                              <Text style={s.storeName} numberOfLines={2}>
                                {store.name}
                              </Text>
                              <Text numberOfLines={2} style={s.storeAddress}>
                                {store.address.address}
                              </Text>
                            </View>
                          </View>
                        </Callout>
                      </Marker>
                    ))}
              </View>
            </AnimatedMapView>
```

### Steps to reproduce

Upgrade react native to 0.76.1

### Expected result

MapView must show marked location

### Actual result

Blank MapView

### React Native Maps Version

1.18.2

### What platforms are you seeing the problem on?

iOS (Apple Maps), iOS (Google Maps)

### React Native Version

0.76.1

### What version of Expo are you using?

Not using Expo

### Device(s)

iPhone all devices

**Comment by wojtekmaj** [comment] 2024-11-27 16:28
Potentially duplicate of #5206?

**Comment by salah-ghanim** [comment] 2024-12-15 11:20
Yes the AnimatedMapView doesn't seem to be supported anymore, I will look into it after finishing the basic Map migration.

most likely the MapView will work with default react animations without need for custom wrappers, but I will keep this issue open to keep track of this exact one

**Closed** 2024-12-25 13:44 UTC
Labels: bug
