### ISSUE TITLE
Streets turn black after specific zoom level on Android emulator running on a Macbook Pro M2 Pro

### ISSUE THREAD

**Issue by aacamhi** [react-native-maps/react-native-maps#4920] opened 2023-12-21 13:57 UTC
### Summary

The streets in the Android version of the React Native application are displaying as black, but the issue is observed only after reaching a specific zoom level. Despite attempts to set custom or default map styles, the problem persists. This issue is not observed in the iOS version. This issue is not observed in the Android version on an actual device. This issue is not observed when running the android emulator on a Macbook Pro M1.

### Reproducible sample code

```TSX
import React from 'react';
import MapView, { PROVIDER_GOOGLE } from 'react-native-maps';
import { MapStyle } from '@components/MapComponents/constants'
import useGeolocation from '@hooks '

export default function App() {
  const { currentLocation } = useGeolocation();
  return (
    <MapView
        //customMapStyle={MapStyle}
        style={{ width: '100%', height: '100%' }}
        initialRegion={{
          latitude: currentLocation.latitude,
          longitude: currentLocation.longitude,
          latitudeDelta: 0.09,
          longitudeDelta: 0.04,
        }}
        provider={PROVIDER_GOOGLE}
      />
  );
}
```

### Steps to reproduce

1. Run the provided React Native application on an Android emulator (Pixel 3a API version 33) on a Macbook Pro M2 Pro.
2. Zoom in and observe the map display.
3. The issue is encountered after reaching a specific zoom level.

### Expected result

Streets on the map should be displayed with a white color, as specified in the custom map styles or default styles, irrespective of the zoom level.

### Actual result

Streets are displayed as black on the Android version of the application after reaching a certain zoom level.
![Captura de pantalla 2023-12-21 a la(s) 11 10 15](https://github.com/react-native-maps/react-native-maps/assets/48267251/35e7d4ac-2114-4ed0-8885-f1ca094b90fc)
![Captura de pantalla 2023-12-21 a la(s) 11 10 32](https://github.com/react-native-maps/react-native-maps/assets/48267251/c98d992d-cff7-400f-b4e5-5beaaa909e87)

### React Native Maps Version

1.8.4

### What platforms are you seeing the problem on?

Android

### React Native Version

0.72.3

### What version of Expo are you using?

Not using Expo

### Device(s)

Android Simulators: Pixel 3a, Pixel 7 Pro (API 33)

### Additional information
- Dark mode is confirmed to be turned off on the Android emulator.
- The issue is not observed in the iOS version of the application.
- I am using a custom hook to get the current location but the bug persists even if I write the coordinates directly.
- The issue is not observed when running the application on an Android device.
- The issue is not observed when running the application on an Android emulator running on a Macbook Pro M1.

**Comment by mateki0** [comment] 2023-12-23 13:06
Hi @aacamhi are you able to reproduce this bug in a clean project? I have tried it in rn-maps example and in a clean project with the same react-native version as you have and everything seems to work fine. Maybe one of your dependency have influence on maps behavior?

**Comment by aacamhi** [comment] 2023-12-26 14:51
Thanks for the answer @mateki0 ! I created a clean project and still have the same bug. I'm thinking maybe the error is related to the android emulator. I am running it in a Macbook Pro M2 Pro. I will try to run my app in an actual android device.

**Comment by aacamhi** [comment] 2023-12-26 18:07
I ran the app on an android device and on an android emulator running on a Macbook Pro M1 and the bug was not observed. So, i am updating the title and description of the issue to add more specificity.

**Comment by mateki0** [comment] 2023-12-27 07:12
Thanks for the clarification. Unfortunately I don't have access to Macbook Pro M2 so I'm not able to reproduce it. However I don't think this is the react-native-maps bug as far as it works fine on physical devices with the same Android as you have in emulator

**Comment by imjakechapman** [comment] 2024-01-05 08:17
I'm actually facing the same issue. Blank project, fresh install.  Have `userInterfaceStyle={colorScheme}` and the map itself doesn't even swap over to dark mode on android emulator. Zoom in and eventually all streets turn black.

**Comment by fourthperson** [comment] 2024-01-08 09:39
I don't think this is a Mac issue because my streets are also black, and I am running a Pixel 5, API 34 emulator on a Debian 12 workstation with kernel  6.1.0-17-amd64
However, running on a real device, the maps seem okay.

React Native: 0.72
react-native-maps 1.9.1

My research has led me to these two links, something about a new Map Renderer that should be implemented.

https://issuetracker.google.com/issues/295677329?pli=1

https://developers.google.com/maps/documentation/android-sdk/renderer

Out of context, but Flutter seems to have the same issue too:
https://stackoverflow.com/questions/77641340/path-roads-are-black-in-google-maps-flutter

So maybe the issue is not the mac but an underlying issue with maps on android. Should the developers implement the "New Map Renderer" perhaps?

**Comment by mateki0** [comment] 2024-01-08 16:28
Thanks for further research @fourthperson. Can you try to add this code and check if it helps?

```javascript
import {enableLatestRenderer} from 'react-native-maps';

enableLatestRenderer();
```

Source: https://github.com/react-native-maps/react-native-maps/blob/master/docs/installation.md#using-the-new-google-maps-renderer

@aacamhi Can you test it also?

**Comment by fourthperson** [comment] 2024-01-12 07:33
> Thanks for further research @fourthperson. Can you try to add this code and check if it helps?
> 
> ```js
> import {enableLatestRenderer} from 'react-native-maps';
> 
> enableLatestRenderer();
> ```
> 
> Source: https://github.com/react-native-maps/react-native-maps/blob/master/docs/installation.md#using-the-new-google-maps-renderer
> 
> @aacamhi Can you test it also?

I added this code in my App.js and logged the return value, 
On one system (Laptop running Debian) it shows `LATEST` and the map is fine as it should be, but on the Workstation, the same code returns `LEGACY` and the streets are black.

I guess that 'fixes' things in a way, depending on which renderer the emulator chooses to use. I am satisfied at the moment, but will report back if I have any more findings, since the black streets are annoying. It's great that it's not a major problem that shows up in production.

**Comment by salah-ghanim** [comment] 2024-01-12 17:32
I'm closing this issue because the latest renderer should be enabled by default with the new google maps iOS SDK that was included in the 1.9.0 release of the library

**Closed by salah-ghanim** 2024-01-12 17:32 UTC
Labels: bug

**Comment by dangiashish** [comment] 2024-01-23 08:26
I am facing the same issue in Pixel 7 Pro emulator, I believe this one is an emulator bug.

**Comment by admirhusic** [comment] 2024-01-23 10:47
Just an update from a native Android developer. This issue also occurs when working with Google Maps in the native map.

 However, here are the things I have discovered so far:

1. It happens only on Pixel emulators, not on other emulators.
2. It does not happen on a real device (Samsung A14).
3. It occurs only when overriding the default theme of the map.


I came across this issue on Google when I was trying to solve it, and I thought it might be helpful for you, my JavaScript friends. 😄

**Comment by PavleNeskovic** [comment] 2024-01-24 12:57
> I am facing the same issue in Pixel 7 Pro emulator, I believe this one is an emulator bug.

issue still happening, here's what I've tried:

- react-native-maps versions: 1.7.1, 1.10.0 (latest atm)
- different emulator devices: pixel, nexus

**Comment by dangiashish** [comment] 2024-01-24 12:59
> > I am facing the same issue in Pixel 7 Pro emulator, I believe this one is an emulator bug.
> 
> issue still happening, here's what I've tried:
> 
> - react-native-maps versions: 1.7.1, 1.10.0 (latest atm)
> - different emulator devices: pixel, nexus

But what about Map SDK For Android ? How to resolve this in Native Android Map ?
ie - Pixel 7 Pro.

**Comment by NooryA** [comment] 2024-01-29 04:29
Any update on this issue? facing this on my pixel also

**Comment by Gowthamr2130** [comment] 2024-02-01 08:45
> Just an update from a native Android developer. This issue also occurs when working with Google Maps in the native map.
> 
> However, here are the things I have discovered so far:
> 
> 1. It happens only on Pixel emulators, not on other emulators.
> 2. It does not happen on a real device (Samsung A14).
> 3. It occurs only when overriding the default theme of the map.
> 
> I came across this issue on Google when I was trying to solve it, and I thought it might be helpful for you, my JavaScript friends. 😄

Any way to fix this issue in emulator without coading.

**Comment by admirhusic** [comment] 2024-02-01 09:08
Update: The next day, the issue just dissapeared by itself.

**Comment by dangiashish** [comment] 2024-02-01 09:12
nope, I have tried by re-installing the emulator with different device and different SDK version, But still facing the same issue.. Actually it is happening at a fixed zoom level on the map 🤔

**Comment by fikkatra** [comment] 2024-02-26 15:32
Using a Macbook M1 Pro here. 
I'm experiencing the issue on the following emulators: Pixel 5 API 30, 31 and 34
NOT experiencing the issue on a Pixel 7 emulator with API 33.

Executing `enableLatestRenderer()`; does not fix the issue.

**Comment by n-misic** [comment] 2024-02-28 17:27
Having the same issue.
Android API 34
Android Emulator

react-native-maps 1.9.1

**Comment by mishkeTz** [comment] 2024-02-28 17:28
I have the same issue.
Android Emulator API 34
react-native-maps 1.9.1

**Comment by mateki0** [comment] 2024-03-03 07:01
Can anyone with this problem check if this solution helps you? https://github.com/react-native-maps/react-native-maps/issues/4986#issuecomment-1968878033

Maybe your emulators are still using old renderer and that's the issue here.

**Comment by flmalte** [comment] 2024-03-09 14:47
I have the same issue but it only happens when the map has a size of >=69%

**Comment by BuyMyBeard** [comment] 2024-03-18 23:06
> Can anyone with this problem check if this solution helps you? [#4986 (comment)](https://github.com/react-native-maps/react-native-maps/issues/4986#issuecomment-1968878033)
> 
> Maybe your emulators are still using old renderer and that's the issue here.

This solution worked for me, thanks for the help!

**Comment by BuyMyBeard** [comment] 2024-03-18 23:08
> Can anyone with this problem check if this solution helps you? [#4986 (comment)](https://github.com/react-native-maps/react-native-maps/issues/4986#issuecomment-1968878033)
> 
> Maybe your emulators are still using old renderer and that's the issue here.

This unfortunately didn't work for me. At about 15 of zoom, all the roads turn black.

**Comment by ashhusen97** [comment] 2024-05-13 05:05
if anyone still facing this issue here is the solution : 
latitudeDelta and longitudeDelta is causing this issue set both to 0.1 and the issue will resolve

**Comment by quentinncl** [comment] 2024-05-14 09:17
Same issue here on a Pixel 8 Pro emulator using expo 50 :confused: 
```javascript
import {enableLatestRenderer} from 'react-native-maps';

enableLatestRenderer();
```
not working either

**Comment by khinlei1998** [comment] 2024-05-14 17:27
I'm ok for android device.

**Comment by plppp2001** [comment] 2024-06-27 12:43
> I'm ok for android device.

Yours is working fine when you zoom in?

**Comment by mateoLorenzo** [comment] 2024-06-28 03:14
Still facing this issue :v

**Comment by mateoLorenzo** [comment] 2024-06-28 04:32
GPT gave me a workaround, I leave it here for anyone who may seem it useful:

First define an object for the MapView custom styles

```js
const mapStyle = [
  {
    elementType: 'geometry',
    stylers: [{color: '#242f3e'}],
  },
  {
    elementType: 'labels.text.stroke',
    stylers: [{color: '#242f3e'}],
  },
  {
    elementType: 'labels.text.fill',
    stylers: [{color: '#746855'}],
  },
  {
    featureType: 'administrative.locality',
    elementType: 'labels.text.fill',
    stylers: [{color: '#d59563'}],
  },
  {
    featureType: 'poi',
    elementType: 'labels.text.fill',
    stylers: [{color: '#d59563'}],
  },
  {
    featureType: 'poi.park',
    elementType: 'geometry',
    stylers: [{color: '#263c3f'}],
  },
  {
    featureType: 'poi.park',
    elementType: 'labels.text.fill',
    stylers: [{color: '#6b9a76'}],
  },
  {
    featureType: 'road',
    elementType: 'geometry',
    stylers: [{color: '#38414e'}],
  },
  {
    featureType: 'road',
    elementType: 'geometry.stroke',
    stylers: [{color: '#212a37'}],
  },
  {
    featureType: 'road',
    elementType: 'labels.text.fill',
    stylers: [{color: '#9ca5b3'}],
  },
  {
    featureType: 'road.highway',
    elementType: 'geometry',
    stylers: [{color: '#746855'}],
  },
  {
    featureType: 'road.highway',
    elementType: 'geometry.stroke',
    stylers: [{color: '#1f2835'}],
  },
  {
    featureType: 'road.highway',
    elementType: 'labels.text.fill',
    stylers: [{color: '#f3d19c'}],
  },
  {
    featureType: 'transit',
    elementType: 'geometry',
    stylers: [{color: '#2f3948'}],
  },
  {
    featureType: 'transit.station',
    elementType: 'labels.text.fill',
    stylers: [{color: '#d59563'}],
  },
  {
    featureType: 'water',
    elementType: 'geometry',
    stylers: [{color: '#17263c'}],
  },
  {
    featureType: 'water',
    elementType: 'labels.text.fill',
    stylers: [{color: '#515c6d'}],
  },
  {
    featureType: 'water',
    elementType: 'labels.text.stroke',
    stylers: [{color: '#17263c'}],
  },
];
```

Then, use the MapView as bellow: 

```js
<MapView
  provider={
    Platform.OS === 'android' ? PROVIDER_GOOGLE : PROVIDER_DEFAULT
  }
  customMapStyle={mapStyle}
  ref={map}
  style={styles.map}
  initialRegion={initialRegion}>
  <Marker
    coordinate={origin}
    draggable
    onDragEnd={direction => setOrigin(direction.nativeEvent.coordinate)}
  />
</MapView>
```

Hope this be useful

**Comment by plppp2001** [comment] 2024-06-28 08:15
> Still facing this issue :v

I'm developing a .NET MAUI app for Android and iOS using the latest Visual Studio 2022. Android emulator and google maps got fixed when I installed the latest Android SDK Platform-Tools 35.0.1 and restarted my windows 11 comp. I got all the latest installed for Android SDKs and Tools;
![image](https://github.com/react-native-maps/react-native-maps/assets/45370058/6abe2dd5-8941-44cb-b26a-b453dd1bc0d6)

![image](https://github.com/react-native-maps/react-native-maps/assets/45370058/952a52d5-6d74-4db4-8b0f-d60614eff710)

![image](https://github.com/react-native-maps/react-native-maps/assets/45370058/e4e80c19-a752-4c78-9598-cc7200003ea2)

Latest for VS2022:
![image](https://github.com/react-native-maps/react-native-maps/assets/45370058/b76a9c15-70c9-42d2-899c-0005d5ad33c5)

**Comment by benoit-ctrl** [comment] 2025-02-07 15:11
I can confirm that in an emulator using API 35, the problem has disappeared

**Comment by dangiashish** [comment] 2025-02-08 02:31
Yes you are right.. Now it has resolved.
> I can confirm that in an emulator using API 35, the problem has disappeared

**Comment by pancybernetyk** [comment] 2025-02-21 10:52
It works well for me on **API 34 + Pixel 4 (+Store)** - Macbook Pro M2, Visual Studio for Mac 17.6.14. 

![Image](https://github.com/user-attachments/assets/5dbe1bcf-3ec9-40fc-a89d-3bc62846be8a)
