### ISSUE TITLE
Default markers show on iOS devices.

### ISSUE THREAD

**Issue by vegetablesalad** [react-native-maps/react-native-maps#4618] opened 2023-02-23 09:59 UTC
### Summary

I have this issue where default markers are visible, but not always and not for all markers. It's kind of strange I can't really determine when/why it shows up.

![IMG_8598](https://user-images.githubusercontent.com/2006277/220873488-aa95e41b-4105-4721-8198-8e8e1d6d726f.PNG)

### Reproducible sample code

```TSX
<Marker {...markerProps} >
      <Image
        source={sourceImage}
        style={{ width: 55, height: 40 }}
        resizeMode="stretch"
        resizeMethod="resize"
      />
    </Marker>
```

### Steps to reproduce

"react": "18.2.0",    
"react-native-map-clustering": "^3.4.2",
"react-native-maps": "^1.4.0",
"react-native": "0.70.6"

Pure react native project with expo modules.

Tested on iPhone 7 (15.1)

### Expected result

Should show just my defined markers.

### Actual result

Show the default red pins.

### React Native Maps Version

1.4.0

### What platforms are you seeing the problem on?

iOS (Apple Maps)

### React Native Version

0.70.6

### What version of Expo are you using?

Not using Expo

### Device(s)

iPhone 7 (15.1)

**Comment by teeserted** [comment] 2023-03-06 17:19
Hello!

I've got the same issue and I've managed to make it reproducable. 

1. Have two views that use the same MapView Fragment
2. Navigate to first view where markers show, markers are loaded as they should
3. Navigate to another map view where other markers are shown.
4. Navigate back to first map view - pins are shown.

**Comment by vegetablesalad** [comment] 2023-03-15 09:33
Seems to work with "image" attribute as well.
```jsx
            <Marker
              key={`k-${s.id}`}
              coordinate={s.coordinate}
              tracksViewChanges={false}
              image={s.marker.image}
            />
```

**Comment by kneza23** [comment] 2023-03-15 10:52
yeah, same things happens for me, ios pin icon is displayed when changing marker coordinates on state changes

**Comment by vegetablesalad** [comment] 2023-03-15 21:10
I really don't want to switch to google maps on iOS, but I might have no other options. This seems like a major issue. I am great with native Android, but unfortunately my iOS coding skills are lacking - otherwise I might try to find and fix the issue.

**Comment by nicolas-rohricht** [comment] 2023-03-28 18:30
Having the same issue here.

"react-native-maps": "^1.4.0"
"react-native": "0.68.1",

<img width="408" alt="image" src="https://user-images.githubusercontent.com/38505703/228333525-5bd39489-a587-47d4-a9ab-e84e2998e043.png">

**Comment by nicolas-rohricht** [comment] 2023-03-31 15:12
> I really don't want to switch to google maps on iOS, but I might have no other options. This seems like a major issue. I am great with native Android, but unfortunately my iOS coding skills are lacking - otherwise I might try to find and fix the issue.

I found this https://github.com/react-native-maps/react-native-maps/issues/4214#issuecomment-1132214457 in another issue, it fixed it for me...
Just in case you still need a fix for that.

**Comment by Simon-TechForm** [comment] 2023-04-20 22:29
Duplicate of #4214

**Closed by Simon-TechForm** 2023-04-20 22:29 UTC
Labels: bug

**Comment by austinGENEreeve** [comment] 2023-07-04 07:15
Is a patch really the only still the only solution for this?

**Comment by austinGENEreeve** [comment] 2023-07-04 07:20
Is a patch really still the only solution for this?

**Comment by ml242** [comment] 2023-08-04 15:24
Very frustrating. My map renders properly at first but after clicking around it loses track of my custom pins and replaces them with unclickable default ones.
