### ISSUE TITLE
MapView only display google logo when borderRadius and overflow hidden are applied

### ISSUE THREAD

**Issue by Onzeka** [react-native-maps/react-native-maps#4646] opened 2023-03-21 01:01 UTC
### Summary

Hello !

When I try to render a mapview in a container with border radius and overflow hidden only the google logo is displayed and the map is just transparent.

PS Thank you for all the work you put in  the library.

### Reproducible sample code

```TSX
import { StyleSheet, View } from "react-native";
import RNMapView, { PROVIDER_GOOGLE } from "react-native-maps";
import mapStyle from "@assets/mapStyle";


function MapView(props){
    const {style,...rest} = props;
    return(
        <View style={[style,{overflow:"hidden",flex:1,backgroundColor:"white",borderRadius:30}]}>
            <RNMapView 
                provider={PROVIDER_GOOGLE} 
                customMapStyle={mapStyle} 
                {...rest} 
                style={[StyleSheet.absoluteFill]}
            />
        </View>
    )

}
export default MapView
```

### Steps to reproduce

use the code above remove the border radius the map will be displayed correctly, without the border radius the map is transparent and you ll only have the google logo. 

### Expected result

the map should be display even when a border radius is applied

### Actual result

the map is not displayed

### React Native Maps Version

1.4.0

### What platforms are you seeing the problem on?

Android

### React Native Version

0.70.6

### What version of Expo are you using?

Not using Expo

### Device(s)

emulator Pixel_4_API_31

**Comment by Simon-TechForm** [comment] 2023-04-20 22:24
Hello @Onzeka 👋

I'm unable to reproduce the issue. The provided code isn't runnable as is, but I tried reproducing the issue using the following code:
```ts
import React from 'react';
import {StyleSheet, View} from 'react-native';
import MapView from 'react-native-maps';

export default function App() {
  return (
    <View style={styles.container}>
      <MapView style={[StyleSheet.absoluteFill]} />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    overflow: 'hidden',
    flex: 1,
    backgroundColor: 'white',
    borderRadius: 30,
  },
});
```

![Screenshot_1682029160](https://user-images.githubusercontent.com/73996878/233499619-681e0e5a-12db-4982-802c-23875ea7f458.png)

**Comment by Onzeka** [comment] 2023-04-24 11:26
Hello @Simon-TechForm ,

Thank you for your reply ! I will try again this week maybe I made a mistake on my end

**Comment by Simon-TechForm** [comment] 2023-04-24 21:47
@Onzeka sure! I hope you are okay with me closing this for now then :)

**Closed by Simon-TechForm** 2023-04-24 21:47 UTC
Labels: bug, cannot reproduce

**Comment by Onzeka** [comment] 2023-05-18 13:42
Hello @Simon-TechForm,

Please do you have the RN version and the react-native-maps  you are using I tried on my end with the code you provided it doesnot seem to be working.

![image](https://github.com/react-native-maps/react-native-maps/assets/48027322/001a0bc0-b617-4a8f-93fc-2e034b322acc)

**Comment by phamtien1709** [comment] 2023-10-30 05:21
> Hello @Simon-TechForm,
> 
> Please do you have the RN and the react-native-ma versions you are using ? I tried on my end with the code you provided it doesnot seem to be working for me.
> 
> ![image](https://user-images.githubusercontent.com/48027322/239248726-001a0bc0-b617-4a8f-93fc-2e034b322acc.png)

Hi @Onzeka,
Please using *.jsx file

**Comment by marchiartur** [comment] 2023-12-01 14:47
> > Hello @Simon-TechForm,
> > Please do you have the RN and the react-native-ma versions you are using ? I tried on my end with the code you provided it doesnot seem to be working for me.
> > ![image](https://user-images.githubusercontent.com/48027322/239248726-001a0bc0-b617-4a8f-93fc-2e034b322acc.png)
> 
> Hi @Onzeka, Please using *.jsx file

set flex = 1 in the mapview and remove flex 1 from the wrapping view
