### ISSUE TITLE
Android / Google Maps. Polygon fill color not updating properly

### ISSUE THREAD

**Issue by JacquesLeupin** [react-native-maps/react-native-maps#3946] opened 2021-09-08 20:08 UTC
# Bug report

## Summary

- In my react native app, I have a map with polygons, and the polygons' fill color updates based on stateful values supplied by an animated Flatlist
- On iOS, the fill color is updating properly on scroll of Flatlist, but on Android the fill color is updating incorrectly
- I'm not sure if this is related to #3057 or #3025

## Environment info

`react-native info` output:

```bash
    "react": "17.0.2",
    "react-native": "0.65.1"
    "react-native-maps": "^0.28.0",
```

## Steps to reproduce

1. Attempt to dynamically update fill color of polygons based on scroll position of scrollview / flatlist
2. Run android simulator to reproduce

Describe what you expected to happen:

1. I expect Android behavior to match iOS behavior

Describe what you actually happens:

1. Android polygon fill color changes incorrectly

## Reproducible sample code

```
const AlertsMap = () => {
  const language = useSelector((state) => get(state, 'user.language', 'en'));
  const alerts = useSelector((state) => get(state, 'alerts.activeAlerts', []));
  const [mapIdx, setMapIdx] = useState(0);
  const themeContext = useContext(ThemeContext);
  const { region } = useMapBoundary(alerts);

  const _scrollView = useRef(null);
  const _map = useRef(null);
  let mapAnimation = new Animated.Value(0);
  let mapIndex = 0;

  useEffect(() => {
    mapAnimation.addListener(({ value }) => {
      // animate 30% away from landing on the next item
      let index = Math.floor(value / CARD_WIDTH + 0.3);
      if (index >= alerts.length) {
        index = alerts.length - 1;
      }
      if (index <= 0) {
        index = 0;
      }

      // @ts-ignore
      clearTimeout(regionTimeout);
      const regionTimeout = setTimeout(() => {
        if (mapIndex !== index) {
          // eslint-disable-next-line react-hooks/exhaustive-deps
          mapIndex = index;
          setMapIdx(index);
          const { minCoords, maxCoords } = AlertsService.getMinMaxLatLng(
            alerts[index],
          );
          const latitudeDelta =
            Math.abs(maxCoords.latitude - minCoords.latitude) + 10;
          const longitudeDelta =
            Math.abs(maxCoords.longitude - minCoords.longitude) + 10;
          const regionToMove = {
            latitude: minCoords.latitude,
            longitude: maxCoords.longitude,
            latitudeDelta,
            longitudeDelta,
          };
          // @ts-ignore
          _map.current.animateToRegion(regionToMove, 350);
        }
      }, 10);
    });
  });

  const renderItem = ({ item }: any) => {
    const id = item.alert.NAADSGUID;
    const isCritical = AlertsService.isCriticalAlert(item);
    const alertInUserLanguage = AlertsService.getAlertInUserLanguage(
      item,
      language,
    );
    const {
      headline,
      effective,
      description,
      event,
      area: { areaDesc },
    } = alertInUserLanguage as AlertInfo;
    const date = moment(effective).format('MMMM Do YYYY, hh:mm');
    return (
      <AlertsMapCard
        key={id}
        id={id}
        isCritical={isCritical}
        headline={headline}
        date={date}
        description={description}
        event={event}
        areaDesc={areaDesc}
      />
    );
  };

  return (
    <>
      <MapView
        ref={_map}
        style={styles.map}
        initialRegion={region}
        showsUserLocation={true}
        loadingEnabled={true}
        loadingIndicatorColor={themeContext.palette.primary}>
        {alerts.map((alert: CompleteAlertData, i: number) => {
          const isCriticalAlert = AlertsService.isCriticalAlert(alert);
          return alert.alert.info[0].area.googleMapsPolygon.map((polygon) => (
            <Polygon
              key={alert.alert.NAADSGUID}
              coordinates={
                polygon as {
                  latitude: number;
                  longitude: number;
                }[]
              }
              strokeWidth={1}
              fillColor={
                mapIdx === i
                  ? isCriticalAlert
                    ? themeContext.palette.mapsWarning
                    : themeContext.palette.mapsYellow
                  : undefined
              }
              strokeColor={
                isCriticalAlert
                  ? themeContext.palette.error
                  : themeContext.palette.darkYellow
              }
            />
          ));
        })}
      </MapView>
      <AnimatedFlatlist
        ref={_scrollView}
        horizontal
        data={alerts}
        keyExtractor={(item: any) => item.alert.NAADSGUID}
        renderItem={renderItem}
        pagingEnabled
        scrollEventThrottle={1}
        showsHorizontalScrollIndicator={false}
        snapToInterval={CARD_WIDTH + 20}
        snapToAlignment="center"
        contentInset={{
          top: 0,
          left: SPACING_FOR_CARD_INSET,
          bottom: 0,
          right: SPACING_FOR_CARD_INSET,
        }}
        contentContainerStyle={styles.contentContainerStyle}
        onScroll={Animated.event(
          [
            {
              nativeEvent: {
                contentOffset: {
                  x: mapAnimation,
                },
              },
            },
          ],
          { useNativeDriver: true },
        )}
      />
    </>
  );
};
```

Here's a link to a google drive folder of emulator recordings of the issue on Android (and expected behavior on iOS): https://drive.google.com/drive/folders/1EdRXmIk9D1vu8qcHKU67Ev2dh6j__QL_?usp=sharing

**Comment by christopherdro** [comment] 2021-09-08 21:50
Is this a duplicate of https://github.com/react-native-maps/react-native-maps/issues/3057 ?

**Comment by JacquesLeupin** [comment] 2021-09-08 22:23
This may be a duplicate. I'd chosen to open another issue, however, after reading through #3057 because most of the comment in that issue mention iOS, not Android.

**Comment by Simon-TechForm** [comment] 2022-03-16 08:40
@JacquesLeupin could you please update your sample code to a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)? I can't run the code you provided, as there are multiple custom hooks, functions, components etc :)

**Closed** 2022-03-25 21:49 UTC
Labels: bug
