### ISSUE TITLE
Map pins are too large on build

### ISSUE THREAD

**Issue by arronhunt** [react-native-maps/react-native-maps#2016] opened 2018-02-06 22:54 UTC
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

react-native: 0.51.0 
react: 16.0.0
react-native-maps: 0.19.0

Target Platform: iOS - 11.2.5 iPhone X Device (Apple Maps)

_NOTE: I am using the maps version that is bundled with Expo_

### Steps to Reproduce

Create a new map marker with the following code:

```jsx
const INACTIVE_PIN = require('path-to-image');

<MapView.Marker
    key={key}
    title={title}
    coordinate={coords}
    image={INACTIVE_PIN}
>
    <MapView.Callout tooltip={false} onPress={() => {}>
        {... custom callout component }
    </MapView.Callout>
</MapView.Marker>
```

### Expected Behavior

Map pins will render to the map

### Actual Behavior

Map pins will display correctly on the simulator, but once they are built and published, the production build shows much larger pin sizes. See images below:

**SIMULATOR:**
<img width="370" alt="screen shot 2018-02-06 at 2 42 00 pm" src="https://user-images.githubusercontent.com/298336/35888616-312cefe8-0b4d-11e8-9ea7-0d2696af0ffe.png">

**PRODUCTION BUILD:**
<img width="370" alt="screen shot 2018-02-06 at 2 42 00 pm" src="https://user-images.githubusercontent.com/298336/35888625-36cb17e0-0b4d-11e8-8d96-3fc5335e92ce.jpeg">

**IMAGE ASSET FOR PIN:**
![map_pin](https://user-images.githubusercontent.com/298336/35888691-76be1c58-0b4d-11e8-9f73-23428f2cf263.png)

### Reproducible Demo

~I'm not sure how to link to a demo, since the bug occurs on building the project. I can try to create a new build if this is absolutely essential to the bug report, but it is a process to get that done.~

https://snack.expo.io/@arronhunt/map-example

**Comment by rborn** [comment] 2018-02-07 12:44
@arronhunt try to provide to the app all size images aka @1x,@2x,@3x

**Comment by jskidd3** [comment] 2018-02-09 13:56
@rborn I am also experiencing the same issues and my markers are sized as you've described. My require line looks like this: `require('../img/markers/red/vehicle.png')`. I have the files at that directory, `vehicle@1x.png`, `vehicle@2x.png`, `vehicle@3x.png`. The largest `3x` file is being shown but it's not downscaling the file so it appears large on the map as @arronhunt's screenshots show.

**Comment by alvelig** [comment] 2018-02-09 14:32
@arronhunt @jskidd3 This is certainly @2x, @3x problem. Make sure that your @2x and @3x images are 2 and 3 times corresponding to the original image size. eg: original: 25x25, 2x: 50x50, 3x: 75x74

**Comment by jskidd3** [comment] 2018-02-09 14:35
@alvelig The sizes are correct, but I noticed your `@3X` has a capital `X`. Will that be the cause of the problem? Mine are currently all lowercase `x`.

**Comment by alvelig** [comment] 2018-02-09 14:36
@jskidd3  they should be lowercase. `@3x` https://facebook.github.io/react-native/docs/images.html

**Comment by alvelig** [comment] 2018-02-09 14:37
@arronhunt your production build is ok, because this is the actual pin size.

**Comment by jskidd3** [comment] 2018-02-09 14:38
@alvelig Ok thanks. I've worked around temporarily by inserting image as a child of the marker and scaling with style but I'll set up a demo project shortly.

**Comment by jskidd3** [comment] 2018-02-10 15:53
@alvelig Just coming back to confirm, I reverted back to using the `image` prop today and it's working fine now. I haven't changed anything, but I did do a `cd android; ./gradlew clean` this morning and my thinking is that would have sorted it.

**Comment by alvelig** [comment] 2018-02-10 16:04
@jskidd3 glad you sorted it

@arronhunt if you keep experiencing this after adding x2 and x3, let us know.

**Comment by arronhunt** [comment] 2018-02-13 16:06
Sorry for the delay in updates. Just did another release build this morning and can confirm that even with the 1x 2x 3x assets, pins are too large on the map after building. 

Here's the snack I used to re-create -> https://snack.expo.io/@arronhunt/map-example

You need to build the project to replicate the steps to reproduce. Also a a note, when previewing the snack I'm getting the opposite issue (pins are now too tiny).

**Comment by arronhunt** [comment] 2018-02-13 16:06
Sorry for the delay in updates. Just did another release build this morning and can confirm that even with the 1x 2x 3x assets, pins are too large on the map after building.

Here's the snack I used to re-create -> https://snack.expo.io/@arronhunt/map-example

You need to build the project to replicate the steps to reproduce. Also a a note, when previewing the snack I'm getting the opposite issue (pins are now too tiny).

cc @alvelig

**Comment by arronhunt** [comment] 2018-02-13 16:07
Here are the assets I am using 

![map_pin](https://user-images.githubusercontent.com/298336/36159998-fd2a6750-1094-11e8-8441-57a15ee8e758.png)
![map_pin 2x](https://user-images.githubusercontent.com/298336/36159999-fd458f62-1094-11e8-882e-b77e09981d39.png)
![map_pin 3x](https://user-images.githubusercontent.com/298336/36160000-fd5e999e-1094-11e8-8bab-92c3a8e297c3.png)

**Comment by alvelig** [comment] 2018-02-13 17:46
@arronhunt Looks like an expo issue. I marked photos x1, x2 and x3 respectively.

See expo:
![photo4906750632896079896](https://user-images.githubusercontent.com/4231544/36164181-636fe1ea-10ca-11e8-98b3-2a72f26d2d19.jpg)

See native build: (Master in this repo https://github.com/alvelig/react-native-maps-example)
![photo4906750632896079897](https://user-images.githubusercontent.com/4231544/36164904-9ad863e4-10cc-11e8-80a6-a87fadf8c43e.jpg)

**Comment by alvelig** [comment] 2018-02-13 17:47
Please try https://github.com/alvelig/react-native-maps-example and comment

**Comment by RyanTG** [comment] 2019-06-05 03:15
I don’t mean to necro this, but I’m experiencing this, as well. Also using the react-native-maps that is bundled with Expo (which right now is 0.22). 

My sizes are 20x20, 40x40, 60x60. And not only is the marker larger in the iOS build, it’s visibly pixelated. But there’s no height/width prop for marker images, so I can’t be accidentally blowing them up larger than they should be. If you suggest, I can start a new issue.

**Comment by chrise86** [comment] 2019-08-18 20:09
I’m also facing this issue. File names are correct, and in development / debug mode on both simulator and device they appear the correct size. When running in release mode the pins are much larger.

**Comment by chrise86** [comment] 2019-08-19 18:21
I've tried various combinations of using and not using @2x and @3x and still getting the same issues. Does anyone know how to resolve this?

**Comment by RyanTG** [comment] 2019-08-19 18:59
It helped when I specified the size, like this:
````
import markerDot from '../assets/images/markerdot.png'
...
<View>
       <Image source={markerDot} style={{height:20,width:20}} onLoad={this.stopRendering} />
</View>
````
and I made:
markerdot.png (20x20)
markerdot@2x.png (40x40)
markerdot@3x.png (60x60)

**Comment by chrise86** [comment] 2019-08-19 21:24
@RyanTG the problem is I'm not using images like that, but rather passing it down via the `image={}` prop.

I'm also using a custom callout, and when I tried using a custom image inside the marker component the callouts no longer rendered correctly.

**Comment by RyanTG** [comment] 2019-08-19 22:53
Sure. I was using `image={}` before I discovered this issue. Had to wrap it in `<View></Image...`. I also had a custom callout, too, and had to abandon it. [Here's our code now](https://github.com/bpoore/pbm-react/blob/master/app/screens/Map.js).

**Comment by ph1lb4** [comment] 2021-08-18 10:13
I am not sure why this issue is closed - Exact same thing that was described here numerous times is still happening. When using the `image={}` prop with a require path, the built version shows the images too large Even though @2x and @3x images are provided with correct naming and sizes. The workaround with custom markers is not working for me either because it is lagging way too much.

**Comment by pacarvalho** [comment] 2022-02-23 02:19
Has anyone been able to address this issue whilst using the image prop?

**Comment by Simon-TechForm** [comment] 2022-07-23 22:40
I'm unable to reproduce the issue. I tried using both expo and vanilla react-native with the markers provided in https://github.com/react-native-maps/react-native-maps/issues/2016#issuecomment-365314178 named `marker.png`, `marker@2x.png`and `marker@3x.png` with the following code:

```ts
import React from 'react';
import {StyleSheet} from 'react-native';
import MapView, {Marker} from 'react-native-maps';

const initialRegion = {
  latitude: 37.78825,
  longitude: -122.4324,
  latitudeDelta: 0.0922,
  longitudeDelta: 0.0421,
};

export default function App() {
  return (
    <MapView style={styles.mapView} initialRegion={initialRegion}>
      <Marker
        coordinate={{
          latitude: initialRegion.latitude,
          longitude: initialRegion.longitude,
        }}
        image={require('./marker.png')}
      />
    </MapView>
  );
}

const styles = StyleSheet.create({
  mapView: {
    flex: 1,
  },
});
```
Can anyone still experiencing this provide an up to date reproducible code (and as important, steps to reproduce)? That is, expo 45/46 and/or `react-native-maps@1.1.0` :)

**Comment by Simon-TechForm** [comment] 2022-08-11 20:26
I'm closing for now. If anyone is still experiencing this, please comment with an up to date reproducible example and I'll be happy to re-open :)

**Closed by Simon-TechForm** 2022-08-11 20:26 UTC
Labels: Information Needed

**Comment by byyoungjin** [comment] 2023-01-30 03:55
Having same issue but with icon props..

**Comment by tamhoangminh** [comment] 2023-10-02 04:06
I have the same problem with v1.7.1 when using image prop with require path. My image only got 58x58, then I have to resize it with `react-native-image-resizer` and the result like this
![image](https://github.com/react-native-maps/react-native-maps/assets/64513661/33ef364c-16f2-417e-b969-9958ad6f74a6)

**Comment by thong-dipro** [comment] 2023-11-06 06:24
Try to export 2x and 4x and nothing else, fixed

<img width="252" alt="image" src="https://github.com/react-native-maps/react-native-maps/assets/108516214/4bae68f7-8fd3-4b04-a952-11bee9306c64">

**Comment by Abbaskatariya** [comment] 2024-11-15 12:12
use 30px * 30px it's work

**Comment by ryskin** [comment] 2024-12-28 06:37
> Try to export 2x and 4x and nothing else, fixed
> 
> <img alt="image" width="252" src="https://private-user-images.githubusercontent.com/108516214/280612164-4bae68f7-8fd3-4b04-a952-11bee9306c64.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUzNjgwNTUsIm5iZiI6MTczNTM2Nzc1NSwicGF0aCI6Ii8xMDg1MTYyMTQvMjgwNjEyMTY0LTRiYWU2OGY3LThmZDMtNGIwNC1hOTUyLTExYmVlOTMwNmM2NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyOFQwNjM1NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYmE1OWI4YWE1ODM1YTliNTlmMWU2MzkxNTA1ZDdjYTNlNzMxYzBhZWY1NDVkYjJkMWJlNDU2MWQ1MDMzMjQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Xq3UEZ0sy9PCn8JLfZabVKc8_C7mNruhss48BLKjH9A">

I did but not help
