### ISSUE TITLE
onRegionChange called after onRegionChangeComplete

### ISSUE THREAD

**Issue by lxr-mwhite** [react-native-maps/react-native-maps#5142] opened 2024-08-16 15:05 UTC
### Summary

Hello!

We have come across an issue in our project where our QA team can reproduce an issue where `onRegionChange` is called after `onRegionChangeComplete`. This is something that they reproduce on iOS devices when they "flick" the map to change its region (i.e. releasing their finger from the screen and letting the momentum move the map before it comes to a stop).

The use case for our project is that moving the map will make an API request to load some information based on the region displayed on the map. `onRegionChangeComplete` is initiating this request. 
The user can keep moving the map to a different region while the request is in progress, so we would like to cancel any pending or ongoing requests if the map moves. `onRegionChange` is used to cancel the request. 

The expectation was that `onRegionChangeComplete` would be the last event called. But when this issue occurs, the API pending/ongoing API request is cancelled, and we don't have anything in place to initiate a new one.

### Reproducible sample code

```TSX
import React from 'react'; 
import MapView from 'react-native-maps'; 

export default function App() { 
  return ( 
    <MapView 
      style={{flex: 1}} 
      initialRegion={{ latitude: 42, longitude: 30, latitudeDelta: 1, longitudeDelta: 1 }}
      onRegionChange={() => console.log('onRegionChange called')}
      onRegionChangeComplete={() => console.log('onRegionChangeComplete called')}
    /> 
  ); 
}
```

### Steps to reproduce

"Flick" the map (i.e. a quick swipe and let momentum carry the map movement)
Note that this doesn't happen every time either, and I have found it hard for myself to reproduce it too.

Here are some examples from logs that I received after the issue has been reproduced:
```
 LOG  onRegionChange called
 LOG  onRegionChange called
 LOG  onRegionChange called
 LOG  onRegionChange called
 LOG  onRegionChange called
 LOG  onRegionChange called
 LOG  onRegionChange called
 LOG  onRegionChange called
 LOG  onRegionChange called
 LOG  onRegionChange called
 LOG  onRegionChange called
 LOG  onRegionChange called
 LOG  onRegionChange called
 LOG  onRegionChange called
 LOG  onRegionChange called
 LOG  onRegionChange called
 LOG  onRegionChange called
 LOG  onRegionChange called
 LOG  onRegionChange called
 LOG  onRegionChange called
 LOG  onRegionChange called
 LOG  onRegionChange called
 LOG  onRegionChange called
 LOG  onRegionChange called
 LOG  onRegionChange called
 LOG  onRegionChange called
 LOG  onRegionChange called
 LOG  onRegionChange called
 LOG  onRegionChange called
 LOG  onRegionChange called
 LOG  onRegionChange called
 LOG  onRegionChange called
 LOG  onRegionChange called
 LOG  onRegionChange called
 LOG  onRegionChange called
 LOG  onRegionChange called
 LOG  onRegionChange called
 LOG  onRegionChange called
 LOG  onRegionChange called
 LOG  onRegionChange called
 LOG  onRegionChange called
 LOG  onRegionChange called
 LOG  onRegionChange called
 LOG  onRegionChange called
 LOG  onRegionChange called
 LOG  onRegionChange called
 LOG  onRegionChangeComplete called
 LOG  onRegionChange called
```

### Expected result

`onRegionChangeComplete` should be the last event called.

### Actual result

`onRegionChange ` is called after `onRegionChangeComplete`.

### React Native Maps Version

1.15.6

### What platforms are you seeing the problem on?

iOS (Google Maps)

### React Native Version

0.74.3

### What version of Expo are you using?

Not using Expo

### Device(s)

iPhone 13 (17.6.1), iPhone 14 Pro (17.4.1), iPad (17.3.1)

### Additional information

A question I have for the maintainers of `react-native-maps`: is there a reason why `mapView:willMove` (iOS) and  `onCameraMoveStarted` (Android) do not have events? And is that something you and others would be open to having in the future? I don't mind creating a pull request to include the event, but don't want to go through it if there's a reason why it hasn't been included yet.

I would also like to ask if anyone else has a similar use case in their projects, and have a different way of handling multiple API requests while moving the map?

**Comment by chhornponleu** [comment] 2024-08-20 09:26
Add this prop to MapView shall fix the issue
```
<MapView paddingAdjustmentBehavior="never" .../>
```

**Comment by lxr-mwhite** [comment] 2024-08-20 20:23
> Add this prop to MapView shall fix the issue
> 
> ```
> <MapView paddingAdjustmentBehavior="never" .../>
> ```

Thank you for the suggestion. After having our QA team re-test the bug with this change, they found they could still reproduce the issue. The logs appear to be the same as the ones from my original post.

**Comment by lxr-mwhite** [comment] 2024-08-20 20:24
I have created #5144 which has been found to resolve the issue for our app's specific use case. 
I know it does not technically solve the underlying issue but it is the kind of callback we need for our use case.

**Comment by sentientmachin3** [comment] 2024-08-28 14:16
I think I just met the same issue, I'll take a look at the `paddingAdjustmentBehavior` thing.

**Comment by sentientmachin3** [comment] 2024-08-28 15:30
`paddingAdjustmentBehavior` does not solve the issue. 
After the issue occurs the map is not responding at all, `onRegionChange` and `onRegionChangeComplete` are not called anymore, seems like the whole map froze in its last state.

Moreover, I'm not using google maps but Apple Maps. I'm using the same version of the library as @lxr-mwhite (1.15.6), on react native 0.74.1.

**Comment by lxr-mwhite** [comment] 2024-08-28 16:07
@sentientmachin3 The issue was only on iOS for us, and our app uses Google Maps. We did not run into the issue where the events are no longer called after the issue occurred once.

**Comment by salah-ghanim** [comment] 2024-11-09 20:41
@lxr-mwhite no, there is no reason why things are missing , often simply there was no need for them or never requested

as for the described issue , I have been testing for 10 minutes on an iphone 12 and I couldn't reproduce once.

I would close this for now (please provide a video if you want to 

also I have reviewed the native code and events propagation and I can't see how such a bug would happen.

specifically, see in the MapView.tsx code:

 ```
 private _onChange({nativeEvent}: ChangeEvent) {
    const isGesture = nativeEvent.isGesture;
    const details = {isGesture};

    if (nativeEvent.continuous) {
      if (this.props.onRegionChange) {
        this.props.onRegionChange(nativeEvent.region, details);
      }
    } else if (this.props.onRegionChangeComplete) {
      this.props.onRegionChangeComplete(nativeEvent.region, details);
    }
  }
```

so if you see if the nativeEvent.continuous is false then completed is sent

and you can see in the native code: AirMapManager.m

```
- (void)mapView:(AIRMap *)mapView regionDidChangeAnimated:(__unused BOOL)animated
{
    // Don't send region did change events until map has
    // started rendering, as these won't represent the final location
    if(mapView.hasStartedRendering){
        [self _regionChanged:mapView];
    }

    if (mapView.legacyZoomConstraintsEnabled == YES) {
        [self applyLegacyZoomConstrains:mapView];
    }

    // Don't send region did change events until map has
    // started rendering, as these won't represent the final location
    if (mapView.hasStartedRendering) {
        [self _emitRegionChangeEvent:mapView continuous:NO];
    };

    mapView.pendingCenter = mapView.region.center;
    mapView.pendingSpan = mapView.region.span;
}

```

the continuous = NO is sent only as a result of regionDidChangeAnimated from the MapKit, which means change has finished / no new callbacks with new region.

**Closed by salah-ghanim** 2024-11-09 20:41 UTC
Labels: bug
