### ISSUE TITLE
The target has transitive dependencies that include static binaries

### ISSUE THREAD

**Issue by dheerajb** [react-native-maps/react-native-maps#3838] opened 2021-06-08 15:39 UTC
# Bug report

## Summary

Maps is not building for iOS with SFLoginPods also included

## Environment info

      react-native: 0.63.4
      react: 16.13.1
      react-native-maps: 0.28.0

  
    Target Platform: eg: iOS - 13 Simulator/iPhone 12 using Google Maps

`react-native info` output:
System:
    OS: macOS 11.3.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 353.87 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.15.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7322048
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: 15.0.2 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

```bash
      react-native: 0.63.4
      react: 16.13.1
      react-native-maps: 0.28.0
```

## Steps to reproduce

1. we have Salesforce mobile sdk dependency included in package.json as 
  "sdkDependencies": {
        "SalesforceMobileSDK-Android": "https://github.com/forcedotcom/SalesforceMobileSDK-Android.git#v9.0.0",
        "SalesforceMobileSDK-iOS": "https://github.com/forcedotcom/SalesforceMobileSDK-iOS.git#v9.0.0"
    }
2. Pod install 
3.  While building for iOS vis Xcode we run into below error
4. [!] The 'Pods-SFLoginRN' target has transitive dependencies that include statically linked binaries: (/Users/tavant/Documents/ABC/sloginrn/SFLoginRN/ios/Pods/GoogleMaps/Base/Frameworks/GoogleMapsBase.framework, /Users/tavant/Documents/ABC/sloginrn/SFLoginRN/ios/Pods/GoogleMaps/Maps/Frameworks/GoogleMaps.framework, and /Users/tavant/Documents/ABC/sloginrn/SFLoginRN/ios/Pods/GoogleMaps/Maps/Frameworks/GoogleMapsCore.framework)

**Comment by dheerajb** [comment] 2021-06-09 04:52
When changed provider to Apple it works. But we are looking for using Google Maps.

**Comment by Simon-TechForm** [comment] 2022-03-13 17:27
I'm going to close this for now, as I'm not really sure anyone on here will be able to help. If you believe that this is still relevant and caused by react-native-maps, please feel free to open a new issue. I hope you worked it out :)

**Closed by Simon-TechForm** 2022-03-13 17:27 UTC
Labels: bug
