### ISSUE TITLE
MarkerAnimated is flickering on IOS

### ISSUE THREAD

**Issue by chanphiromsok** [react-native-maps/react-native-maps#4371] opened 2022-08-05 10:53 UTC
### Summary

Current behavior MarkerAnimated is flickering on IOS ```provider={PROVIDER_GOOGLE}``` when I use with new AnimateRegion when I call ```
                coordinate
                    .timing({ ...newCoordinate, useNativeDriver: false, duration: 1000 })
                    .start();
            ```
the current problem comes from a duration 1000
when set  ```useNativeDriver``` to ```true``` also get crashes in IOS

### Reproducible sample code

```TSX
import React from 'react';
import { StyleSheet, View, Text, Dimensions, TouchableOpacity, Platform } from 'react-native';
import MapView, {
    Marker,
    AnimatedRegion,
    MapMarker,
    PROVIDER_GOOGLE,
} from 'react-native-maps';

const screen = Dimensions.get('window');
const ASPECT_RATIO = screen.width / screen.height;
const LATITUDE = 37.78825;
const LONGITUDE = -122.4324;
const LATITUDE_DELTA = 0.0922;
const LONGITUDE_DELTA = LATITUDE_DELTA * ASPECT_RATIO;

class AnimatedMarkers extends React.Component<any, any> {
    marker: MapMarker;
    ref: MapView;
    constructor(props: any) {
        super(props);

        this.state = {
            coordinate: new AnimatedRegion({
                latitude: LATITUDE,
                longitude: LONGITUDE
            })
        };
    }

    animate() {
        const { coordinate } = this.state;
        const newCoordinate = {
            latitude: LATITUDE + (Math.random() - 0.5) * (LATITUDE_DELTA / 2),
            longitude: LONGITUDE + (Math.random() - 0.5) * (LONGITUDE_DELTA / 2)
        };
            this.ref.getCamera().then(() => {
                coordinate
                    .timing({ ...newCoordinate, useNativeDriver: false, duration: 0 })
                    .start();
            });
        
    }

    render() {
        return (
            <View style={ ...StyleSheet.absoluteFillObject,
        justifyContent: 'flex-end',
        alignItems: 'center'}>
                <MapView
                    ref={ref => {
                        this.ref = ref;
                    }}
                    provider={PROVIDER_GOOGLE}
                    style={styles.map}
                    initialRegion={{
                        latitude: LATITUDE,
                        longitude: LONGITUDE,
                        latitudeDelta: LATITUDE_DELTA,
                        longitudeDelta: LONGITUDE_DELTA
                    }}
                >
                    <Marker.Animated
                        ref={(marker: any) => {
                            this.marker = marker;
                        }}
                        coordinate={this.state.coordinate}
                    />
                </MapView>
                <View style={{ flexDirection: 'row',
                                         marginVertical: 20,
                                         backgroundColor: 'transparent'}>
                    <TouchableOpacity
                        onPress={() => this.animate()}
                        style={ width: 80,
                                     alignItems: 'center',
                                    marginHorizontal: 10, flex: 1,
                                    backgroundColor: 'rgba(255,255,255,0.7)',
                                    paddingHorizontal: 18,
                                    paddingVertical: 12,
                                    borderRadius: 20}>
                        <Text>Animate</Text>
                    </TouchableOpacity>
                </View>
            </View>
        );
    }
}
```

### Steps to reproduce

After Map initialize I click on the Animate button then it got flickering while the marker moving

### Expected result

Expect the marker to move smoothly with the ```duration=1000```  and  ```useNativeDriver=true``` 

###  Flickering
``` coordinate.timing({ ...newCoordinate, useNativeDriver: false, duration: 1000}).start();```

https://user-images.githubusercontent.com/65760336/183062656-9a9384a1-a408-435a-84d2-0fd28173e22d.MP4

### No Flickering
``` coordinate.timing({ ...newCoordinate, useNativeDriver: false, duration: 1000}).start();```

https://user-images.githubusercontent.com/65760336/183062210-0ba085d0-5d5c-4d36-b56e-c9cf79df088e.MP4

### React Native Maps Version

1.1.0

### What platforms are you seeing the problem on?

iOS (Google Maps)

### React Native Version

0.65.1

### What version of Expo are you using?

Not using Expo

### Device(s)

13 Pro

**Comment by Simon-TechForm** [comment] 2022-08-05 21:54
Hi @chanphiromsok 👋 

Can I have you trim away as much as possible from your reproducible sample code and ensure that it is runnable as is? There seem to be at least a few props that is unrelated to the problem, as well as imports that can't be resolved without additional code :)

**Comment by chanphiromsok** [comment] 2022-08-07 02:04
> Hi @chanphiromsok 👋
> 
> Can I have you trim away as much as possible from your reproducible sample code and ensure that it is runnable as is? There seem to be at least a few props that is unrelated to the problem, as well as imports that can't be resolved without additional code :)

 Hello, the code is updated.
 My goal is I want to use ```coordinate.timing({ ...newCoordinate, useNativeDriver: false, duration: 1000}).start();``` in the ```animate``` function without any flick marker

**Comment by spsaucier** [comment] 2022-09-05 13:50
I'm seeing markers flickering when not animated at all - very strange behavior.

**Comment by estmau** [comment] 2022-09-09 21:59
Same issue in ios 15.6.1, react native 0.69.5, react native maps 1.3.1, iphone 12 pro and iphone 8. My mark and own marks on the map are flickering.

**Comment by danidaryaweesh** [comment] 2022-10-18 12:53
Update on this issue: the issue disappears for me if I don't call enableLatestRenderer();

**Comment by spsaucier** [comment] 2022-10-18 13:27
We are not using enableLatestRenderer in our code but still see the issue.

**Comment by MoronovArt** [comment] 2022-10-24 04:22
same issue

**Comment by almandoro** [comment] 2022-10-24 09:49
I'm using AnimatedMarker and it's being updated on location change.
I think it could be related to iOS 16.

On my end works fine on Android and iOS emulators.
Launched on real device iPhone XR with iOS 15 - still okay
For iPhone 14 Pro running iOS 16 it's flickering.

This behavior is non acceptable for prod-ready apps 😞

**Comment by estmau** [comment] 2022-11-07 16:41
.

**Comment by aatdevelopment** [comment] 2022-11-25 21:07
Hello, I have the same issue, on iOS.  Physical device and simulators with ios 15.2 and ios 16.0.3

https://user-images.githubusercontent.com/98107503/204054862-14eba441-7d5d-4864-94e9-ec069dd9e4ee.mov

Works fine in android.

    "react-native": "0.70.5",
    "react-native-maps": "1.3.2",
    "react-native-reanimated": "2.12.0",

`import MapView, { Marker, AnimatedRegion, MarkerAnimated } from 'react-native-maps';
import React, { useRef, useEffect, useState } from 'react';
import { IProps } from './types';
import { Platform } from 'react-native';
// import Animated from 'react-native-reanimated';

export default (props: IProps) => {
    // const isFirstRender = useRef(true);
    // const fadeAnim = useRef(new Animated.Value(0)).current;
    const [marker, setMarker] = useState(null);
    var latitude = props.latLng.latitude;
    var longitude = props.latLng.longitude;
    const [coordinate, setCoordinate] = useState(
        new AnimatedRegion({
            latitude,
            longitude,
            latitudeDelta: 0.03,
            longitudeDelta: 0.015,
        }),
    );
    useEffect(() => {
        animateMarker();
    }, [props.latLng]);
    const animateMarker = () => {
        const newCoordinate = {
            latitude: props.latLng.latitude,
            longitude: props.latLng.longitude,
            latitudeDelta: 0.03,
            longitudeDelta: 0.015,
        };

        if (Platform.OS === 'android') {
            if (marker) {
                // @ts-ignore
                marker.animateMarkerToCoordinate(newCoordinate, 5000);
            }
        } else {
            // @ts-ignore
            coordinate.timing(newCoordinate).start();
        }
    };
    return (
        <Marker.Animated ref={(marker: any) => {
            setMarker(marker);
        }}
            zIndex={props.zIndex}
            // @ts-ignore
            coordinate={coordinate} onPress={props.onPress} anchor={{ x: 0.5, y: 0.5 }}>
            {props.children}
        </Marker.Animated>
    );
}`


plus, I get this when debugging the animation on iOS:

<img width="727" alt="image" src="https://user-images.githubusercontent.com/98107503/204055404-9e4bc770-37b1-4391-9aad-5b69a44b54c7.png">

**Comment by chanphiromsok** [comment] 2022-12-02 02:42
> I'm using AnimatedMarker and it's being updated on location change. I think it could be related to iOS 16.
> 
> On my end works fine on Android and iOS emulators. Launched on real device iPhone XR with iOS 15 - still okay For iPhone 14 Pro running iOS 16 it's flickering.
> 
> This behavior is non acceptable for prod-ready apps 😞

I run on many different devices but still got the same Iphone 8Plus Iphone 7 Iphone 7plus 13 pro but still got this issue

**Comment by chanphiromsok** [comment] 2022-12-02 02:43
one more thing animateMarkerToCoordinate not working in release mode

**Comment by hlspablo** [comment] 2022-12-07 18:16
Same problem here, @Simon-TechForm It's possible to use reanimated 2 to control the position of a market in iOS and Android? To avoid at all AnimateToCoordinates and Animated Region?

**Comment by AnatoleLucet** [comment] 2022-12-09 10:50
I had to reimplement `AnimatedRegion` with reanimated to get smooth animations on Android and iOS.
Here's the hook I ended up with:
```ts
import { useMemo } from 'react';
import { MapMarker, MapMarkerProps } from 'react-native-maps';
import Animated, {
  Easing,
  EasingFn,
  EasingFunctionFactory,
  useAnimatedProps,
  useSharedValue,
  withTiming,
} from 'react-native-reanimated';

interface LatLng {
  latitude: number;
  longitude: number;
  longitudeDelta?: number;
  latitudeDelta?: number;
}

interface AnimateOptions extends LatLng {
  duration?: number;
  easing?: EasingFn | EasingFunctionFactory;
}

export const useAnimatedRegion = (location: Partial<LatLng> = {}) => {
  const latitute = useSharedValue(location.latitude);
  const longitude = useSharedValue(location.longitude);
  const latitudeDelta = useSharedValue(location.latitudeDelta);
  const longitudeDelta = useSharedValue(location.longitudeDelta);

  const animatedProps = useAnimatedProps(() => ({
    coordinate: {
      latitude: latitute.value ?? 0,
      longitude: longitude.value ?? 0,
      latitudeDelta: latitudeDelta.value ?? 0,
      longitudeDelta: longitudeDelta.value ?? 0,
    },
  }));

  const animate = useMemo(
    () => (options: AnimateOptions) => {
      const { duration = 500, easing = Easing.inOut(Easing.ease) } = options;

      const animateValue = (
        value: Animated.SharedValue<number | undefined>,
        toValue?: number,
      ) => {
        if (!toValue) {
          return;
        }

        value.value = withTiming(toValue, {
          duration,
          easing,
        });
      };

      animateValue(latitute, options.latitude);
      animateValue(longitude, options.longitude);
      animateValue(latitudeDelta, options.latitudeDelta);
      animateValue(longitudeDelta, options.longitudeDelta);
    },
    [latitute, longitude, latitudeDelta, longitudeDelta],
  );

  return {
    props: animatedProps,
    animate,
  };
};

type MarkerProps = Omit<MapMarkerProps, 'coordinate'> & {
  coordinate?: MapMarkerProps['coordinate'];
};

export const AnimatedMarker = Animated.createAnimatedComponent(
  MapMarker as React.ComponentClass<MarkerProps>,
);
```

Usage:
```ts
import { Easing } from "react-native-reanimated"

import { AnimatedMarker, useAnimatedRegion } from 'hooks/useAnimatedRegion';

export const MyMarker: React.FC = () => {
  const animatedRegion = useAnimatedRegion(location);

  useEffect(() => {
    // works well on both Android and iOS
    animatedRegion.animate({
      latitude: ...,
      longitude: ...,
      duration: 1000,
      easing: Easing.linear
    });
  }, [])

  return (
    <AnimatedMarker
      ...
      animatedProps={animatedRegion.props}
    >
      ...
    </AnimatedMarker>
  );
};
```

The `useAnimatedRegion` is pretty much the same implementation as [`AnimatedRegion`](https://github.com/react-native-maps/react-native-maps/blob/master/src/AnimatedRegion.ts) apart from the fact that it uses Reanimated instead of RN's built-in `Animated` API. Reanimated V2 runs animations on the native UI thread by default ("worklets" as they call it), which makes it way more performant than RN's `Animated` API.

The only downside is, you can not use any kind of pure js function for `easing`. You need to use Reanimated's `Easing` constants, or define your easing functions to [run as a worklet](https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/worklets/).

I did try to replace `Animated` by Reanimated on the [`AnimatedRegion`](https://github.com/react-native-maps/react-native-maps/blob/master/src/AnimatedRegion.ts) class to open a PR, but couldn't get it to work (`AnimatedRegion` currently seems to rely on a few hacks to work properly :confused: ).

**Comment by hlspablo** [comment] 2022-12-09 18:44
> I had to reimplement `AnimatedRegion` with reanimated to get smooth animations on Android and iOS. Here's the hook I ended up with:
> 
> ```ts
> import { useMemo } from 'react';
> import { MapMarker, MapMarkerProps } from 'react-native-maps';
> import Animated, {
>   Easing,
>   EasingFn,
>   EasingFunctionFactory,
>   useAnimatedProps,
>   useSharedValue,
>   withTiming,
> } from 'react-native-reanimated';
> 
> interface LatLng {
>   latitude: number;
>   longitude: number;
>   longitudeDelta?: number;
>   latitudeDelta?: number;
> }
> 
> interface AnimateOptions extends LatLng {
>   duration?: number;
>   easing?: EasingFn | EasingFunctionFactory;
> }
> 
> export const useAnimatedRegion = (location: Partial<LatLng> = {}) => {
>   const latitute = useSharedValue(location.latitude);
>   const longitude = useSharedValue(location.longitude);
>   const latitudeDelta = useSharedValue(location.latitudeDelta);
>   const longitudeDelta = useSharedValue(location.longitudeDelta);
> 
>   const animatedProps = useAnimatedProps(() => ({
>     coordinate: {
>       latitude: latitute.value ?? 0,
>       longitude: longitude.value ?? 0,
>       latitudeDelta: latitudeDelta.value ?? 0,
>       longitudeDelta: longitudeDelta.value ?? 0,
>     },
>   }));
> 
>   const animate = useMemo(
>     () => (options: AnimateOptions) => {
>       const { duration = 500, easing = Easing.inOut(Easing.ease) } = options;
> 
>       const animateValue = (
>         value: Animated.SharedValue<number | undefined>,
>         toValue?: number,
>       ) => {
>         if (!toValue) {
>           return;
>         }
> 
>         value.value = withTiming(toValue, {
>           duration,
>           easing,
>         });
>       };
> 
>       animateValue(latitute, options.latitude);
>       animateValue(longitude, options.longitude);
>       animateValue(latitudeDelta, options.latitudeDelta);
>       animateValue(longitudeDelta, options.longitudeDelta);
>     },
>     [latitute, longitude, latitudeDelta, longitudeDelta],
>   );
> 
>   return {
>     props: animatedProps,
>     animate,
>   };
> };
> 
> type MarkerProps = Omit<MapMarkerProps, 'coordinate'> & {
>   coordinate?: MapMarkerProps['coordinate'];
> };
> 
> export const AnimatedMarker = Animated.createAnimatedComponent(
>   MapMarker as React.ComponentClass<MarkerProps>,
> );
> ```
> 
> Usage:
> 
> ```ts
> import { Easing } from "react-native-reanimated"
> 
> import { AnimatedMarker, useAnimatedRegion } from 'hooks/useAnimatedRegion';
> 
> export const MyMarker: React.FC = () => {
>   const animatedRegion = useAnimatedRegion(defaultLocation);
> 
>   useEffect(() => {
>     // works well on both Android and iOS
>     animatedRegion.animate({
>       latitude: ...,
>       longitude: ...,
>       duration: 1000,
>       easing: Easing.linear
>     });
>   }, [])
> 
>   return (
>     <AnimatedMarker
>       ...
>       animatedProps={animatedRegion.props}
>     >
>       ...
>     </AnimatedMarker>
>   );
> };
> ```
> 
> The `useAnimatedRegion` is pretty much the same implementation as [`AnimatedRegion`](https://github.com/react-native-maps/react-native-maps/blob/master/src/AnimatedRegion.ts) apart from the fact that it uses Reanimated instead of RN's built-in `Animated` API. Reanimated V2 runs animations on the native UI thread by default ("worklets" as they call it), which makes it way more performant than RN's `Animated` API.
> 
> The only downside is, you can not use any kind of pure js function for `easing`. You need to use Reanimated's `Easing` constants, or define your easing functions to [run as a worklet](https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/worklets/).
> 
> I did try to replace `Animated` by Reanimated on the [`AnimatedRegion`](https://github.com/react-native-maps/react-native-maps/blob/master/src/AnimatedRegion.ts) class to open a PR, but couldn't get it to work (`AnimatedRegion` currently seems to rely on a few hacks to work properly 😕 ).

Thanks for share this

**Comment by hlspablo** [comment] 2022-12-09 18:44
@AnatoleLucet, Thanks for share this.

**Comment by chanphiromsok** [comment] 2022-12-29 05:25
I think the issue can closed now

**Comment by danidaryaweesh** [comment] 2022-12-29 12:38
@chanphiromsok What is the solution for the flickering markers on iOS? apologies if I'm missing something here, but I don't see a suggested solution anywhere. I would appreciate any feedback here :)

**Comment by chanphiromsok** [comment] 2023-01-09 09:54
I used the code from @AnatoleLucet from his comment above

**Comment by chanphiromsok** [comment] 2023-01-09 09:56
> @chanphiromsok What is the solution for the flickering markers on iOS? apologies if I'm missing something here, but I don't see a suggested solution that actually works anywhere. I would appreciate any feedback here :)

I use the code from his comment above @AnatoleLucet

**Comment by AnatoleLucet** [comment] 2023-01-09 10:52
@chanphiromsok While my solution provides an alternative that *can* be used to fix the original issue, it does not fix the built-in `AnimatedRegion`.
I think it would be more appropriate to let this issue open until the maintainers decide otherwise (maybe by fixing the current `AnimatedRegion` and/or including my hook in the lib), or close the issue as a "won't fix".

**Comment by chanphiromsok** [comment] 2023-01-12 06:35
Thanks for suggestion

**Comment by spsaucier** [comment] 2023-03-24 18:44
This seems to have resolved when I use `tracksViewChanges={false}` on my Markers.

**Comment by chanphiromsok** [comment] 2023-03-27 04:07
> This seems to have resolved when I use `tracksViewChanges={false}` on my Markers.

```tracksViewChanges``` is used to reduce CPU usage when you have many markers on a map 
after the Marker display on MapView, we must set it to false otherwise phone will heat and freeze

**Comment by germanmb23** [comment] 2023-03-27 16:52
> 

Thanks for the solution! How can I set anchor, icon and other props to the Marker component?

**Comment by cornejobarraza** [comment] 2023-06-18 02:07
@AnatoleLucet 6 months later and your solution helped me tremendously, thank you so much

**Comment by sspread** [comment] 2023-11-30 07:44
Does this AnatoleLucet solution work with react-native-reanimated v3? Marker expects props lat/long nested under `coordinate` and I can't get it to work.

**Comment by cornejobarraza** [comment] 2023-11-30 18:26
> Does this AnatoleLucet solution work with react-native-reanimated v3? Marker expects props lat/long nested under `coordinate` and I can't get it to work.

I checked the migration docs and it states all code written in Reanimated v2 API works in 3.x without any changes. I used his solution with v2 and it works really well, what specifically is the issue you are facing?

**Comment by cornejobarraza** [comment] 2023-11-30 22:00
> @cornejobarraza Marker doesn't animate (no errors). Setup is otherwise the same. react-native-maps v1.8.0. I can confirm the animated values are triggered by logging the values in the useAnimatedProps callback.
> 
> Related? [software-mansion/react-native-reanimated#2257](https://github.com/software-mansion/react-native-reanimated/pull/2257) [software-mansion/react-native-reanimated#2767](https://github.com/software-mansion/react-native-reanimated/issues/2767)
> 
> EDIT: Marker shows according the initial values past to useSharedValue, but doesn't reflect updates, even if value set without timing animation.

@sspread this is how I implemented a custom marker component using the code AnatoleLucet provided. I had to do some changes since I'm working with TypeScript, I hope this helps in some way:

```tsx
import { AnimatedMarker, useAnimatedRegion } from "hooks/useAnimatedRegion";
import { useEffect } from "react";
import { Image } from "react-native";
import { LatLng } from "react-native-maps";

export const MyMarker: React.FC = (coords: LatLng) => {
  const defaultCoords = { latitude: -48.12485, longitude: -22.08061 };
  const animatedRegion = useAnimatedRegion(defaultCoords);

  useEffect(() => {
    // works well on both Android and iOS
    animatedRegion.animate({ ...coords });
  }, [coords]);

  return (
    <AnimatedMarker animatedProps={animatedRegion.props}>
      <Image
        style={{
          height: 48,
          width: 48,
        }}
        source={require("@assets/images/marker.png")}
        resizeMode="contain"
      />
    </AnimatedMarker>
  );
};
```

**Comment by sspread** [comment] 2023-11-30 23:22
@cornejobarraza Yea there's nothing different from what i have there. Its got to be something that changed in reanimated v3.

**Comment by chanphiromsok** [comment] 2023-12-01 00:55
> @cornejobarraza Yea there's nothing different from what i have there. Its got to be something that changed in reanimated v3. 

reanimated v3 is work well please check code again We are using with google map

**Comment by sspread** [comment] 2023-12-09 21:32
I was using apple maps. confirmed it does work on google maps (iOS)

**Comment by salah-ghanim** [comment] 2023-12-10 14:24
I'm wondering if this really should be part of the library, I was just reviewing google maps docs for iOS / Android SDK and they clearly mention that the latlong values are animatable:

https://developers.google.com/maps/documentation/android-sdk/reference/com/google/android/libraries/maps/model/LatLng

iOS
https://github.com/colibridigital/maiamall-luxury/blob/18625c523eca1572d3fec6c725960bd95d3abd8f/GoogleMaps.framework/Versions/A/Headers/GMSMarker.h#L37


which means theoretically updating the coordinates through your favourite lib of animation (reanimated) should work well.

I don't see why this library need to implement animation when, based on @AnatoleLucet's answer it seems like it would work perfectly without using AnimatedRegion.

**Comment by SergioAN007** [comment] 2023-12-18 14:20
> Does this AnatoleLucet solution work with react-native-reanimated v3? Marker expects props lat/long nested under `coordinate` and I can't get it to work.

Thid solution works perfect in Android and iOS.
 But if you want to add nested animation, like fadein(out), rotation, else, in iOS need set marker prop trackviewchanges=true and add Animated.View.  something like this.  In android Animated.View not needed.
`<AnimatedMarker
      ref={Ref}
      key={"Marker"}
      identifier={"Marker"}
      flat={true}
      tracksViewChanges={trackViewChanges}
      anchor={{ x: 0.5, y: 0.5 }}
      animatedProps={animatedRegion.props}>
      <Animated.View
        key={"key"}
        style={[{
          alignItems: "center",
          zIndex: 1002,
        }, reanimatedStyleFade]}>
        <MarkerImage
          key={"carIconKey"}
		  />
      </Animated.View>
    </AnimatedMarker>
`

**Comment by owaisnizam** [comment] 2023-12-19 15:07
I am trying to use @AnatoleLucet solution with JS
I am even using google maps and latest
Reanimated and react native maps. 
but the marker draws at initial location and doesn't move. 
I do not have issue with my flickering but the issue I have the my animation only takes default [duration](https://github.com/react-native-maps/react-native-maps/issues/2816) of 500ms instead of what I am passing. 
Can anyone help please?
` coords
        .timing({
          ...coordinates,
          duration: 5000,
        })
        .start();`
where coords is AnimatedRegion

**Comment by chanphiromsok** [comment] 2023-12-20 00:53
> I am trying to use @AnatoleLucet solution with JS
> 
> I am even using google maps and latest
> 
> Reanimated and react native maps. 
> 
> but the marker draws at initial location and doesn't move. 
> 
> I do not have issue with my flickering but the issue I have the my animation only takes default [duration](https://github.com/react-native-maps/react-native-maps/issues/2816) of 500ms instead of what I am passing. 
> 
> Can anyone help please?
> 
> ` coords
> 
>         .timing({
> 
>           ...coordinates,
> 
>           duration: 5000,
> 
>         })
> 
>         .start();`
> 
> where coords is AnimatedRegion

make sure that location is available before render marker

**Comment by owaisnizam** [comment] 2023-12-20 09:36
Yes 
I do have it but still it does not.

**Comment by owaisnizam** [comment] 2023-12-20 13:53
Hi I was able to fix the duration thing but unable to get the marker moving on maps. I am using google maps on ios @AnatoleLucet @sspread

**Comment by SergioAN007** [comment] 2023-12-20 18:42
> Hi I was able to fix the duration thing but unable to get the marker moving on maps. I am using google maps on ios @AnatoleLucet @sspread

If you are using multiple marker animations in iOS, ex AnimatedRegion with fade or\with rotation, need update [custom marker component ](https://github.com/react-native-maps/react-native-maps/issues/4371#issuecomment-1834630083) like this:

`   <AnimatedMarker
      ref={marker}
      key={"km"}
      identifier={"im"}
      flat={true}
      tracksViewChanges={trackViewChanges}
      anchor={{ x: 0.5, y: 0.5 }}
      animatedProps={animatedRegion.props}>
      <Animated.View
        key={"kmv"}
        style={ animatedStyleFade, animatedStyleRotation }>
		<Image
			style={{
			  height: 48,
			  width: 48,
			}}
			source={require("@assets/images/marker.png")}
			resizeMode="contain"
		/>
      </Animated.View>`

**Comment by sspread** [comment] 2023-12-20 18:49
@owaisnizam Your animation syntax doesn't look like react-native-reanimated, rather react native Animated API

**Comment by owaisnizam** [comment] 2023-12-21 13:40
@sspread my syntax was fine but thanks to your comment I checked that my Easing was imported from react-native and not from reanimated. 
This fixed my problem. 
Much Appreciated. 
Shout out for @AnatoleLucet  for a beautiful piece of code

**Comment by sspread** [comment] 2023-12-22 04:29
@salah-ghanim Perhaps the lib implementation is needed because reanimated doesn't work on apple maps? I would like it to because I get minor flickering with apple maps too. And using native driver crashes. Would love to hear if someone has a solution for apple maps.

**Comment by onizam95** [comment] 2023-12-28 13:41
Hi @AnatoleLucet 
Is there any way that I can get a callback which indicates that the animation is completed with a finished flag true or false. 
like in 'timing.start({finished} =>{})'

**Comment by cornejobarraza** [comment] 2024-01-05 06:01
If anyone is struggling with their `AnimatedMarker` freezing and not animating properly after many consecutive location changes, here's what I added to AnatoleLucet's code. I'm only using `LatLng` so I removed the other shared values:

```tsx
import { cancelAnimation } from "react-native-reanimated";

const animate = useCallback(
  (options: AnimateOptions) => {
    const { duration = 500, easing = Easing.inOut(Easing.ease) } = options;

    const animateValue = (
      value: Animated.SharedValue<number | undefined>,
      toValue?: number,
    ) => {
      if (!toValue) {
        return;
      }

      value.value = withTiming(toValue, {
        duration,
        easing,
      });
    };

    animateValue(latitute, options.latitude);
    animateValue(longitude, options.longitude);

    // Add this cleanup
    return () => {
      cancelAnimation(latitude);
      cancelAnimation(longitude);
    }
  },
  [latitute, longitude],
);
```

This Medium article by chrischuck35 guided me to this, read more here:
https://medium.com/@chrischuck35/why-are-my-react-native-animations-freezing-62f38526d17d

This only started affecting me after upgrading to Expo SDK 49 for some reason. It might have been the `react-native-reanimated` upgrade, or maybe I didn't test enough previously, who knows 😅

**Comment by salah-ghanim** [comment] 2024-02-20 10:21
I recently published the latest version of the library where in the examples a marker animation is done  using reanimated and it works smoothly compared to the previous implementation on iOS.

Can someone please test / confirm in their project so that finally this ticket can be closed ?

**Comment by sspread** [comment] 2024-02-20 14:45
@salah-ghanim Using the approach from the example in your merged code, reanimated is working, but now in addition to the occasional flicker, there's a constant blur. For my use, its worse now, for that reason. Interestingly, when I try to screen capture video, it doesn't pick up the blur. Something going on with frame rate, and the blur only happens when I have the map camera 'follow' the pin. 

Is the `runOnJS` and `setNativeProps` on the ref the only way to use it? `animatedProps` approach didn't work.

**Comment by salah-ghanim** [comment] 2024-02-21 20:40
@sspread thanks for your feedback, did you use some specific code to reproduce the issue with the high frame rate ?  or simply the example ?

In android you can simply use: getWindow().setPreferredRefreshRate(30f); // Request 30fps

to set the Frame rate for the app, I would recommend that you use this for now

https://developer.android.com/media/optimize/performance/frame-rate

regarding supporting a higher framerate I think we have two ways:
  1. move to the new arch, this should reduce the cost of serialisation of data between JS / Native
  2. implement Reanimated with native support (needs to be investigated).
  
  honestly I would close this issue given that the animation runs smooth at 30fps which is the best to expect from the current setup.

**Comment by sspread** [comment] 2024-02-21 20:47
@salah-ghanim I'm testing on iOS - 120fps is the default. I used your example code to produce the issue, but again, i'm also "following" the marker with the camera (setCamera). Unfortunately, the code improvements don't help me out specifically, but that doesn't mean this issue isn't resolved (I'm not OP).

**Closed** 2024-02-22 15:31 UTC
Labels: bug

**Comment by chanphiromsok** [comment] 2024-02-22 23:30
if you closed this please refer to the docs too

**Comment by salah-ghanim** [comment] 2024-02-23 12:26
@chanphiromsok do you want to share an updated doc by any chance ?

**Comment by chanphiromsok** [comment] 2024-02-23 14:22
> @chanphiromsok do you want to share an updated doc by any chance ?

tell user in marker document 
how to use reanimated that's it I'm willing to help
