### ISSUE TITLE
After moving map textinputs no longer respond to touch\

### ISSUE THREAD

**Issue by tgreco** [react-native-maps/react-native-maps#3817] opened 2021-05-09 16:52 UTC
# Bug report

## Summary

Drag the marker on the map, then try to press a button and it will not respond to the touch event.

## Environment info

`react-native info` output:
System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
    Memory: 1.69 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 15.0.1 - /usr/local/bin/node
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7199119
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  npmPackages:
    react: ^16.13.1 => 16.14.0 
    react-native: ^0.63.2 => 0.63.4

## Steps to reproduce

Drag marker and then try touching any button in the header (react navigation) and they will not respond to touch.

## Reproducible sample code

`
  import React, { Component } from 'react';
  import MapView, { Callout, Circle, Marker, PROVIDER_GOOGLE } from 'react-native-maps';
  import { KeyboardAwareScrollView } from 'react-native-keyboard-aware-scroll-view';
  
  export default class Map extends Component
  {
    _mapViewRef = null;
  
    constructor(props)
    {
      super(props);
      console.log('\tMap()');
      this._dataMgr = DataManager.GetInstance();
      this.state =
      {
      };
  
      this._mapViewRef = React.createRef();
    }
  
    render()
    {
      const locationData = 
      {
        mapLocation 
        {
          latitude: 36.7783,
          longitude: 119.4179,
          latitudeDelta: 0.0922,
          longitudeDelta: 0.0421,
        },
        alertLocation 
        {
          latitude: 36.7783,
          longitude: 119.4179,
          latitudeDelta: 0.0922,
          longitudeDelta: 0.0421,
        }
      };
      
      return (
      <KeyboardAvoidingView style={styles.container}>
        <KeyboardAwareScrollView
          contentContainerStyle={{flexGrow: 1}}
          keyboardShouldPersistTaps={'always'}
        >
  
          <View style={{height: '100%'}}>
            <MapView
              ref={this._mapViewRef}
              provider={PROVIDER_GOOGLE}
              onPress={(e) =>
              {
              }}
              onRegionChangeComplete={async(region, isGesture) =>
              {
                console.log('Map.onRegionChangeComplete()');
              }}
              region={(locationData && locationData.mapLocation) ? locationData.mapLocation :
              {
                latitude: this.props.geofenceArea.location.coordinates[1],
                longitude: this.props.geofenceArea.location.coordinates[0],
                latitudeDelta: 0.0922,
                longitudeDelta: 0.0421,
              }}
              showsUserLocation={true}
            >
              <Circle
                center={locationData.alertLocation}
                radius={500}
                onRegionChangeComplete={async(e) =>
                {
                  console.log('Circle.onRegionChangeComplete()');
                  return true;
                }}
                strokeWidth = { 5 }
                strokeColor = { '#1a66ff' }
                fillColor = { 'rgba(230,238,255,0.5)' }
              />
              <Marker
                draggable
                coordinate={locationData.alertLocation}
                onDragEnd={async(e) =>
                {
                  console.log('OnMarkerDragEnd()');
                  return true;
                }}
                pinColor={"green"}
              />
            </MapView>
  
        </KeyboardAwareScrollView>
      </KeyboardAvoidingView>
      );
    }
  }

`

Possible solution is using react-native-gesture-handler's TouchableOpacity but that is not a solution but rather a workaround.
This would only fix buttons and not text inputs.

**Comment by mikamations** [comment] 2021-06-17 15:37
I have the same issue. If you drag a marker nothing else on screen responds to touch/press events

**Comment by harrigee** [comment] 2021-06-18 06:04
We are also facing issues with TouchableOpacity and TextInputs.

**Comment by saransh-malik** [comment] 2021-08-19 19:21
This is happening to me as well, something blocks the touch events completely.

**Comment by yehyaumar** [comment] 2021-08-23 07:31
Same thing happening here as well. Any possible fix?

**Comment by liho00** [comment] 2021-09-15 16:51
HELP us dears, owner & collaborators, dont you face this issue haha, or u r using TouchableOpacity from react-native-gesture-handler package? instead of react-native hah

**Comment by steffenabel** [comment] 2021-11-17 10:30
Using `TouchableOpacity` from the `react-native-gesture-handler` package works for us. But beware if you are using absolute positioning then these Touchables don't work any more (the builtin Touchables from `react-native` work in that case). To use absolute positioning use a `View` around the Touchable and position the View absolutely. At least for us this works fine.

**Comment by navarrofracisco** [comment] 2022-02-16 06:34
How is this still not fixed? This seems like core/vital functionality for the "best" react native maps library available. How can we help fix this?

**Comment by edmsamuel** [comment] 2022-05-31 14:16
The problem persists

**Comment by vrgimael** [comment] 2022-06-05 18:00
This is really not stale.. it still happens and work arounds have to be pretty creative to circumvent this.

Using react-native-gesture-handler does seem to help, and also I noticed that when this glitch does happen, onPressOut is called immediately with onPressIn, allowing you to at least detect when it's glitched.

I hope this helps someone but really this shouldn't be an issue

**Comment by Simon-TechForm** [comment] 2022-07-22 22:07
I wanted to look into this, but I'm struggling to reproduce the issue. Since the code put forth by the author in this issue isn't runnable as is, I used the code provided in #4282.

If anyone is still able to reproduce this in `v1.1.0` could you please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by Simon-TechForm** [comment] 2022-08-11 20:27
I'm closing for now. If anyone is still experiencing this, please comment with an up to date reproducible example and I'll be happy to re-open :)

**Closed by Simon-TechForm** 2022-08-11 20:27 UTC
Labels: bug

**Comment by madahatter** [comment] 2022-09-09 14:57
I am still experiencing this problem.  There must be a solution out there somewhere?

My App doesn't have much else going on at the moment, it is honestly just a Map with a draggable marker and a Bottom Tab Navigator. The BottomTabBar Navigator from react-navigation is not responsive, neither is my Pressable on the map once I drag the default marker.

I've tried removing the Pressable altogether and tried map.current.animateToRegion to trick the map in believing it was moved.

Once you interact with the map after dropping the pin, everything works as intended.

Any feedback is much appreciated :)

`
                <View style={styles.container}>
                    <MapView
                        provider={PROVIDER_GOOGLE}
                        ref={map}
                        showsUserLocation={true}
                        style={{
                            width: Dimensions.get('window').width,
                            height: showBottomSheet ? Dimensions.get('window').height - 350 : Dimensions.get('window').height,
                        }}
                        initialRegion={{latitude: props.location.latitude, longitude: props.location.longitude, latitudeDelta: 0.005, longitudeDelta: 0.005}}
                    >
                    <Marker 
                        draggable
                        coordinate={parkingSpot}
                        onDragEnd={(e) => setDraggableSpot(e.nativeEvent.coordinate)}
                    />
                            <Pressable
                                style={{
                                    backgroundColor: "white",
                                    padding: 10,
                                    margin: 10,
                                    height: 65,
                                    width: 65,
                                    borderRadius: 9999,
                                    justifyContent: 'center',
                                    alignItems: 'center',
                                    position: 'absolute',
                                    top: '80%', 
                                    right: 10
                                }}
                                onPress={handleCenter}
                            >
                                <FontAwesome name="location-arrow" size={30} color="blue" />
                            </Pressable>
                    </MapView>`

**Comment by navarrofracisco** [comment] 2022-09-09 18:24
@madahatter yes this has been a pain in the A@#, you will find some very annoying/lacking features in this library. Anyways, you likely are encounterin problem because of <Pressable> you probably need to use: import { TouchableOpacity } from "react-native-gesture-handler";

Also why do you need a pressable element inside of the Marker? Isn't the marker draggable already?  Some reference code:

<View style={[styles.flexOne, {paddingTop: this.state.statusBarHeight}]}>
                {this.state.displayMapView ?
                <MapView
                    ref={(ref) => {
                        this.mapRef = ref;
                    }}
                    mapType={"satellite"}
                    provider="google"
                    zoomEnabled={true}
                    followsUserLocation={true}
                    showsUserLocation={true}
                    showsMyLocationButton={true}
                    camera={this.state.cameraOF}
                >
                    <Marker
                        draggable={true}
                        coordinate={{
                            latitude: Number(this.state.latitude),
                            longitude: Number(this.state.longitude),
                        }}
                        onDragEnd={(e) => {
                            this.needsReRender(e.nativeEvent.coordinate);
                        }}
                    >
                        <Image style={styles.pinDrop} source={require("../../src/assets/pin.png")} />
                    </Marker>
                </MapView>

**Comment by madahatter** [comment] 2022-09-09 19:36
Hey @navarrofracisco !  Thanks for the response!

I'm not even importing TouchableOpacity anywhere in my App, so do you think importing it will still solve the problem?

The reason I was using a Pressable element inside the MapView is to create a "center position on my location" button.  I just saw the solution to this problem in your reference code, so thanks a bunch for that!

Thanks again for the help!  Let me know if you think I need to import and use TouchableOpacity anywhere in the Component?

**Comment by navarrofracisco** [comment] 2022-09-12 23:08
@madahatter got it. No, you should not need to `import { TouchableOpacity } from "react-native-gesture-handler";` if you are not using it. I only mentioned that, because any other type of touchable/pressable elements seem to be buggy when used inside or around the <Maps> element. So if you ever encounter problems with your buttons while using the maps library you may to use the code I mentioned.

Were u able to solve ur problem?

**Comment by driiftkiing** [comment] 2022-11-08 10:35
@Simon-TechForm: I can reproduce this behaviour on iOS with the provided code from https://github.com/react-native-maps/react-native-maps/issues/4282.

| iOS            | 16.1 (Device) |
| :---------------- | :------------- |
| **react-native** | **0.67.4**    |

**Comment by hamdidamar** [comment] 2023-05-23 06:58
Same here. Is there any persist solution? I have same issue on ios. When ı drag marker its still focus on map and cant touch any component. Just when ı click maap again ı can use my screen.
