### ISSUE TITLE
Dragging marker makes MapView steal focus of app

### ISSUE THREAD

**Issue by MarcusQuist** [react-native-maps/react-native-maps#4282] opened 2022-06-28 21:24 UTC
### Summary

When I drag a marker inside of MapView, I cannot interact with any buttons on the page. However, if I use my fingers to move around inside the map, zoom in/out or rotate the map, I can yet again click the button.

It seems like the MapView's marker is stealing some sort of focus.
Any ideas to what is happening?

Using MapView from react-native-maps version 0.29.4.

### Reproducible sample code

```TSX
import React from "react";
import { View, Dimensions, Button } from "react-native";
import MapView, { Marker, PROVIDER_GOOGLE } from "react-native-maps";

const app = (
    <View
      style={{
        flex: 1,
        alignItems: "center",
        justifyContent: "center",
      }}
    >
      <MapView
        style={{ width: Dimensions.get("window").width, height: 400 }}
        provider={PROVIDER_GOOGLE}
        initialRegion={{
          latitude: 37.78825,
          longitude: -122.4324,
          latitudeDelta: 0.0922,
          longitudeDelta: 0.0421,
        }}
      >
        <Marker
          key="marker"
          coordinate={{
            latitude: 37.78825,
            longitude: -122.4324,
          }}
          draggable
        />
      </MapView>
      <Button title="Click me" onPress={() => console.log("Clicked")}></Button>
    </View>
  );
export default app;
```

### Steps to reproduce

1. Drag the marker
2. Click the button (fails)
3. Zoom in / out in the MapView
4. Click the button (works)

### Expected result

It should be clickable without having to zoom in/out after moving the marker.

### Actual result

After moving the marker, it becomes impossible to interact with anything on the app untill the map has been zoomed in / out, rotated or dragged.

### React Native Maps Version

0.29.4

### What platforms are you seeing the problem on?

iOS (Google Maps)

### React Native Version

0.64.3

### Are you using Expo?

Yes

### Device(s)

Iphone 12 Pro

### Additional information

I have not tested on newer versions of react-native-maps, as I am forced to use this version because I use a stable firebase version requiring this version of React Native & Expo.

**Comment by Simon-TechForm** [comment] 2022-07-01 20:53
hi @MarcusQuist 👋 I believe that this is caused by the same issue causing #3817, so I will reference it and close this for now. If you believe that I'm mistaking, let me know :)

**Closed by Simon-TechForm** 2022-07-01 20:53 UTC
Labels: bug
