### ISSUE TITLE
UrlTile is not working with openstreetmap url on Android

### ISSUE THREAD

**Issue by artemrsx** [react-native-maps/react-native-maps#3747] opened 2021-03-13 16:12 UTC
# Bug report

## Summary
UrlTile is not working with openstreetmap url on Android
works great with IOS, but not working with Android (emulator/real device)

## Environment info
OS: macOS 11.2.2,
Android: Pixel 4XL API 30 Android 11.0

`react-native info` output:

```bash
"react": "16.11.0",
"react-dom": "16.11.0",
"react-native": "0.62",
"react-native-maps": "0.27.1"
```

## Steps to reproduce
1. Create new project
2. Add react-native-maps
3. Use `<UrlTile urlTemplate="http://c.tile.openstreetmap.org/{z}/{x}/{y}.png" />`
4. `UrlTile` works fine with this url 'http://tile.stamen.com/terrain/{z}/{x}/{y}.jpg' but not working with `osm` url 'http://c.tile.openstreetmap.org/{z}/{x}/{y}.png' (403 Forbidden) although `osm` url works in browser
looks like `osm` blocked `user-agent`

Describe what you expected to happen:
- Visible OSM tiles

Describe what you actually happens:
- Blank map on android device

## Reproducible sample code
```
<MapView region={this.state.region}>
  <UrlTile
    urlTemplate="http://c.tile.openstreetmap.org/{z}/{x}/{y}.png"
    maximumZ={19}
    zIndex={99}
  />
</MapView>
```

Android:
[![Android][1]][1]
IOS:
[![IOS][2]][2]

  [1]: https://i.stack.imgur.com/V2ZqRm.png
  [2]: https://i.stack.imgur.com/1opJdm.jpg

**Comment by MaRaSu** [comment] 2021-03-15 06:39
@artemrsx, I run into the same problem with tile.openstreetmap.org server. However, it's the only tile server I have had any problem with react-native-maps. Therefore my guess is that the reason is related on to how native UrlTileProvider in Android (i.e. outside of scope of react-native-maps) is sending queries to tile.openstreetmap.org. That tile server might be e.g. blocking certain http user agents due to misuse of their tile server (tile.openstreetmap.org has a usage policy: [https://operations.osmfoundation.org/policies/tiles/](url).

E.g. tile.openstreetmap.de works if you want to test your app with OSM-data. Note however that it is not meant for production use either.

**Comment by jasonmichaels** [comment] 2021-03-15 17:54
@MaRaSu Would you say, then, that this is less a RNM issue and more an OSM issue? Looking to close this.

**Comment by MaRaSu** [comment] 2021-03-15 18:52
@jasonmichaels Yep, my best guess is that this is between UrlTileProvider in Android and openstreetmap.org tile servers i.e. not related to RNM. 

Lots of developers are abusing those tile servers so I can imagine that they have started to enforce their usage policy more strictly. I have spent a bit of time also looking at RNM code for Tile Overlays and cannot imagine where in the RNM code the reason for this could be.

**Comment by jasonmichaels** [comment] 2021-03-15 19:16
@MaRaSu -- confirmed. I'm going to close this then. Thanks!

**Closed by jasonmichaels** 2021-03-15 19:16 UTC
Labels: bug

**Comment by artemrsx** [comment] 2021-03-15 19:49
OpenStreetMap's tile usage policy (https://operations.osmfoundation.org/policies/tiles) says that a "Valid HTTP User-Agent identifying application" must be sent. As I understand the current user-agent `UrlTile` sends when it downloads a tile is the same for every app. Looks like we should send a user-agent that is more compliant with OSM's tile usage policy. The idea is actually to change the user agent value, because the default has been banned and anyway you're supposed to overwrite this value.

**Comment by Shashank-ecInfo** [comment] 2021-08-13 03:14
@artemrsx can you please tell me if you're able to use openstreetmap tile and if you did able to use it, then please tell the process as I'm stuck at this for 3 days.

**Comment by ydhnwb** [comment] 2022-02-21 08:56
the url 
```http://c.tile.openstreetmap.org/{z}/{x}/{y}.png```

is hit when we moving, zooming the maps?

**Comment by Sbenitez-Ideas** [comment] 2022-07-24 22:10
Any solution?, I have the same issue.

**Comment by JKKholmatov** [comment] 2023-06-13 01:12
Any solution?, I have the same issue.

**Comment by songsongchen** [comment] 2023-07-19 08:14
怎么解决

**Comment by DendeberiaOleksandr** [comment] 2024-09-29 15:26
Hey, is there some solution ?

**Comment by vishaal-workhall** [comment] 2025-01-07 14:17
Any solution how to use tiles with react-native-maps ?

**Comment by vishaal-workhall** [comment] 2025-01-07 14:17
> Hey, is there some solution ?

Have you found any solution for this ?

**Comment by DendeberiaOleksandr** [comment] 2025-01-07 14:22
@vishaal-workhall I think the issue was related to the OSM host and I was needed to self host the tiles server in my local machine. I think they provide some Docker ready solutions, you only need to download(specify the url) of the tiles you need
