### ISSUE TITLE
Support for play-services-maps 18.0.0 new renderer (because of progressive rollout 2022)

### ISSUE THREAD

**Issue by tonsnoei** [react-native-maps/react-native-maps#4101] opened 2022-02-18 08:14 UTC
# Feature request

Support for play-services-maps 18.0.0 new renderer. Because of progressive roll out in june 2022

## Why it is needed

I am not sure if the older version of the play-services-maps will be in support after june 2022

## Possible implementation

Just add `implementation 'com.google.android.gms:play-services-maps:18.0.0'` to the build.gradle?

**Comment by Simon-TechForm** [comment] 2022-02-21 10:59
There's already an open issue regarding this, as well as a pull request. See #3991 and #4055. I'm sure the pr author and maintainers would appreciate someone testing out the proposed changes :)

**Comment by Simon-TechForm** [comment] 2022-03-11 18:15
Duplicate of #3991.

**Closed by Simon-TechForm** 2022-03-11 18:15 UTC
Labels: Feature Request
