### ISSUE TITLE
EAS IOS builds getting fail

### ISSUE THREAD

**Issue by SohelIslamImran** [react-native-maps/react-native-maps#4563] opened 2022-12-13 20:42 UTC
### Summary

After upgraded to SDK47 and EAS, my IOS builds getting fail.
![image](https://user-images.githubusercontent.com/76745339/207436046-e7af4085-3d0b-4e62-866d-5e4a274d5c1f.png)

**Run fastlane** section last logs:
```sh
› Compiling build Pods/react-native-google-maps » react-native-google-maps-dummy.m
› Compiling react-native-maps Pods/react-native-google-maps » RCTConvert+GMSMapViewType.m
› Compiling react-native-maps Pods/react-native-google-maps » AIRGoogleMapWMSTileManager.m
› Compiling react-native-maps Pods/react-native-google-maps » AIRGoogleMapWMSTile.m
› Compiling react-native-maps Pods/react-native-google-maps » AIRGoogleMapUrlTile.m
› Compiling react-native-maps Pods/react-native-google-maps » AIRGoogleMapURLTileManager.m
› Compiling react-native-maps Pods/react-native-google-maps » AIRGoogleMapPolylineManager.m

❌  (node_modules/react-native-maps/ios/AirGoogleMaps/AIRGoogleMapPolylineManager.m:17:9)

  15 | #import <React/RCTViewManager.h>
  16 | #import <React/UIView+React.h>
> 17 | #import "RCTConvert+AirMap.h"
     |         ^ 'RCTConvert+AirMap.h' file not found
  18 | #import "AIRGoogleMapPolyline.h"
  19 | 
  20 | @interface AIRGoogleMapPolylineManager()
› Compiling react-native-maps Pods/react-native-google-maps » AIRGoogleMapPolyline.m
› Compiling react-native-maps Pods/react-native-google-maps » AIRGoogleMapPolygonManager.m
    Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'React-Codegen' from project 'Pods')
    Run script build phase 'Start Packager' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Tilleli' from project 'Tilleli')
    Run script build phase 'Bundle React Native code and images' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Tilleli' from project 'Tilleli')
    Run script build phase '[CP-User] Generate app.config for prebuilt Constants.manifest' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'EXConstants' from project 'Pods')
    Run script build phase '[CP-User] Generate app.manifest for expo-updates' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'EXUpdates' from project 'Pods')
    Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'RCT-Folly' from project 'Pods')
▸ ** ARCHIVE FAILED **
▸ The following build commands failed:
▸ 	CompileC /Users/expo/Library/Developer/Xcode/DerivedData/Tilleli-fzmqitxhjmwestgpefzrhsophzqr/Build/Intermediates.noindex/ArchiveIntermediates/Tilleli/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/react-native-google-maps.build/Objects-normal/arm64/AIRGoogleMapPolylineManager.o /Users/expo/workingdir/build/node_modules/react-native-maps/ios/AirGoogleMaps/AIRGoogleMapPolylineManager.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'react-native-google-maps' from project 'Pods')
▸ (1 failure)
** ARCHIVE FAILED **
The following build commands failed:
	CompileC /Users/expo/Library/Developer/Xcode/DerivedData/Tilleli-fzmqitxhjmwestgpefzrhsophzqr/Build/Intermediates.noindex/ArchiveIntermediates/Tilleli/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/react-native-google-maps.build/Objects-normal/arm64/AIRGoogleMapPolylineManager.o /Users/expo/workingdir/build/node_modules/react-native-maps/ios/AirGoogleMaps/AIRGoogleMapPolylineManager.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'react-native-google-maps' from project 'Pods')
(1 failure)
Exit status: 65
+-------------+-------------------------+
|           Build environment           |
+-------------+-------------------------+
| xcode_path  | /Applications/Xcode.app |
| gym_version | 2.210.0                 |
| sdk         | iPhoneOS16.0.sdk        |
+-------------+-------------------------+
Looks like fastlane ran into a build/archive error with your project
It's hard to tell what's causing the error, so we wrote some guides on how
to troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/
Before submitting an issue on GitHub, please follow the guide above and make
sure your project is set up correctly.
fastlane uses `xcodebuild` commands to generate your binary, you can see the
the full commands printed out in yellow in the above log.
Make sure to inspect the output above, as usually you'll find more error information there
[stderr] [!] Error building the application - see the log above
Error: Fastlane build failed with unknown error. See logs for the "Run fastlane" and "Xcode Logs" phases for more information.
Fastlane errors in most cases are not printed at the end of the output, so you may not find any useful information in the last lines of output when looking for an error message.
```

### Reproducible sample code

I'm currently using `firebase` js package and `expo-firebase-analytics` with `"expo-build-properties"` plugins.
![image](https://user-images.githubusercontent.com/76745339/207439708-8a8da07f-f973-472e-843a-3090551a45b3.png)

### Steps to reproduce

I found https://forums.expo.dev/t/eas-build-fails-sdk-47-ios-file-not-found-in-react-native-maps/67908 and this discussion https://github.com/react-native-maps/react-native-maps/discussions/4389 

 Can you please give me a solution?

### Expected result

Should build the app

### Actual result

Can't build. 

### React Native Maps Version

1.3.2

### What platforms are you seeing the problem on?

iOS (Google Maps)

### React Native Version

0.70.5

### What version of Expo are you using?

SDK 47

### Device(s)

IOS

**Comment by NxsHbb** [comment] 2022-12-14 09:22
I am also facing similar issue
Expo SDK 47 (managed)

The following build commands failed:
	`CompileC /Users/expo/Library/Developer/Xcode/DerivedData/HomListi-ccxodtjizzeesdethgbxbudycanm/Build/Intermediates.noindex/ArchiveIntermediates/HomListi/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/react-native-google-maps.build/Objects-normal/arm64/AIRGoogleMapPolylineManager.o /Users/expo/workingdir/build/node_modules/react-native-maps/ios/AirGoogleMaps/AIRGoogleMapPolylineManager.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'react-native-google-maps' from project 'Pods')`

**Comment by alqamabinsadiq** [comment] 2022-12-16 21:11
Facing same in using react native cli 😢

**Comment by hasnainbaloch** [comment] 2022-12-17 11:31
Same issue with react native version 0.70 build failed

**Comment by SzaboKrisztian** [comment] 2022-12-21 07:41
Same issue here, on an Expo managed project with SDK 47

**Comment by SohelIslamImran** [comment] 2022-12-21 14:06
Try this, It will resolve the build issue. But now crashing my ios app.

```js
// react-native-maps-plugin.js
const fs = require("fs");
const path = require("path");
const generateCode = require("@expo/config-plugins/build/utils/generateCode");
const configPlugins = require("@expo/config-plugins");

const code = `    # Note you don't need to add RNBootSplash or react-native-app-auth if unused
$static_library = [
 'React',
 'Google-Maps-iOS-Utils',
 'GoogleMaps',
 'react-native-maps',
 'react-native-google-maps',
 'React-hermes'
]

pre_install do |installer|
    Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
    installer.pod_targets.each do |pod|
      bt = pod.send(:build_type)
      if $static_library.include?(pod.name)
        puts "Overriding the build_type to static_library from static_framework for #{pod.name}"
        def pod.build_type;
          Pod::BuildType.static_library
        end
      end
    end
    installer.pod_targets.each do |pod|
      bt = pod.send(:build_type)
      puts "#{pod.name} (#{bt})"
      puts "  linkage: #{bt.send(:linkage)} packaging: #{bt.send(:packaging)}"
    end
end`;

module.exports = (config) => {
  return configPlugins.withDangerousMod(config, [
    "ios",
    async (config) => {
      const filePath = path.join(
        config.modRequest.platformProjectRoot,
        "Podfile"
      );
      const contents = fs.readFileSync(filePath, "utf-8");

      const addCode = generateCode.mergeContents({
        tag: "withReactNativeFirebase",
        src: contents,
        newSrc: code,
        anchor: /\s*get_default_flags\(\)/i,
        offset: 2,
        comment: "#",
      });

      if (!addCode.didMerge) {
        console.error(
          "ERROR: Cannot add withReactNativeMaps to the project's ios/Podfile because it's malformed."
        );
        return config;
      }

      fs.writeFileSync(filePath, addCode.contents);

      return config;
    },
  ]);
};
```

```json
// app.json
"plugins": [
      "./react-native-maps-plugin",
    ],
```

**Comment by ansaf-kz** [comment] 2022-12-27 15:08
> 

Did you manage to solve this issue?

**Comment by fakhruz3105** [comment] 2023-01-05 13:41
Face the same issue, is there any fix yet?

**Comment by SohelIslamImran** [comment] 2023-01-05 14:18
Try the method mentioned above @fakhruz3105

**Comment by ansaf-kz** [comment] 2023-01-05 15:16
> Try the method mentioned above @fakhruz3105

I tried it and as it was mentioned, compilation goes with no issues but the app crashes anyway

**Comment by SohelIslamImran** [comment] 2023-01-05 15:53
> I tried it and as it was mentioned, compilation goes with no issues but the app crashes anyway
Yes. Same

**Comment by fakhruz3105** [comment] 2023-01-06 02:01
> > Try the method mentioned above @fakhruz3105
> 
> I tried it and as it was mentioned, compilation goes with no issues but the app crashes anyway

Yes, same

**Comment by ericlemans** [comment] 2023-01-08 01:00
No solutions out there yet? When I was using non expo build:iOS, I wasn’t getting this issue

**Comment by daganchen** [comment] 2023-01-08 10:18
[RUN_FASTLANE] The following build commands failed:
[RUN_FASTLANE]  PhaseScriptExecution [CP-User]\ Generate\ app.manifest\ for\ expo-updates /var/folders/4y/fgzcj0ks4bd2r29s4w8pc_t00000gq/T/eas-build-local-nodejs/331193ca-f1a9-4cde-bf0a-10ee35985159/build/ios/build/Build/Intermediates.noindex/Pods.build/Release-iphonesimulator/EXUpdates.build/Script-46EB2E0001C540.sh (in target 'EXUpdates' from project 'Pods')
[RUN_FASTLANE] (1 failure)
[RUN_FASTLANE] Exit status: 65
[RUN_FASTLANE] › Compiling expo-dev-menu Pods/expo-dev-menu » DevMenuREASetNode.m
[RUN_FASTLANE] › Compiling expo-dev-menu Pods/expo-dev-menu » DevMenuREAPropsNode.m

**Comment by SohelIslamImran** [comment] 2023-01-08 13:31
> No solutions out there yet? When I was using non expo build:iOS, I wasn’t getting this issue

Yes. Same.

**Comment by tonydatw** [comment] 2023-01-13 23:37
same issue here

**Comment by GITupeer** [comment] 2023-01-16 08:40
same issue, on expo SDK 47

**Comment by sylvainlg** [comment] 2023-01-16 08:44
Hi

The @SohelIslamImran solution is working (found here too https://github.com/react-native-maps/react-native-maps/discussions/4389#discussioncomment-3750010).

**Comment by SohelIslamImran** [comment] 2023-01-26 22:06
@Simon-TechForm This issue is still not fixed. Very sad. Can't build our IOS app for a long time.

**Comment by devuco** [comment] 2023-01-30 05:14
Hello @all
Since there is no merge for #4572, everyone can use this fork https://github.com/infoSamyak/react-native-maps/tree/master

**Comment by SohelIslamImran** [comment] 2023-01-30 09:32
> Try this, It will resolve the build issue. But now crashing my ios app.
> 
> ```js
> // react-native-maps-plugin.js
> const fs = require("fs");
> const path = require("path");
> const generateCode = require("@expo/config-plugins/build/utils/generateCode");
> const configPlugins = require("@expo/config-plugins");
> 
> const code = `    # Note you don't need to add RNBootSplash or react-native-app-auth if unused
> $static_library = [
>  'React',
>  'Google-Maps-iOS-Utils',
>  'GoogleMaps',
>  'react-native-maps',
>  'react-native-google-maps',
>  'React-hermes'
> ]
> 
> pre_install do |installer|
>     Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
>     installer.pod_targets.each do |pod|
>       bt = pod.send(:build_type)
>       if $static_library.include?(pod.name)
>         puts "Overriding the build_type to static_library from static_framework for #{pod.name}"
>         def pod.build_type;
>           Pod::BuildType.static_library
>         end
>       end
>     end
>     installer.pod_targets.each do |pod|
>       bt = pod.send(:build_type)
>       puts "#{pod.name} (#{bt})"
>       puts "  linkage: #{bt.send(:linkage)} packaging: #{bt.send(:packaging)}"
>     end
> end`;
> 
> module.exports = (config) => {
>   return configPlugins.withDangerousMod(config, [
>     "ios",
>     async (config) => {
>       const filePath = path.join(
>         config.modRequest.platformProjectRoot,
>         "Podfile"
>       );
>       const contents = fs.readFileSync(filePath, "utf-8");
> 
>       const addCode = generateCode.mergeContents({
>         tag: "withReactNativeFirebase",
>         src: contents,
>         newSrc: code,
>         anchor: /\s*get_default_flags\(\)/i,
>         offset: 2,
>         comment: "#",
>       });
> 
>       if (!addCode.didMerge) {
>         console.error(
>           "ERROR: Cannot add withReactNativeMaps to the project's ios/Podfile because it's malformed."
>         );
>         return config;
>       }
> 
>       fs.writeFileSync(filePath, addCode.contents);
> 
>       return config;
>     },
>   ]);
> };
> ```
> 
> ```json
> // app.json
> "plugins": [
>       "./react-native-maps-plugin",
>     ],
> ```

Also, currently this is working for me. You can try this.

**Comment by SohelIslamImran** [comment] 2023-01-30 13:12
> Try this, It will resolve the build issue. But now crashing my ios app.
> 
> ```js
> // react-native-maps-plugin.js
> const fs = require("fs");
> const path = require("path");
> const generateCode = require("@expo/config-plugins/build/utils/generateCode");
> const configPlugins = require("@expo/config-plugins");
> 
> const code = `# Note you don't need to add RNBootSplash or react-native-app-auth if unused
> $static_library = [
>  'React',
>  'Google-Maps-iOS-Utils',
>  'GoogleMaps',
>  'react-native-maps',
>  'react-native-google-maps',
>  'React-hermes'
> ]
> 
> pre_install do |installer|
>     Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
>     installer.pod_targets.each do |pod|
>       bt = pod.send(:build_type)
>       if $static_library.include?(pod.name)
>         puts "Overriding the build_type to static_library from static_framework for #{pod.name}"
>         def pod.build_type;
>           Pod::BuildType.static_library
>         end
>       end
>     end
>     installer.pod_targets.each do |pod|
>       bt = pod.send(:build_type)
>       puts "#{pod.name} (#{bt})"
>       puts "  linkage: #{bt.send(:linkage)} packaging: #{bt.send(:packaging)}"
>     end
> end`;
> 
> module.exports = (expoConfig) => {
>   return configPlugins.withDangerousMod(expoConfig, [
>     "ios",
>     async (config) => {
>       const filePath = path.join(
>         config.modRequest.platformProjectRoot,
>         "Podfile"
>       );
>       const contents = fs.readFileSync(filePath, "utf-8");
> 
>       const addCode = generateCode.mergeContents({
>         tag: "withReactNativeFirebase",
>         src: contents,
>         newSrc: code,
>         anchor: /\s*get_default_flags\(\)/i,
>         offset: 2,
>         comment: "#",
>       });
> 
>       if (!addCode.didMerge) {
>         console.error(
>           "ERROR: Cannot add withReactNativeMaps to the project's ios/Podfile because it's malformed."
>         );
>         return config;
>       }
> 
>       fs.writeFileSync(filePath, addCode.contents);
> 
>       return config;
>     },
>   ]);
> };
> ```
> 
> ```json
> // app.json
> "plugins": [
>       "./react-native-maps-plugin",
>     ],
> ```

Also, currently this is working for me. You can try this.

**Comment by NxsHbb** [comment] 2023-02-01 05:43
> > Try this, It will resolve the build issue. But now crashing my ios app.
> > ```js
> > // react-native-maps-plugin.js
> > const fs = require("fs");
> > const path = require("path");
> > const generateCode = require("@expo/config-plugins/build/utils/generateCode");
> > const configPlugins = require("@expo/config-plugins");
> > 
> > const code = `# Note you don't need to add RNBootSplash or react-native-app-auth if unused
> > $static_library = [
> >  'React',
> >  'Google-Maps-iOS-Utils',
> >  'GoogleMaps',
> >  'react-native-maps',
> >  'react-native-google-maps',
> >  'React-hermes'
> > ]
> > 
> > pre_install do |installer|
> >     Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
> >     installer.pod_targets.each do |pod|
> >       bt = pod.send(:build_type)
> >       if $static_library.include?(pod.name)
> >         puts "Overriding the build_type to static_library from static_framework for #{pod.name}"
> >         def pod.build_type;
> >           Pod::BuildType.static_library
> >         end
> >       end
> >     end
> >     installer.pod_targets.each do |pod|
> >       bt = pod.send(:build_type)
> >       puts "#{pod.name} (#{bt})"
> >       puts "  linkage: #{bt.send(:linkage)} packaging: #{bt.send(:packaging)}"
> >     end
> > end`;
> > 
> > module.exports = (expoConfig) => {
> >   return configPlugins.withDangerousMod(expoConfig, [
> >     "ios",
> >     async (config) => {
> >       const filePath = path.join(
> >         config.modRequest.platformProjectRoot,
> >         "Podfile"
> >       );
> >       const contents = fs.readFileSync(filePath, "utf-8");
> > 
> >       const addCode = generateCode.mergeContents({
> >         tag: "withReactNativeFirebase",
> >         src: contents,
> >         newSrc: code,
> >         anchor: /\s*get_default_flags\(\)/i,
> >         offset: 2,
> >         comment: "#",
> >       });
> > 
> >       if (!addCode.didMerge) {
> >         console.error(
> >           "ERROR: Cannot add withReactNativeMaps to the project's ios/Podfile because it's malformed."
> >         );
> >         return config;
> >       }
> > 
> >       fs.writeFileSync(filePath, addCode.contents);
> > 
> >       return config;
> >     },
> >   ]);
> > };
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```json
> > // app.json
> > "plugins": [
> >       "./react-native-maps-plugin",
> >     ],
> > ```
> 
> Also, currently this is working for me. You can try this.

Some says it solves the build issue but it crashes the iOS app. Did your app crash?

**Comment by izniburak** [comment] 2023-02-03 19:20
Is there any exact solution about that? Any suggestion?

**Comment by SohelIslamImran** [comment] 2023-02-03 19:37
> Some says it solves the build issue but it crashes the iOS app. Did your app crash?


Previously it was crashing but currently it is not crashing for me.

**Comment by ChromeQ** [comment] 2023-03-05 12:34
This issue is still persisting, I tried with the plugin and builds, but the app crashes on first click. How has this not been fixed yet as it is a major breakage. Using expo v48.

**Comment by jan-karnik** [comment] 2023-03-07 22:41
> > Some says it solves the build issue but it crashes the iOS app. Did your app crash?
> 
> Previously it was crashing but currently it is not crashing for me.


@SohelIslamImran  What expo were you running where it works and doesn't crash can i ask?

**Comment by SohelIslamImran** [comment] 2023-03-08 10:05
@jan-karnik Also, using `"react-native-maps"` version `1.4.0`

**Comment by heidgert** [comment] 2023-03-20 07:49
Build works for me, but...

I was having the same problems with EAS build failed on iOS and by following the comment by @SohelIslamImran (https://github.com/react-native-maps/react-native-maps/issues/4563#issuecomment-1408609039) I managed to build my app (thanks for getting me that far!).

The problem I am experiencing is that the maps are blank. The indicator for my position is visible but no map details are there.

I'm using Expo 48 with `react-native-maps` version `1.4.0`.

Anyone else experiencing this?

**Comment by heidgert** [comment] 2023-03-20 07:54
A quick update. Switching to the default provider (Apple Maps) works.

**Comment by SohelIslamImran** [comment] 2023-03-20 19:33
Maybe you didn't add the Google Map API key @heidgert? https://docs.expo.dev/versions/latest/sdk/map-view/#ios

**Comment by heidgert** [comment] 2023-03-21 07:03
You are absolutely correct. I recently switched to using expo-dev-client and used a different bundle identifier for this build. By adding this bundle identifier to my app on Google Cloud console under API keys the map started working again.

Thanks for pointing me in the right direction!

**Comment by BrodaNoel** [comment] 2023-03-23 08:05
This is properly working on SDK 48, and also works for iOS: https://github.com/react-native-maps/react-native-maps/issues/4563#issuecomment-1361353933

**Comment by stau1** [comment] 2023-03-27 00:02
> This is properly working on SDK 48, and also works for iOS: [#4563 (comment)](https://github.com/react-native-maps/react-native-maps/issues/4563#issuecomment-1361353933)

For us it unfortunately isn't...

**Comment by SohelIslamImran** [comment] 2023-03-27 00:10
Try with `"react-native-maps"` version `1.4.0` @stau1

**Comment by stau1** [comment] 2023-03-28 04:22
Thank you, @SohelIslamImran. Even after forcing react-native-maps 1.4.0 on SDK 48 (apparently it prefers 1.3.2) it's still throwing the error and crashing the app shortly after I open it. Maybe something else in my setup?

 "dependencies": {
    "@expo-google-fonts/lato": "^0.2.2",
    "@expo-google-fonts/oswald": "^0.2.2",
    "@expo/react-native-action-sheet": "^4.0.1",
    "@mapbox/geo-viewport": "^0.5.0",
    "@react-native-async-storage/async-storage": "1.17.11",
    "@react-native-community/eslint-config": "^3.0.1",
    "@react-native-community/masked-view": "^0.1.11",
    "@react-navigation/bottom-tabs": "^6.1.0",
    "@react-navigation/drawer": "^6.4.1",
    "@react-navigation/native": "^6.1.1",
    "@react-navigation/stack": "^6.2.1",
    "@shopify/flash-list": "1.4.0",
    "axios": "^0.25.0",
    "deepmerge": "^3.3.0",
    "eslint": "^8.30.0",
    "expo": "^48.0.0",
    "expo-asset": "~8.9.1",
    "expo-build-properties": "~0.5.1",
    "expo-cached-image": "^48.0.0",
    "expo-dev-client": "~2.1.6",
    "expo-device": "~5.2.1",
    "expo-font": "~11.1.1",
    "expo-image-picker": "~14.1.1",
    "expo-jwt": "^1.4.1",
    "expo-keep-awake": "~12.0.1",
    "expo-linear-gradient": "~12.1.2",
    "expo-location": "~15.1.1",
    "expo-navigation-bar": "~2.1.1",
    "expo-splash-screen": "~0.18.1",
    "expo-status-bar": "~1.4.4",
    "fast-deep-equal": "^3.1.3",
    "object-hash": "^2.2.0",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.71.4",
    "react-native-confirmation-code-field": "^7.3.1",
    "react-native-gesture-handler": "~2.9.0",
    "react-native-google-mobile-ads": "^10.0.0",
    "react-native-maps": "^1.4.0",
    "react-native-paper": "^4.11.2",
    "react-native-reanimated": "~2.14.4",
    "react-native-safe-area-context": "4.5.0",
    "react-native-screens": "~3.20.0",
    "react-native-svg": "13.4.0",
    "react-native-web": "~0.18.11",
    "react-redux": "^7.2.6",
    "redux": "^4.1.2",
    "redux-thunk": "^2.4.1",
    "spin-delay": "^1.2.0",
    "styled-components": "^5.3.3",
    "supercluster": "^7.1.5"
  },

**Comment by SohelIslamImran** [comment] 2023-03-28 08:08
@stau1 show me the error

**Comment by SohelIslamImran** [comment] 2023-03-28 16:19
Not this, the logs of the build page of Expo.

**Comment by stau1** [comment] 2023-03-28 17:55
Thank you, @SohelIslamImran for offering to take a look at the logs! Before I start spamming this thread with endless log file content, can you tell me which of the following logs would be helpful for you to take a look at?

<img width="494" alt="image" src="https://user-images.githubusercontent.com/18011358/228325860-34710582-c307-41d4-adc8-5ea53ccf6e3d.png">

(The Exp Doctor warning only complains about react-native-maps being 1.4.0 and not 1.3.2)
Other than that no errors are highlighted in particular.

**Comment by stau1** [comment] 2023-03-28 19:27
@BrodaNoel - okay that's embarrassing on my part - thank you for pointing this out! Always tested on Expo Go and there it wasn't a problem. Then eventually switched to EAS because I had to integrate  'react-native-google-mobile-ads'...

**Comment by jfbn** [comment] 2023-03-29 09:21
EAS iOS development build is also failing for me.
The error:
```
Build failed: Compatible versions of some pods could not be resolved.
You are seeing this error because either:
  - Versions in the cached Podfile.lock do not match required values in Podspecs of some installed libraries. To fix this, you can re-run build command with "--clear-cache" option, or select "Clear cache and retry build" on the build page.
  - Some of the pods used in your project depend on different versions of the same pod. See logs for more information.
  ```
  
   I ran `expo prebuild` and then `eas build --clear-cache --profile development-simulator platform ios` and it still occurred. 
   I am not meant to step into the `ios` folder and `pod install` when I'm using the `expo prebuild` to handle native configurations, am i?

**Comment by Simon-TechForm** [comment] 2023-04-18 22:17
Hello everyone 👋

I've just released a new beta version that should fix this (see: [v1.5.1-beta.3](https://github.com/react-native-maps/react-native-maps/releases/tag/v1.5.1-beta.3)). Please check it out, and if doesn't solve the issue, feel free to open a new issue!

As this issue is accumulating all sorts of other issues, I'm going to close it, but please feel free to open a new issue if the release I've just mentioned doesn't fix the build issue 👍

**Closed by Simon-TechForm** 2023-04-18 22:17 UTC
Labels: bug

**Comment by alexvazquez** [comment] 2023-04-19 20:10
> Hello everyone 👋
> 
> I've just released a new beta version that should fix this (see: [v1.5.1-beta.3](https://github.com/react-native-maps/react-native-maps/releases/tag/v1.5.1-beta.3)). Please check it out, and if doesn't solve the issue, feel free to open a new issue!
> 
> As this issue is accumulating all sorts of other issues, I'm going to close it, but please feel free to open a new issue if the release I've just mentioned doesn't fix the build issue 👍

@Simon-TechForm I can confirm that it works!! I had the same issue, found this thread today and saw your comment about version 1.5.1-beta.3.  Im installing the app using _eas build --profile development --platform ios --clear-cache_ and will write here after if I found any issue with maps, etc.

Thanks

**Comment by leggomuhgreggo** [comment] 2023-06-23 10:31
The [config plugin fix](https://github.com/react-native-maps/react-native-maps/issues/4563#issuecomment-1361353933) worked!

Details:

- `"expo": "48.0.19"`
- `"react-native-maps": "1.3.2"`
- `['expo-build-properties', { ios: { useFrameworks: 'static' } }]`
- Nx monorepo

Thank you very much @SohelIslamImran 🙏

**Comment by SohelIslamImran** [comment] 2023-06-23 10:57
> The [config plugin fix](https://github.com/react-native-maps/react-native-maps/issues/4563#issuecomment-1361353933) worked!

@leggomuhgreggo You no longer need the config plugin. Update `"react-native-maps"` to the latest version... The issue already solved

**Comment by leggomuhgreggo** [comment] 2023-06-23 13:23
Yeah it's odd. Before I tried your plugin fix, I had tried `1.7.1` (latest) -- as well as `1.6.x` and `1.4.x` -- and couldn't get iOS to pass the build. 

Just tried `1.7.1` again and got this:
```
› Compiling react-native-maps Pods/react-native-google-maps » AIRGoogleMapHeatmapManager.m

❌  (/Users/expo/workingdir/build/apps/order/ios/build/Build/Products/Debug-iphonesimulator/Google-Maps-iOS-Utils/GoogleMapsUtils.framework/Headers/GoogleMapsUtils-Swift.h:280:2)

  278 | 
  279 | #else
> 280 | #error unsupported Swift architecture
      |  ^ unsupported Swift architecture
  281 | #endif
  282 | 

❌  (../../node_modules/react-native-maps/ios/AirGoogleMaps/AIRGoogleMapHeatmap.h:7:9)

   5 | //
   6 | 
>  7 | #import "GMUHeatmapTileLayer.h"
     |         ^ could not build module 'GoogleMapsUtils'
   8 | 
   9 | @interface AIRGoogleMapHeatmap : UIView
  10 | 
› Compiling react-native-maps Pods/react-native-google-maps » AIRGoogleMapHeatmap.m
```

Must be some idiosyncrasy of my usage which is thwarting that fix.

Figured I'd concede to the expo-prescribed version `1.3.2`, for the time being, but definitely curious to find a better solution.

**Comment by ldevLucasl** [comment] 2023-07-11 21:16
same issue here @leggomuhgreggo 😞

**Comment by SohelIslamImran** [comment] 2023-07-11 22:35
@leggomuhgreggo Expo cache your builds to speed up, so clearing the cache with `eas build --clear-cache` may work.
@ldevLucasl try to upgrade to new SDK 49 and the latest map

**Comment by ldevLucasl** [comment] 2023-07-11 23:02
@SohelIslamImran im current using `expo SDK 49` and `react-native-maps@1.7.1` but the issue to be continued.

I did install and configure `react-native-maps` today and got the same error as @leggomuhgreggo.

**Comment by ldevLucasl** [comment] 2023-07-11 23:22
<img width="1118" alt="Screenshot 2023-07-11 at 20 21 20" src="https://github.com/react-native-maps/react-native-maps/assets/62044186/86dc06c2-477f-49d0-b1d2-b48de159534a">

**Comment by SohelIslamImran** [comment] 2023-07-12 13:41
I think this is not related to this.. Try to create a new issue.

**Comment by SohelIslamImran** [comment] 2023-07-13 08:49
I created a new issue here https://github.com/react-native-maps/react-native-maps/issues/4793 @ldevLucasl @leggomuhgreggo

**Comment by SohelIslamImran** [comment] 2023-08-09 13:16
Try this plugin @ldevLucasl @leggomuhgreggo, It will resolve the issue. Check out the issue here : https://github.com/react-native-maps/react-native-maps/issues/4793

```js
// react-native-maps-plugin.js
const fs = require("fs");
const path = require("path");
const { withDangerousMod } = require("expo/config-plugins");
const generateCode = require("@expo/config-plugins/build/utils/generateCode");

// https://github.com/react-native-maps/react-native-maps/issues/4793#issuecomment-1671269814
const googleMapsIosSiliconWorkaroundPodCode = `pod 'Google-Maps-iOS-Utils', :git => 'https://github.com/Simon-TechForm/google-maps-ios-utils.git', :branch => 'feat/support-apple-silicon'`;

/** @type { import('expo/config-plugins').ConfigPlugin } */
const withPlugin = (expoConfig) => {
  return withDangerousMod(expoConfig, [
    "ios",
    async (config) => {
      const filePath = path.join(
        config.modRequest.platformProjectRoot,
        "Podfile"
      );

      const contents = fs.readFileSync(filePath, "utf-8");

      const addCode = generateCode.mergeContents({
        newSrc: googleMapsIosSiliconWorkaroundPodCode,
        tag: "withGoogleMapsIOSWorkaroundPlugin",
        anchor: /\s*get_default_flags\(\)/i,
        src: contents,
        comment: "#",
        offset: 2,
      });

      if (!addCode.didMerge) {
        console.warn(
          "WARNING: Couldn't add custom plugin Podfile code from app.plugin.js to the project's ios/Podfile."
        );
        return config;
      }

      fs.writeFileSync(filePath, addCode.contents);

      return config;
    },
  ]);
};

module.exports = withPlugin;
```

```json
// app.json
"plugins": [
      "./react-native-maps-plugin",
    ],
```

As mentioned here :
https://github.com/react-native-maps/react-native-maps/pull/4757#issuecomment-1604959747
https://github.com/react-native-maps/react-native-maps/blob/master/docs/installation.md#enabling-google-maps
