### ISSUE TITLE
Can't map Polyline (ANDROID)

### ISSUE THREAD

**Issue by teachdugsimt** [react-native-maps/react-native-maps#3823] opened 2021-05-18 04:11 UTC
# In lastest  update.  Same code but can't map polyline.

Error while updating property 'lineCap' of a view managed by: AIRMapPolyline

Case :
1. I have  older react-native project don't run npm install this Polyline is work normally.
2. In my production project after run npm install  it not work (Same code).

Step to reproduce: pick code from suggestion
[example](https://github.com/react-native-maps/react-native-maps/blob/master/docs/polyline.md)

<img width="1061" alt="Screen Shot 2564-05-18 at 11 05 57" src="https://user-images.githubusercontent.com/65938999/118588808-5bb79700-b7c9-11eb-9fa2-bdc8f0990524.png">

Result look like this picutre.

![messageImage_1621309702930](https://user-images.githubusercontent.com/65938999/118588079-ec8d7300-b7c7-11eb-8c38-970788f05076.jpg)

**Comment by Arsh150701** [comment] 2021-05-21 15:19
Facing the same issue, please update if you find a solution.

**Comment by teachdugsimt** [comment] 2021-05-24 03:48
1.  go to package.json
2.  "react-native-maps": "https://github.com/react-community/react-native-maps.git#X.Y.ZZ",
specify version code.
3. delete node_modules - package-lock.json -  yarn.lock
4. yarn install or npm install (Use yarn if npm can't run)

**Comment by Arsh150701** [comment] 2021-05-26 15:22
Hey, could you please share the exact version that worked for you?

**Comment by shovancak** [comment] 2021-06-04 11:45
Hello guys, can you tell me what version of package is working for you ?

**Comment by andkom** [comment] 2021-06-04 13:08
Have the same issue after upgrading to 0.28.0
0.27.1 is OK

**Comment by KaviduAloka** [comment] 2021-06-07 16:15
> 1. go to package.json
> 2. "react-native-maps": "https://github.com/react-community/react-native-maps.git#X.Y.ZZ",
>    specify version code.
> 3. delete node_modules - package-lock.json -  yarn.lock
> 4. yarn install or npm install (Use yarn if npm can't run)

I added  ```https://github.com/react-community/react-native-maps.git#0.27.1``` to my ```package.json``` and tried to ```npm install```. 
It gives **npm install error code 128**

Any sugestion?

**Comment by Arsh150701** [comment] 2021-06-07 19:06
> > 1. go to package.json
> > 2. "react-native-maps": "https://github.com/react-community/react-native-maps.git#X.Y.ZZ",
> >    specify version code.
> > 3. delete node_modules - package-lock.json -  yarn.lock
> > 4. yarn install or npm install (Use yarn if npm can't run)
> 
> I added  ```https://github.com/react-community/react-native-maps.git#0.27.1``` to my ```package.json``` and tried to ```npm install```. 
> It gives **npm install error code 128**
> 
> Any sugestion?

Try  "react-native-maps": "0.27.1"

**Comment by KaviduAloka** [comment] 2021-06-08 03:36
> > > 1. go to package.json
> > > 2. "react-native-maps": "https://github.com/react-community/react-native-maps.git#X.Y.ZZ",
> > >    specify version code.
> > > 3. delete node_modules - package-lock.json -  yarn.lock
> > > 4. yarn install or npm install (Use yarn if npm can't run)
> > 
> > 
> > I added  `https://github.com/react-community/react-native-maps.git#0.27.1` to my `package.json` and tried to `npm install`.
> > It gives **npm install error code 128**
> > Any sugestion?
> 
> Try "react-native-maps": "0.27.1"

I tried that. It gives the same same error as this original question explains

**Comment by KaviduAloka** [comment] 2021-06-09 16:10
> > > 1. go to package.json
> > > 2. "react-native-maps": "https://github.com/react-community/react-native-maps.git#X.Y.ZZ",
> > >    specify version code.
> > > 3. delete node_modules - package-lock.json -  yarn.lock
> > > 4. yarn install or npm install (Use yarn if npm can't run)
> > 
> > 
> > I added  `https://github.com/react-community/react-native-maps.git#0.27.1` to my `package.json` and tried to `npm install`.
> > It gives **npm install error code 128**
> > Any sugestion?
> 
> Try "react-native-maps": "0.27.1"

In this `Polyline` option is working. But the `Overlay` component's `bearing` feature is not working. I need both the features to be working

**Comment by Johan-dutoit** [comment] 2021-06-21 11:47
This is the offending https://github.com/react-native-maps/react-native-maps/pull/3797

**Comment by Johan-dutoit** [comment] 2021-06-21 11:51
patch file
```
diff --git a/node_modules/react-native-maps/lib/android/src/main/java/com/airbnb/android/react/maps/AirMapPolyline.java b/node_modules/react-native-maps/lib/android/src/main/java/com/airbnb/android/react/maps/AirMapPolyline.java
index 1af0b9f..662842e 100644
--- a/node_modules/react-native-maps/lib/android/src/main/java/com/airbnb/android/react/maps/AirMapPolyline.java
+++ b/node_modules/react-native-maps/lib/android/src/main/java/com/airbnb/android/react/maps/AirMapPolyline.java
@@ -100,7 +100,6 @@ public class AirMapPolyline extends AirMapFeature {
 
   private void applyPattern() {
     if(patternValues == null) {
-      polyline.setPattern(null);
       return;
     }
     this.pattern = new ArrayList<>(patternValues.size());
```

**Comment by gluons** [comment] 2021-07-02 07:16
For my case, I got this error after I upgrade to 0.29.0.

**Comment by dsf3449** [comment] 2021-07-02 14:27
Thanks for the patch file, it works 👍

**Comment by TeChn4K** [comment] 2021-07-02 14:34
Another workaround could be to set a `lineDashPattern` prop on your `Polyline` component.

```
    <Polyline
      ...
      lineDashPattern={[1]}
    />
```

**Comment by KaviduAloka** [comment] 2021-07-03 16:39
> Another workaround could be to set a `lineDashPattern` prop on your `Polyline` component.
> 
> ```
>     <Polyline
>       ...
>       lineDashPattern={[1]}
>     />
> ```

Thanks for this. It really worked

**Comment by shantnushubham** [comment] 2021-07-04 09:41
Adding ` lineDashPattern={null}` will also do your job. No need to downgrade

**Comment by christopherdro** [comment] 2021-07-05 23:11
Commit from https://github.com/react-native-maps/react-native-maps/pull/3797 has been reverted in 0.29.2.

**Comment by me-ibad** [comment] 2021-07-09 15:28
same error on both 0.27.1 and 0.28 any solution

**Comment by anfehernandez94** [comment] 2021-07-09 17:47
> same error on both 0.27.1 and 0.28 any solution?
> I am using expo and error come while using react-native-maps-directions

Add  `<MapViewDirections lineDashPattern={[number]} ... />` inside

**Comment by me-ibad** [comment] 2021-07-09 18:03
> ineDashPattern={[number]}

no same error

**Comment by douglaslondrina** [comment] 2021-07-12 12:56
For me, having the line dashed isn't a solution, so instead I temporarily used a Polygon with copied inverted coordinates - to avoid having a closed Polygon.

Btw, is there a `lineDashPattern` configuration that shows a filled line?
On my test, it's always plotted as dots.

**Comment by salah-ghanim** [comment] 2021-07-13 10:15
we need the stacktrace for android to fix this issue to identify where exactly the NPE is being thrown ... the JS stacktrace doesn't show that

**Comment by MarouaniALA** [comment] 2021-07-14 06:17
Hi, any news on this bug plz!

**Comment by douglaslondrina** [comment] 2021-07-14 18:30
Guys, I've created an issue ticket on Expo to ask them to push a new minor release with 0.29.2, but since 0.29.x is an alpha/beta release they can't publish a client update pointing to it.

So, Cedric, from Expo, suggested react-native-maps maintainers publish a 0.28.x release without the offending commit:

[https://github.com/expo/expo/issues/13584#issuecomment-879107991](https://github.com/expo/expo/issues/13584#issuecomment-879107991) 

Is that possible? Thank you!

**Comment by christopherdro** [comment] 2021-07-14 18:42
@douglaslondrina The offending commit was NOT included in v0.28.0. It was initially released with v0.29.0 and reverted in v0.29.2.

**Comment by douglaslondrina** [comment] 2021-07-14 19:43
Ok, thanks for clarifying Chris.
Strange that I see the crash with Expo's 42 release that includes rn-maps 0.28.0. Is it possible they pushed the wrong version upstream?

https://github.com/expo/expo/pull/13619

**Comment by byCedric** [comment] 2021-07-14 20:07
We are currently re-vendoring the version used in SDK 42. If that's the case, it should be fixed for Expo Go fairly soon. @douglaslondrina

**Comment by pdandradeb** [comment] 2021-07-15 13:38
Using geojson I was able to migrate from this:

```jsx
import polyline from '@mapbox/polyline';
import { Polyline } from 'react-native-maps';

const routePolyline = 'nxynCfh}{G_CxA_Aj@z@`BZn@jBrDpCtFpB|D]Po@`@g@\\';
const routeCoordinates = polyline.decode(routePolyline).map((pair) => {
  return { latitude: pair[0], longitude: pair[1] };
});
<Polyline coordinates={routeCoordinates} />
```

to this:

```jsx
import { Geojson } from 'react-native-maps';
import { FeatureCollection } from 'geojson';

const routePolyline = 'nxynCfh}{G_CxA_Aj@z@`BZn@jBrDpCtFpB|D]Po@`@g@\\';
const geojson: FeatureCollection = {
  type: 'FeatureCollection',
  features: [
    {
      type: 'Feature',
      properties: {},
      geometry: {
        ...polyline.toGeoJSON(routePolyline),
      },
    },
  ],
};

<Geojson
  geojson={geojson}
  strokeColor="black"
  fillColor="black"
  strokeWidth={1}
  lineCap="round"
/>
```

**Comment by josephcrowell** [comment] 2021-07-19 02:08
Could you leave a message here when this is resolved so we can refresh the packages?

**Comment by buribalazs** [comment] 2021-07-22 07:47
Sorry for the noob question. Is this issue only in expo-go now or in built apks too? I tried to build an apk now with expo build:android but it crashes. Not sure why, I was unable to debug with adb. I'm using react-native-maps 0.28.0. Thank you

**Comment by douglaslondrina** [comment] 2021-07-22 14:54
With expo, even when you build your APK, you're actually using the libraries bundled within the expo SDK. So even if you change rn-maps to 0.29.2, it will still use the native library for 0.28.0. For expo 42, my understanding is that it looks like Expo is using rn-maps 0.28.0, but in reality, the underlying lib is pointed to an unstable version.

So, we'll need to wait on an update from Expo. Meanwhile, there are some workarounds commented on above.

**Comment by lorenzo-portocarrero** [comment] 2021-07-23 03:28
For me it doesn't work with version 0.27.1 or 0.29.2 neither. I really wanted to show a straight line -not a dotted line- so I did a workaround. This works for the last version too

First I add this line inside my component, using the useState hook to store the initial state of the prop
`const [lineDashPattern, setLineDashPattern] = useState([0]);`

Then I retrieve some coordinates on my app inside useEffect, and once that's done I call `setLineDashPattern(null)`

The Polyline props should look like this:
```
<Polyline
          lineDashPattern={lineDashPattern}
          coordinates={coordinates}
          strokeColor="#FF0000"
          strokeWidth={6}
></Polyline>
```
The trick is to change the property during runtime, that way it doesn't throw the error. If you update the state too early -without waiting for 400ms or so-, it will start to fail again. I don't need to await because I'm doing a request before, but otherwise it will be needed

**Comment by arunpugahz** [comment] 2021-08-03 07:16
I'm using the expo app with SDK 42.
v0.28.0 works if I give add prop `lineDashPattern={[1]}` to `Polyline` component.
But It looks a bit weird. It would really be great if this is fixed

**Comment by Parth-2412** [comment] 2021-08-04 16:35
> For me it doesn't work with version 0.27.1, 0.28.0 or 0.29.2 neither. I really wanted to show a line -not a dotted line- so I did a workaround. This works for the last version too
> 
> First I add this line inside my component, using the useState hook to store the initial state of the prop
> `const [lineDashPattern, setLineDashPattern] = useState([0]);`
> 
> Then I retrieve some coordinates on my app inside useEffect, and once that's done I call `setLineDashPattern(null)`
> 
> The Polyline props should look like this:
> 
> ```
> <Polyline
>           lineDashPattern={lineDashPattern}
>           coordinates={coordinates}
>           strokeColor="#FF0000"
>           strokeWidth={6}
> ></Polyline>
> ```
> 
> The trick is to change the property during runtime, that way it doesn't throw the error. If you update the state too early -without waiting for 400ms or so-, it will start to fail again. I don't need to await because I'm doing a request before, but otherwise it will be needed

This worked for me!! I am using expo. Thanks for the answer!

**Comment by khelifioussama** [comment] 2021-08-30 10:48
Any solution please still crashing

**Comment by liangchaoqin** [comment] 2021-09-01 01:04
> For me it doesn't work with version 0.27.1, 0.28.0 or 0.29.2 neither. I really wanted to show a line -not a dotted line- so I did a workaround. This works for the last version too
> 
> First I add this line inside my component, using the useState hook to store the initial state of the prop
> `const [lineDashPattern, setLineDashPattern] = useState([0]);`
> 
> Then I retrieve some coordinates on my app inside useEffect, and once that's done I call `setLineDashPattern(null)`
> 
> The Polyline props should look like this:
> 
> ```
> <Polyline
>           lineDashPattern={lineDashPattern}
>           coordinates={coordinates}
>           strokeColor="#FF0000"
>           strokeWidth={6}
> ></Polyline>
> ```
> 
> The trick is to change the property during runtime, that way it doesn't throw the error. If you update the state too early -without waiting for 400ms or so-, it will start to fail again. I don't need to await because I'm doing a request before, but otherwise it will be needed

no woking in product

**Comment by Lena-Hubup** [comment] 2021-09-02 13:53
> For me, having the line dashed isn't a solution, so instead I temporarily used a Polygon with copied inverted coordinates - to avoid having a closed Polygon.
> 
> Btw, is there a `lineDashPattern` configuration that shows a filled line?
> On my test, it's always plotted as dots.

Same !

**Comment by johan-forestlink** [comment] 2021-09-03 08:59
Any update on when this will be solved? For us it's not an option to change the styling of the polyline.

**Comment by kstee** [comment] 2021-09-12 10:56
I am using expo, so I go to node_modules/react-native-maps/lib/components/MapPolyline.js and comment "lineJoin" and "lineCap" properties:

const defaultProps = {
  strokeColor: '#000',
  strokeWidth: 1,
  // lineJoin: 'round',
  // lineCap: 'round',
};

and it works because I found out "lineCap" cannot be set to default whenever the "lineDashPattern" property is null.

**Comment by josedavidgc** [comment] 2021-10-09 00:08
> I am using expo, so I go to node_modules/react-native-maps/lib/components/MapPolyline.js and comment "lineJoin" and "lineCap" properties:
> 
> const defaultProps = { strokeColor: '#0', strokeWidth: 1, // lineJoin: 'round', // lineCap: 'round', };
> 
> and it works because I found out "lineCap" cannot be set to default whenever the "lineDashPattern" property is null.

Kstee, thank you very much, it worked for me.

**Comment by ruimcf** [comment] 2021-11-04 19:48
> I am using expo, so I go to node_modules/react-native-maps/lib/components/MapPolyline.js and comment "lineJoin" and "lineCap" properties:
> 
> const defaultProps = { strokeColor: '#0', strokeWidth: 1, // lineJoin: 'round', // lineCap: 'round', };
> 
> and it works because I found out "lineCap" cannot be set to default whenever the "lineDashPattern" property is null.

This might work for a dev environment but there's not chance this will work for a published application

Any updates on this?

**Comment by LeoKaynan** [comment] 2021-11-14 19:58
> I am using expo, so I go to node_modules/react-native-maps/lib/components/MapPolyline.js and comment "lineJoin" and "lineCap" properties:
> 
> const defaultProps = { strokeColor: '#0', strokeWidth: 1, // lineJoin: 'round', // lineCap: 'round', };
> 
> and it works because I found out "lineCap" cannot be set to default whenever the "lineDashPattern" property is null.

Perfect!!

**Comment by jroux-git** [comment] 2021-11-28 12:12
Any progress on this issue maybe?

**Comment by uzbeki** [comment] 2021-12-03 07:38
no progress yet?

**Comment by uzbeki** [comment] 2021-12-03 07:38
How can I help?

**Comment by caminoninja** [comment] 2021-12-04 17:32
Got the same problem here, and without a workaround that works.

**Comment by josephcrowell** [comment] 2021-12-05 02:31
My solution was to rewrite my app in Flutter and I haven't regretted it yet.

**Comment by caminoninja** [comment] 2021-12-05 02:59
> 

Well then it won't be helpful to tell you how I worked around it

**Comment by LeoKaynan** [comment] 2021-12-05 23:56
0.29.3 - (August 29, 2021)
    Common: #3920 GeoJSON onPress Crash Fix and Marker Customization Options
    Common: #3930 Updated peer deps to maintain compatibility with expo init
0.29.2 - (July 5, 2021)
    Android: Revert #3797 Allow a previously dashed line to be made solid

**Comment by LeoKaynan** [comment] 2021-12-05 23:56
Try to update the module to the latest version.

**Comment by LeoKaynan** [comment] 2021-12-05 23:57
Try to update the module to the latest version
https://yarnpkg.com/package/react-native-maps

0.29.3 - (August 29, 2021)
    Common: #3920 GeoJSON onPress Crash Fix and Marker Customization Options
    Common: #3930 Updated peer deps to maintain compatibility with expo init
0.29.2 - (July 5, 2021)
    Android: Revert #3797 Allow a previously dashed line to be made solid

**Comment by LeoKaynan** [comment] 2021-12-06 02:00
> Any progress on this issue maybe?
Tutorial Video
https://www.youtube.com/watch?v=-FuYiPnSo6Q

**Comment by LeoKaynan** [comment] 2021-12-06 02:00
Tutorial Video
https://www.youtube.com/watch?v=-FuYiPnSo6Q

**Comment by apanagio** [comment] 2022-01-19 09:39
> Btw, is there a `lineDashPattern` configuration that shows a filled line?

Not actually a lineDashPattern, but if you set 
`lineCap="square"`
`lineDashPattern={[1]}` 
you get a filled line

**Comment by buitrbao222** [comment] 2022-01-25 06:51
Any progress? The solution by @apanagio works find but the line cap is not round so I can't use it in my case.

**Comment by Simon-TechForm** [comment] 2022-03-14 18:59
I'm only able to reproduce the issue put forward by the author in v.0.29.0 and v0.29.1.

Can anyone still experiencing this please get back to me with the following:

- Running expo? If yes, what version?
- What version of react-native-maps?
- [Minimal minimal-reproducible-example](https://stackoverflow.com/help/minimal-reproducible-example)
- Error message and stacktrace

**Closed** 2022-04-13 18:36 UTC
Labels: bug, help wanted

**Comment by Stephan-MDD** [comment] 2022-04-21 11:46
Hi @Simon-TechForm - I'm using a library called [react-native-map-clustering](https://www.npmjs.com/package/react-native-map-clustering). 

The issues occurs when multiple pins has the same coordinates. The library handles these clusters and expands when you click them. When the cluster is expanded every pin is connected with a PolyLine which causes the issue.

Changing the internal `PolyLine` props in the lib folder fixes the issue for me, as mentioned above. But I would prefer a solution without overwriting third-party module :)

> node_modules/react-native-map-clustering/lib/ClusteredMapView.js

- `expo` `^43.0.0`
- `react-native-maps`: `0.28.1`/ `0.30.1`
- `react-native-map-clustering`: `^3.4.2`

> I tried using the newest version (0.30.1) of `react-native-maps` but got the same error.

Thanks for your time :)

### Minimal example
```jsx
import React, { useState } from 'react'
import MapView from 'react-native-map-clustering'
import { Marker } from 'react-native-maps'

export function Map() {
  const [mapReady, setMapReady] = useState(false)

  const initialRegion = {
    latitude: 55.6711876,
    longitude: 12.4537421,
    latitudeDelta: 0.25,
    longitudeDelta: 0.25,
  }

  function getPins() {
    if (mapReady === false) return []

    const pins = [
      { lat: 55.6711876, lng: 12.4537421 },
      { lat: 55.6711876, lng: 12.4537421 },
    ]

    return pins
  }

  return (
    <MapView initialRegion={initialRegion} onLayout={() => setMapReady(true)} style={{ height: '100%', width: '100%' }}>
      {getPins().map((pin, index) => (
        <Marker key={index} identifier={index} coordinate={{ latitude: pin.lat, longitude: pin.lng }} />
      ))}
    </MapView>
  )
}
```
### Error message
Cant get logs in text format, hope these can help :)

![278915746_725953931925072_3597319293790910026_n](https://user-images.githubusercontent.com/37081797/164450237-4ee1a721-c2dd-4f2c-97ac-78cd6b01e01b.jpg)

![278649463_288319473501629_561281480984788637_n](https://user-images.githubusercontent.com/37081797/164450190-ca94ee05-b907-44b1-b3fd-4b01e9282dfd.jpg)

![278582600_949416459077300_1216634412091015604_n](https://user-images.githubusercontent.com/37081797/164450296-0ee34e99-d973-438a-9a04-f8c8a4f2af5c.jpg)
